// Code generated by girgen. DO NOT EDIT.

package gstva

import (
	"unsafe"

	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
)

// #include <stdlib.h>
import "C"

//export _gotk4_gstva1_VaDisplayClass_create_va_display
func _gotk4_gstva1_VaDisplayClass_create_va_display(arg0 *C.GstVaDisplay) (cret C.gpointer) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[VaDisplayOverrides](instance0)
	if overrides.CreateVaDisplay == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected VaDisplayOverrides.CreateVaDisplay, got none")
	}

	gpointer := overrides.CreateVaDisplay()

	var _ unsafe.Pointer

	cret = (C.gpointer)(unsafe.Pointer(gpointer))

	return cret
}
