// Code generated by girgen. DO NOT EDIT.

package gstva

import (
	"fmt"
	"runtime"
	_ "runtime/cgo"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gextras"
	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
	"github.com/diamondburned/gotk4/pkg/gst"
	"github.com/diamondburned/gotk4/pkg/gstvideo"
)

// #cgo pkg-config: gstreamer-va-1.0 gstreamer-analytics-1.0
// #cgo CFLAGS: -Wno-deprecated-declarations
// #include <stdlib.h>
// #include <glib-object.h>
// extern gpointer _gotk4_gstva1_VaDisplayClass_create_va_display(GstVaDisplay*);
// gpointer _gotk4_gstva1_VaDisplay_virtual_create_va_display(void* fnptr, GstVaDisplay* arg0) {
//   return ((gpointer (*)(GstVaDisplay*))(fnptr))(arg0);
// };
import "C"

// GType values.
var (
	GTypeVaFeature         = coreglib.Type(C.gst_va_feature_get_type())
	GTypeVaAllocator       = coreglib.Type(C.gst_va_allocator_get_type())
	GTypeVaDisplay         = coreglib.Type(C.gst_va_display_get_type())
	GTypeVaDisplayDRM      = coreglib.Type(C.gst_va_display_drm_get_type())
	GTypeVaDisplayWrapped  = coreglib.Type(C.gst_va_display_wrapped_get_type())
	GTypeVaDmabufAllocator = coreglib.Type(C.gst_va_dmabuf_allocator_get_type())
	GTypeVaPool            = coreglib.Type(C.gst_va_pool_get_type())
)

func init() {
	coreglib.RegisterGValueMarshalers([]coreglib.TypeMarshaler{
		coreglib.TypeMarshaler{T: GTypeVaFeature, F: marshalVaFeature},
		coreglib.TypeMarshaler{T: GTypeVaAllocator, F: marshalVaAllocator},
		coreglib.TypeMarshaler{T: GTypeVaDisplay, F: marshalVaDisplay},
		coreglib.TypeMarshaler{T: GTypeVaDisplayDRM, F: marshalVaDisplayDRM},
		coreglib.TypeMarshaler{T: GTypeVaDisplayWrapped, F: marshalVaDisplayWrapped},
		coreglib.TypeMarshaler{T: GTypeVaDmabufAllocator, F: marshalVaDmabufAllocator},
		coreglib.TypeMarshaler{T: GTypeVaPool, F: marshalVaPool},
	})
}

const ALLOCATOR_VASURFACE = "VAMemory"
const CAPS_FEATURE_MEMORY_VA = "memory:VAMemory"

// MAP_VA: flag indicating that we should map the VASurfaceID instead of
// to system memory, so users can use libva primitives to operate with that
// surface.
const MAP_VA = 131072
const VA_DISPLAY_HANDLE_CONTEXT_TYPE_STR = "gst.va.display.handle"

type VaFeature C.gint

const (
	// VaFeatureDisabled: feature is disabled.
	VaFeatureDisabled VaFeature = iota
	// VaFeatureEnabled: feature is enabled.
	VaFeatureEnabled
	// VaFeatureAuto: feature is enabled automatically.
	VaFeatureAuto
)

func marshalVaFeature(p uintptr) (interface{}, error) {
	return VaFeature(coreglib.ValueFromNative(unsafe.Pointer(p)).Enum()), nil
}

// String returns the name in string for VaFeature.
func (v VaFeature) String() string {
	switch v {
	case VaFeatureDisabled:
		return "Disabled"
	case VaFeatureEnabled:
		return "Enabled"
	case VaFeatureAuto:
		return "Auto"
	default:
		return fmt.Sprintf("VaFeature(%d)", v)
	}
}

// VaImplementation types of different VA API implemented drivers. These are the
// typical and the most widely used VA drivers.
type VaImplementation C.gint

const (
	// VaImplementationMesaGallium: mesa gallium implementation.
	VaImplementationMesaGallium VaImplementation = iota
	// VaImplementationIntelI965: legacy i965 intel implementation.
	VaImplementationIntelI965
	// VaImplementationIntelIhd: iHD intel implementation.
	VaImplementationIntelIhd
	// VaImplementationOther: other implementation.
	VaImplementationOther
	// VaImplementationInvalid: invalid implementation.
	VaImplementationInvalid
)

// String returns the name in string for VaImplementation.
func (v VaImplementation) String() string {
	switch v {
	case VaImplementationMesaGallium:
		return "MesaGallium"
	case VaImplementationIntelI965:
		return "IntelI965"
	case VaImplementationIntelIhd:
		return "IntelIhd"
	case VaImplementationOther:
		return "Other"
	case VaImplementationInvalid:
		return "Invalid"
	default:
		return fmt.Sprintf("VaImplementation(%d)", v)
	}
}

// BufferPoolConfigSetVaAlignment: video alignment is not handled as expected
// by VA since it uses opaque surfaces, not directly mappable memory. Still,
// decoders might need to request bigger surfaces for coded size rather
// than display sizes. This method will set the coded size to bufferpool's
// configuration, out of the typical video aligment.
//
// The function takes the following parameters:
//
//   - config with the pool's configuration.
//   - align: VideoAlignment.
func BufferPoolConfigSetVaAlignment(config *gst.Structure, align *gstvideo.VideoAlignment) {
	var _arg1 *C.GstStructure      // out
	var _arg2 *C.GstVideoAlignment // out

	_arg1 = (*C.GstStructure)(gextras.StructNative(unsafe.Pointer(config)))
	_arg2 = (*C.GstVideoAlignment)(gextras.StructNative(unsafe.Pointer(align)))

	C.gst_buffer_pool_config_set_va_alignment(_arg1, _arg2)
	runtime.KeepAlive(config)
	runtime.KeepAlive(align)
}

// BufferPoolConfigSetVaAllocationParams sets the usage hint for the buffers
// handled by the buffer pool.
//
// The function takes the following parameters:
//
//   - config with the pool's configuration.
//   - usageHint: VA usage hint for new VASurfaceID.
//   - useDerived for derived mapping (only used when VA allocator).
func BufferPoolConfigSetVaAllocationParams(config *gst.Structure, usageHint uint, useDerived VaFeature) {
	var _arg1 *C.GstStructure // out
	var _arg2 C.guint         // out
	var _arg3 C.GstVaFeature  // out

	_arg1 = (*C.GstStructure)(gextras.StructNative(unsafe.Pointer(config)))
	_arg2 = C.guint(usageHint)
	_arg3 = C.GstVaFeature(useDerived)

	C.gst_buffer_pool_config_set_va_allocation_params(_arg1, _arg2, _arg3)
	runtime.KeepAlive(config)
	runtime.KeepAlive(usageHint)
	runtime.KeepAlive(useDerived)
}

// The function takes the following parameters:
//
//   - context may contain the display.
//   - typeName string of the element type.
//   - renderDevicePath string of render device path.
//
// The function returns the following values:
//
//   - displayPtr we get.
//   - ok: whether we find a valid display in the context.
func ContextGetVaDisplay(context *gst.Context, typeName, renderDevicePath string) (*VaDisplay, bool) {
	var _arg1 *C.GstContext   // out
	var _arg2 *C.gchar        // out
	var _arg3 *C.gchar        // out
	var _arg4 *C.GstVaDisplay // in
	var _cret C.gboolean      // in

	_arg1 = (*C.GstContext)(gextras.StructNative(unsafe.Pointer(context)))
	_arg2 = (*C.gchar)(unsafe.Pointer(C.CString(typeName)))
	defer C.free(unsafe.Pointer(_arg2))
	_arg3 = (*C.gchar)(unsafe.Pointer(C.CString(renderDevicePath)))
	defer C.free(unsafe.Pointer(_arg3))

	_cret = C.gst_context_get_va_display(_arg1, _arg2, _arg3, &_arg4)
	runtime.KeepAlive(context)
	runtime.KeepAlive(typeName)
	runtime.KeepAlive(renderDevicePath)

	var _displayPtr *VaDisplay // out
	var _ok bool               // out

	_displayPtr = wrapVaDisplay(coreglib.AssumeOwnership(unsafe.Pointer(_arg4)))
	if _cret != 0 {
		_ok = true
	}

	return _displayPtr, _ok
}

// ContextSetVaDisplay: set the display in the context.
//
// The function takes the following parameters:
//
//   - context: Context.
//   - display we want to set.
func ContextSetVaDisplay(context *gst.Context, display *VaDisplay) {
	var _arg1 *C.GstContext   // out
	var _arg2 *C.GstVaDisplay // out

	_arg1 = (*C.GstContext)(gextras.StructNative(unsafe.Pointer(context)))
	_arg2 = (*C.GstVaDisplay)(unsafe.Pointer(coreglib.InternObject(display).Native()))

	C.gst_context_set_va_display(_arg1, _arg2)
	runtime.KeepAlive(context)
	runtime.KeepAlive(display)
}

// VaBufferCreateAuxSurface creates a new VASurfaceID with buffer's allocator
// and attached it to it.
//
// *This method is used only by plugin's internal VA decoder.*.
//
// The function takes the following parameters:
//
//   - buffer: Buffer.
//
// The function returns the following values:
//
//   - ok: TRUE if the new VASurfaceID is attached to buffer correctly; FALSE,
//     otherwise.
func VaBufferCreateAuxSurface(buffer *gst.Buffer) bool {
	var _arg1 *C.GstBuffer // out
	var _cret C.gboolean   // in

	_arg1 = (*C.GstBuffer)(gextras.StructNative(unsafe.Pointer(buffer)))

	_cret = C.gst_va_buffer_create_aux_surface(_arg1)
	runtime.KeepAlive(buffer)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// The function takes the following parameters:
//
//   - buffer: Buffer.
//
// The function returns the following values:
//
//   - vaDisplay: display which this buffer belongs to. The reference of the
//     display is unchanged.
func VaBufferPeekDisplay(buffer *gst.Buffer) *VaDisplay {
	var _arg1 *C.GstBuffer    // out
	var _cret *C.GstVaDisplay // in

	_arg1 = (*C.GstBuffer)(gextras.StructNative(unsafe.Pointer(buffer)))

	_cret = C.gst_va_buffer_peek_display(_arg1)
	runtime.KeepAlive(buffer)

	var _vaDisplay *VaDisplay // out

	_vaDisplay = wrapVaDisplay(coreglib.Take(unsafe.Pointer(_cret)))

	return _vaDisplay
}

// VaContextQuery: query the specified context type name.
//
// The function takes the following parameters:
//
//   - element: Element.
//   - contextType string specify the context type name.
func VaContextQuery(element gst.Elementer, contextType string) {
	var _arg1 *C.GstElement // out
	var _arg2 *C.gchar      // out

	_arg1 = (*C.GstElement)(unsafe.Pointer(coreglib.InternObject(element).Native()))
	_arg2 = (*C.gchar)(unsafe.Pointer(C.CString(contextType)))
	defer C.free(unsafe.Pointer(_arg2))

	C.gst_va_context_query(_arg1, _arg2)
	runtime.KeepAlive(element)
	runtime.KeepAlive(contextType)
}

// VaDmabufGetModifierForFormat: get the underlying modifier for specified
// format and usage_hint.
//
// The function takes the following parameters:
//
//   - display: VaDisplay.
//   - format: VideoFormat.
//   - usageHint: VA usage hint.
//
// The function returns the following values:
//
//   - guint64: underlying modifier.
func VaDmabufGetModifierForFormat(display *VaDisplay, format gstvideo.VideoFormat, usageHint uint) uint64 {
	var _arg1 *C.GstVaDisplay  // out
	var _arg2 C.GstVideoFormat // out
	var _arg3 C.guint          // out
	var _cret C.guint64        // in

	_arg1 = (*C.GstVaDisplay)(unsafe.Pointer(coreglib.InternObject(display).Native()))
	_arg2 = C.GstVideoFormat(format)
	_arg3 = C.guint(usageHint)

	_cret = C.gst_va_dmabuf_get_modifier_for_format(_arg1, _arg2, _arg3)
	runtime.KeepAlive(display)
	runtime.KeepAlive(format)
	runtime.KeepAlive(usageHint)

	var _guint64 uint64 // out

	_guint64 = uint64(_cret)

	return _guint64
}

// VaDmabufMemoriesSetup: it imports the array of mem, representing a single
// frame, into a VASurfaceID and it's attached into every mem.
//
// The function takes the following parameters:
//
//   - display: VaDisplay.
//   - drmInfo: VideoInfoDmaDrm.
//   - mem: memories. One per plane.
//   - fds: array of DMABuf file descriptors.
//   - offset: array of memory offsets.
//   - usageHint: VA usage hint.
//
// The function returns the following values:
//
//   - ok: TRUE if frame is imported correctly into a VASurfaceID; FALSE
//     otherwise.
func VaDmabufMemoriesSetup(display *VaDisplay, drmInfo *gstvideo.VideoInfoDmaDRM, mem [4]*gst.Memory, fds [4]uintptr, offset [4]uint, usageHint uint) bool {
	var _arg1 *C.GstVaDisplay       // out
	var _arg2 *C.GstVideoInfoDmaDrm // out
	var _arg3 **C.GstMemory         // out
	var _arg4 *C.uintptr_t          // out
	var _arg5 *C.gsize              // out
	var _arg6 C.guint               // out
	var _cret C.gboolean            // in

	_arg1 = (*C.GstVaDisplay)(unsafe.Pointer(coreglib.InternObject(display).Native()))
	_arg2 = (*C.GstVideoInfoDmaDrm)(gextras.StructNative(unsafe.Pointer(drmInfo)))
	{
		var out [4]*C.GstMemory
		_arg3 = &out[0]
		for i := 0; i < 4; i++ {
			out[i] = (*C.GstMemory)(gextras.StructNative(unsafe.Pointer(mem[i])))
		}
	}
	_arg4 = (*C.uintptr_t)(unsafe.Pointer(&fds))
	_arg5 = (*C.gsize)(unsafe.Pointer(&offset))
	_arg6 = C.guint(usageHint)

	_cret = C.gst_va_dmabuf_memories_setup(_arg1, _arg2, _arg3, _arg4, _arg5, _arg6)
	runtime.KeepAlive(display)
	runtime.KeepAlive(drmInfo)
	runtime.KeepAlive(mem)
	runtime.KeepAlive(fds)
	runtime.KeepAlive(offset)
	runtime.KeepAlive(usageHint)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// VaElementPropagateDisplayContext: propagate display by posting it as Context
// in the pipeline's bus.
//
// The function takes the following parameters:
//
//   - element: Element.
//   - display to propagate.
func VaElementPropagateDisplayContext(element gst.Elementer, display *VaDisplay) {
	var _arg1 *C.GstElement   // out
	var _arg2 *C.GstVaDisplay // out

	_arg1 = (*C.GstElement)(unsafe.Pointer(coreglib.InternObject(element).Native()))
	_arg2 = (*C.GstVaDisplay)(unsafe.Pointer(coreglib.InternObject(display).Native()))

	C.gst_va_element_propagate_display_context(_arg1, _arg2)
	runtime.KeepAlive(element)
	runtime.KeepAlive(display)
}

// VaEnsureElementData: called by the va element to ensure a valid VaDisplay.
//
// The function takes the following parameters:
//
//   - element (optional): Element.
//   - renderDevicePath string of render device path.
//
// The function returns the following values:
//
//   - displayPtr to ensure.
//   - ok: whether a VaDisplay exists in display_ptr.
func VaEnsureElementData(element unsafe.Pointer, renderDevicePath string) (*VaDisplay, bool) {
	var _arg1 C.gpointer      // out
	var _arg2 *C.gchar        // out
	var _arg3 *C.GstVaDisplay // in
	var _cret C.gboolean      // in

	_arg1 = (C.gpointer)(unsafe.Pointer(element))
	_arg2 = (*C.gchar)(unsafe.Pointer(C.CString(renderDevicePath)))
	defer C.free(unsafe.Pointer(_arg2))

	_cret = C.gst_va_ensure_element_data(_arg1, _arg2, &_arg3)
	runtime.KeepAlive(element)
	runtime.KeepAlive(renderDevicePath)

	var _displayPtr *VaDisplay // out
	var _ok bool               // out

	_displayPtr = wrapVaDisplay(coreglib.AssumeOwnership(unsafe.Pointer(_arg3)))
	if _cret != 0 {
		_ok = true
	}

	return _displayPtr, _ok
}

// VaHandleContextQuery: used by elements when processing their pad's queries,
// propagating element's VaDisplay if the processed query requests it.
//
// The function takes the following parameters:
//
//   - element: Element.
//   - query to query the context.
//   - display to answer the query.
//
// The function returns the following values:
//
//   - ok: whether we can handle the context query successfully.
func VaHandleContextQuery(element gst.Elementer, query *gst.Query, display *VaDisplay) bool {
	var _arg1 *C.GstElement   // out
	var _arg2 *C.GstQuery     // out
	var _arg3 *C.GstVaDisplay // out
	var _cret C.gboolean      // in

	_arg1 = (*C.GstElement)(unsafe.Pointer(coreglib.InternObject(element).Native()))
	_arg2 = (*C.GstQuery)(gextras.StructNative(unsafe.Pointer(query)))
	_arg3 = (*C.GstVaDisplay)(unsafe.Pointer(coreglib.InternObject(display).Native()))

	_cret = C.gst_va_handle_context_query(_arg1, _arg2, _arg3)
	runtime.KeepAlive(element)
	runtime.KeepAlive(query)
	runtime.KeepAlive(display)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// VaHandleSetContext: called by elements in their ElementClass::set_context
// vmethod. It gets a valid VaDisplay if context has it.
//
// The function takes the following parameters:
//
//   - element: Element.
//   - context may contain the display.
//   - renderDevicePath string of render device path.
//
// The function returns the following values:
//
//   - displayPtr to set.
//   - ok: whether the display_ptr could be successfully set to a valid
//     VaDisplay in the context.
func VaHandleSetContext(element gst.Elementer, context *gst.Context, renderDevicePath string) (*VaDisplay, bool) {
	var _arg1 *C.GstElement   // out
	var _arg2 *C.GstContext   // out
	var _arg3 *C.gchar        // out
	var _arg4 *C.GstVaDisplay // in
	var _cret C.gboolean      // in

	_arg1 = (*C.GstElement)(unsafe.Pointer(coreglib.InternObject(element).Native()))
	_arg2 = (*C.GstContext)(gextras.StructNative(unsafe.Pointer(context)))
	_arg3 = (*C.gchar)(unsafe.Pointer(C.CString(renderDevicePath)))
	defer C.free(unsafe.Pointer(_arg3))

	_cret = C.gst_va_handle_set_context(_arg1, _arg2, _arg3, &_arg4)
	runtime.KeepAlive(element)
	runtime.KeepAlive(context)
	runtime.KeepAlive(renderDevicePath)

	var _displayPtr *VaDisplay // out
	var _ok bool               // out

	_displayPtr = wrapVaDisplay(coreglib.AssumeOwnership(unsafe.Pointer(_arg4)))
	if _cret != 0 {
		_ok = true
	}

	return _displayPtr, _ok
}

// The function takes the following parameters:
//
//   - mem: Memory.
//
// The function returns the following values:
//
//   - vaDisplay: display which this mem belongs to. The reference of the
//     display is unchanged.
func VaMemoryPeekDisplay(mem *gst.Memory) *VaDisplay {
	var _arg1 *C.GstMemory    // out
	var _cret *C.GstVaDisplay // in

	_arg1 = (*C.GstMemory)(gextras.StructNative(unsafe.Pointer(mem)))

	_cret = C.gst_va_memory_peek_display(_arg1)
	runtime.KeepAlive(mem)

	var _vaDisplay *VaDisplay // out

	_vaDisplay = wrapVaDisplay(coreglib.Take(unsafe.Pointer(_cret)))

	return _vaDisplay
}

// VaAllocator: there are two types of VA allocators:
//
// * VaAllocator * VaDmabufAllocator.
type VaAllocator struct {
	_ [0]func() // equal guard
	gst.Allocator
}

var (
	_ gst.Allocatorrer = (*VaAllocator)(nil)
)

func wrapVaAllocator(obj *coreglib.Object) *VaAllocator {
	return &VaAllocator{
		Allocator: gst.Allocator{
			GstObject: gst.GstObject{
				InitiallyUnowned: coreglib.InitiallyUnowned{
					Object: obj,
				},
			},
		},
	}
}

func marshalVaAllocator(p uintptr) (interface{}, error) {
	return wrapVaAllocator(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// NewVaAllocator: instanciate a new pooled Allocator backed by VASurfaceID.
//
// The function takes the following parameters:
//
//   - display: VaDisplay.
//   - surfaceFormats: #GArray of valid VideoFormat for surfaces in current VA
//     context.
//
// The function returns the following values:
//
//   - vaAllocator: VaDisplay.
func NewVaAllocator(display *VaDisplay, surfaceFormats []uint) *VaAllocator {
	var _arg1 *C.GstVaDisplay // out
	var _arg2 *C.GArray       // out
	var _cret *C.GstAllocator // in

	_arg1 = (*C.GstVaDisplay)(unsafe.Pointer(coreglib.InternObject(display).Native()))
	_arg2 = C.g_array_sized_new(false, false, C.guint(C.sizeof_GArray), C.guint(len(surfaceFormats)))
	_arg2 = C.g_array_set_size(_arg2, C.guint(len(surfaceFormats)))
	{
		out := unsafe.Slice(_arg2.data, len(surfaceFormats))
		for i := range surfaceFormats {
			out[i] = C.GArray(surfaceFormats[i])
		}
	}

	_cret = C.gst_va_allocator_new(_arg1, _arg2)
	runtime.KeepAlive(display)
	runtime.KeepAlive(surfaceFormats)

	var _vaAllocator *VaAllocator // out

	_vaAllocator = wrapVaAllocator(coreglib.Take(unsafe.Pointer(_cret)))

	return _vaAllocator
}

// VaAllocatorAlloc: allocate a new VASurfaceID backed Memory.
//
// The function takes the following parameters:
//
//   - allocator: Allocator.
//
// The function returns the following values:
//
//   - memory backed with a VASurfaceID; NULL, otherwise.
func VaAllocatorAlloc(allocator gst.Allocatorrer) *gst.Memory {
	var _arg1 *C.GstAllocator // out
	var _cret *C.GstMemory    // in

	_arg1 = (*C.GstAllocator)(unsafe.Pointer(coreglib.InternObject(allocator).Native()))

	_cret = C.gst_va_allocator_alloc(_arg1)
	runtime.KeepAlive(allocator)

	var _memory *gst.Memory // out

	_memory = (*gst.Memory)(gextras.NewStructNative(unsafe.Pointer(_cret)))
	runtime.SetFinalizer(
		gextras.StructIntern(unsafe.Pointer(_memory)),
		func(intern *struct{ C unsafe.Pointer }) {
			C.free(intern.C)
		},
	)

	return _memory
}

// VaAllocatorFlush removes all the memories in allocator's pool.
//
// The function takes the following parameters:
//
//   - allocator: Allocator.
func VaAllocatorFlush(allocator gst.Allocatorrer) {
	var _arg1 *C.GstAllocator // out

	_arg1 = (*C.GstAllocator)(unsafe.Pointer(coreglib.InternObject(allocator).Native()))

	C.gst_va_allocator_flush(_arg1)
	runtime.KeepAlive(allocator)
}

// VaAllocatorGetFormat gets current internal configuration of allocator.
//
// The function takes the following parameters:
//
//   - allocator: Allocator.
//
// The function returns the following values:
//
//   - info (optional): VideoInfo.
//   - usageHint (optional): VA usage hint.
//   - useDerived (optional): whether derived images are used for buffer
//     mapping.
//   - ok: TRUE if allocator is already configured; FALSE otherwise.
func VaAllocatorGetFormat(allocator gst.Allocatorrer) (info *gstvideo.VideoInfo, usageHint uint, useDerived, ok bool) {
	var _arg1 *C.GstAllocator // out
	var _arg2 C.GstVideoInfo  // in
	var _arg3 C.guint         // in
	var _arg4 C.gboolean      // in
	var _cret C.gboolean      // in

	_arg1 = (*C.GstAllocator)(unsafe.Pointer(coreglib.InternObject(allocator).Native()))

	_cret = C.gst_va_allocator_get_format(_arg1, &_arg2, &_arg3, &_arg4)
	runtime.KeepAlive(allocator)

	var _info *gstvideo.VideoInfo // out
	var _usageHint uint           // out
	var _useDerived bool          // out
	var _ok bool                  // out

	_info = (*gstvideo.VideoInfo)(gextras.NewStructNative(unsafe.Pointer((&_arg2))))
	_usageHint = uint(_arg3)
	if _arg4 != 0 {
		_useDerived = true
	}
	if _cret != 0 {
		_ok = true
	}

	return _info, _usageHint, _useDerived, _ok
}

// The function takes the following parameters:
//
//   - allocator: Allocator.
//
// The function returns the following values:
//
//   - vaDisplay: display which this allocator belongs to. The reference of the
//     display is unchanged.
func VaAllocatorPeekDisplay(allocator gst.Allocatorrer) *VaDisplay {
	var _arg1 *C.GstAllocator // out
	var _cret *C.GstVaDisplay // in

	_arg1 = (*C.GstAllocator)(unsafe.Pointer(coreglib.InternObject(allocator).Native()))

	_cret = C.gst_va_allocator_peek_display(_arg1)
	runtime.KeepAlive(allocator)

	var _vaDisplay *VaDisplay // out

	_vaDisplay = wrapVaDisplay(coreglib.Take(unsafe.Pointer(_cret)))

	return _vaDisplay
}

// VaAllocatorPrepareBuffer: this method will populate buffer with pooled
// VASurfaceID memories. It doesn't allocate new VASurfacesID.
//
// The function takes the following parameters:
//
//   - allocator: Allocator.
//   - buffer: empty Buffer.
//
// The function returns the following values:
//
//   - ok: TRUE if buffer was populated correctly; FALSE otherwise.
func VaAllocatorPrepareBuffer(allocator gst.Allocatorrer, buffer *gst.Buffer) bool {
	var _arg1 *C.GstAllocator // out
	var _arg2 *C.GstBuffer    // out
	var _cret C.gboolean      // in

	_arg1 = (*C.GstAllocator)(unsafe.Pointer(coreglib.InternObject(allocator).Native()))
	_arg2 = (*C.GstBuffer)(gextras.StructNative(unsafe.Pointer(buffer)))

	_cret = C.gst_va_allocator_prepare_buffer(_arg1, _arg2)
	runtime.KeepAlive(allocator)
	runtime.KeepAlive(buffer)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// VaAllocatorSetupBuffer populates an empty buffer with a VASuface backed
// Memory.
//
// The function takes the following parameters:
//
//   - allocator: Allocator.
//   - buffer: Buffer.
//
// The function returns the following values:
//
//   - ok: TRUE if buffer is populated; FALSE otherwise.
func VaAllocatorSetupBuffer(allocator gst.Allocatorrer, buffer *gst.Buffer) bool {
	var _arg1 *C.GstAllocator // out
	var _arg2 *C.GstBuffer    // out
	var _cret C.gboolean      // in

	_arg1 = (*C.GstAllocator)(unsafe.Pointer(coreglib.InternObject(allocator).Native()))
	_arg2 = (*C.GstBuffer)(gextras.StructNative(unsafe.Pointer(buffer)))

	_cret = C.gst_va_allocator_setup_buffer(_arg1, _arg2)
	runtime.KeepAlive(allocator)
	runtime.KeepAlive(buffer)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// VaDisplayOverrides contains methods that are overridable.
type VaDisplayOverrides struct {
	// CreateVaDisplay: this is called when the subclass has to create the
	// internal VADisplay.
	//
	// The function returns the following values:
	//
	//   - gpointer (optional): created VADisplay.
	CreateVaDisplay func() unsafe.Pointer
}

func defaultVaDisplayOverrides(v *VaDisplay) VaDisplayOverrides {
	return VaDisplayOverrides{
		CreateVaDisplay: v.createVaDisplay,
	}
}

// VaDisplay: it is a generic wrapper for VADisplay. To create new instances
// subclasses are required, depending on the display type to use (v.gr. DRM,
// X11, Wayland, etc.).
//
// The purpose of this class is to be shared among pipelines via Context so
// all the VA processing elements will use the same display entry. Application
// developers can create their own subclass, based on their display, and shared
// it via the synced bus message for the application.
type VaDisplay struct {
	_ [0]func() // equal guard
	gst.GstObject
}

var (
	_ gst.GstObjector = (*VaDisplay)(nil)
)

func init() {
	coreglib.RegisterClassInfo[*VaDisplay, *VaDisplayClass, VaDisplayOverrides](
		GTypeVaDisplay,
		initVaDisplayClass,
		wrapVaDisplay,
		defaultVaDisplayOverrides,
	)
}

func initVaDisplayClass(gclass unsafe.Pointer, overrides VaDisplayOverrides, classInitFunc func(*VaDisplayClass)) {
	pclass := (*C.GstVaDisplayClass)(unsafe.Pointer(C.g_type_check_class_cast((*C.GTypeClass)(gclass), C.GType(GTypeVaDisplay))))

	if overrides.CreateVaDisplay != nil {
		pclass.create_va_display = (*[0]byte)(C._gotk4_gstva1_VaDisplayClass_create_va_display)
	}

	if classInitFunc != nil {
		class := (*VaDisplayClass)(gextras.NewStructNative(gclass))
		classInitFunc(class)
	}
}

func wrapVaDisplay(obj *coreglib.Object) *VaDisplay {
	return &VaDisplay{
		GstObject: gst.GstObject{
			InitiallyUnowned: coreglib.InitiallyUnowned{
				Object: obj,
			},
		},
	}
}

func marshalVaDisplay(p uintptr) (interface{}, error) {
	return wrapVaDisplay(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// The function takes the following parameters:
//
//   - major version to check.
//   - minor version to check.
//
// The function returns the following values:
//
//   - ok: whether driver version is equal or greater than major.minor.
func (self *VaDisplay) CheckVersion(major, minor uint) bool {
	var _arg0 *C.GstVaDisplay // out
	var _arg1 C.guint         // out
	var _arg2 C.guint         // out
	var _cret C.gboolean      // in

	_arg0 = (*C.GstVaDisplay)(unsafe.Pointer(coreglib.InternObject(self).Native()))
	_arg1 = C.guint(major)
	_arg2 = C.guint(minor)

	_cret = C.gst_va_display_check_version(_arg0, _arg1, _arg2)
	runtime.KeepAlive(self)
	runtime.KeepAlive(major)
	runtime.KeepAlive(minor)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// Implementation: get the the VaImplementation type of self.
//
// The function returns the following values:
//
//   - vaImplementation: VaImplementation.
func (self *VaDisplay) Implementation() VaImplementation {
	var _arg0 *C.GstVaDisplay       // out
	var _cret C.GstVaImplementation // in

	_arg0 = (*C.GstVaDisplay)(unsafe.Pointer(coreglib.InternObject(self).Native()))

	_cret = C.gst_va_display_get_implementation(_arg0)
	runtime.KeepAlive(self)

	var _vaImplementation VaImplementation // out

	_vaImplementation = VaImplementation(_cret)

	return _vaImplementation
}

// VaDpy: get the VA display handle of the self.
//
// The function returns the following values:
//
//   - gpointer (optional): VA display handle.
func (self *VaDisplay) VaDpy() unsafe.Pointer {
	var _arg0 *C.GstVaDisplay // out
	var _cret C.gpointer      // in

	_arg0 = (*C.GstVaDisplay)(unsafe.Pointer(coreglib.InternObject(self).Native()))

	_cret = C.gst_va_display_get_va_dpy(_arg0)
	runtime.KeepAlive(self)

	var _gpointer unsafe.Pointer // out

	_gpointer = (unsafe.Pointer)(unsafe.Pointer(_cret))

	return _gpointer
}

// Initialize: if the display is set by the user (foreign) it is assumed that
// the driver is already initialized, thus this function is noop.
//
// If the display is opened internally, this function will initialize the driver
// and it will set driver's message callbacks.
//
// NOTE: this function is supposed to be private, only used by GstVaDisplay
// descendants.
//
// The function returns the following values:
//
//   - ok: TRUE if the VA driver can be initialized; FALSE otherwise.
func (self *VaDisplay) Initialize() bool {
	var _arg0 *C.GstVaDisplay // out
	var _cret C.gboolean      // in

	_arg0 = (*C.GstVaDisplay)(unsafe.Pointer(coreglib.InternObject(self).Native()))

	_cret = C.gst_va_display_initialize(_arg0)
	runtime.KeepAlive(self)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// createVaDisplay: this is called when the subclass has to create the internal
// VADisplay.
//
// The function returns the following values:
//
//   - gpointer (optional): created VADisplay.
func (self *VaDisplay) createVaDisplay() unsafe.Pointer {
	gclass := (*C.GstVaDisplayClass)(coreglib.PeekParentClass(self))
	fnarg := gclass.create_va_display

	var _arg0 *C.GstVaDisplay // out
	var _cret C.gpointer      // in

	_arg0 = (*C.GstVaDisplay)(unsafe.Pointer(coreglib.InternObject(self).Native()))

	_cret = C._gotk4_gstva1_VaDisplay_virtual_create_va_display(unsafe.Pointer(fnarg), _arg0)
	runtime.KeepAlive(self)

	var _gpointer unsafe.Pointer // out

	_gpointer = (unsafe.Pointer)(unsafe.Pointer(_cret))

	return _gpointer
}

// VaDisplayDRM: this is a VaDisplay subclass to instantiate with DRM devices.
type VaDisplayDRM struct {
	_ [0]func() // equal guard
	VaDisplay
}

var (
	_ gst.GstObjector = (*VaDisplayDRM)(nil)
)

func wrapVaDisplayDRM(obj *coreglib.Object) *VaDisplayDRM {
	return &VaDisplayDRM{
		VaDisplay: VaDisplay{
			GstObject: gst.GstObject{
				InitiallyUnowned: coreglib.InitiallyUnowned{
					Object: obj,
				},
			},
		},
	}
}

func marshalVaDisplayDRM(p uintptr) (interface{}, error) {
	return wrapVaDisplayDRM(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// NewVaDisplayDRMFromPath creates a new VaDisplay from a DRM device . It will
// try to open and operate the device in path.
//
// The function takes the following parameters:
//
//   - path to the DRM device.
//
// The function returns the following values:
//
//   - vaDisplayDrm: newly allocated VaDisplay if the specified DRM render
//     device could be opened and initialized; otherwise NULL is returned.
func NewVaDisplayDRMFromPath(path string) *VaDisplayDRM {
	var _arg1 *C.gchar        // out
	var _cret *C.GstVaDisplay // in

	_arg1 = (*C.gchar)(unsafe.Pointer(C.CString(path)))
	defer C.free(unsafe.Pointer(_arg1))

	_cret = C.gst_va_display_drm_new_from_path(_arg1)
	runtime.KeepAlive(path)

	var _vaDisplayDrm *VaDisplayDRM // out

	_vaDisplayDrm = wrapVaDisplayDRM(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))

	return _vaDisplayDrm
}

// VaDisplayWrapped: this is a VaDisplay instantiaton subclass for custom
// created VADisplay, such as X11 or Wayland, wrapping it.
type VaDisplayWrapped struct {
	_ [0]func() // equal guard
	VaDisplay
}

var (
	_ gst.GstObjector = (*VaDisplayWrapped)(nil)
)

func wrapVaDisplayWrapped(obj *coreglib.Object) *VaDisplayWrapped {
	return &VaDisplayWrapped{
		VaDisplay: VaDisplay{
			GstObject: gst.GstObject{
				InitiallyUnowned: coreglib.InitiallyUnowned{
					Object: obj,
				},
			},
		},
	}
}

func marshalVaDisplayWrapped(p uintptr) (interface{}, error) {
	return wrapVaDisplayWrapped(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// NewVaDisplayWrapped creates a VaDisplay wrapping an already created and
// initialized VADisplay.
//
// The lifetime of handle must be hold by the provider while the pipeline is
// instantiated. Do not call vaTerminate on it while the pipeline is not in NULL
// state.
//
// The function takes the following parameters:
//
//   - handle (optional): VADisplay to wrap.
//
// The function returns the following values:
//
//   - vaDisplayWrapped: new VaDisplay if handle is valid, Otherwise NULL.
func NewVaDisplayWrapped(handle unsafe.Pointer) *VaDisplayWrapped {
	var _arg1 C.gpointer      // out
	var _cret *C.GstVaDisplay // in

	_arg1 = (C.gpointer)(unsafe.Pointer(handle))

	_cret = C.gst_va_display_wrapped_new(_arg1)
	runtime.KeepAlive(handle)

	var _vaDisplayWrapped *VaDisplayWrapped // out

	_vaDisplayWrapped = wrapVaDisplayWrapped(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))

	return _vaDisplayWrapped
}

// VaDmabufAllocator: pooled memory allocator backed by the DMABufs exported
// from a VASurfaceID. Also it is possible to import DMAbufs into a VASurfaceID.
type VaDmabufAllocator struct {
	_ [0]func() // equal guard
	gst.Allocator
}

var (
	_ gst.Allocatorrer = (*VaDmabufAllocator)(nil)
)

func wrapVaDmabufAllocator(obj *coreglib.Object) *VaDmabufAllocator {
	return &VaDmabufAllocator{
		Allocator: gst.Allocator{
			GstObject: gst.GstObject{
				InitiallyUnowned: coreglib.InitiallyUnowned{
					Object: obj,
				},
			},
		},
	}
}

func marshalVaDmabufAllocator(p uintptr) (interface{}, error) {
	return wrapVaDmabufAllocator(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// NewVaDmabufAllocator: instanciate a new pooled allocator backed with both
// DMABuf and VASurfaceID.
//
// The function takes the following parameters:
//
//   - display: VaDisplay.
//
// The function returns the following values:
//
//   - vaDmabufAllocator: new allocated Allocator.
func NewVaDmabufAllocator(display *VaDisplay) *VaDmabufAllocator {
	var _arg1 *C.GstVaDisplay // out
	var _cret *C.GstAllocator // in

	_arg1 = (*C.GstVaDisplay)(unsafe.Pointer(coreglib.InternObject(display).Native()))

	_cret = C.gst_va_dmabuf_allocator_new(_arg1)
	runtime.KeepAlive(display)

	var _vaDmabufAllocator *VaDmabufAllocator // out

	_vaDmabufAllocator = wrapVaDmabufAllocator(coreglib.Take(unsafe.Pointer(_cret)))

	return _vaDmabufAllocator
}

// VaDmabufAllocatorFlush removes all the memories in allocator's pool.
//
// The function takes the following parameters:
//
//   - allocator: Allocator.
func VaDmabufAllocatorFlush(allocator gst.Allocatorrer) {
	var _arg1 *C.GstAllocator // out

	_arg1 = (*C.GstAllocator)(unsafe.Pointer(coreglib.InternObject(allocator).Native()))

	C.gst_va_dmabuf_allocator_flush(_arg1)
	runtime.KeepAlive(allocator)
}

// VaDmabufAllocatorGetFormat gets current internal configuration of allocator.
//
// The function takes the following parameters:
//
//   - allocator: Allocator.
//
// The function returns the following values:
//
//   - info (optional): VideoInfoDmaDrm.
//   - usageHint (optional): VA usage hint.
//   - ok: TRUE if allocator is already configured; FALSE otherwise.
func VaDmabufAllocatorGetFormat(allocator gst.Allocatorrer) (*gstvideo.VideoInfoDmaDRM, uint, bool) {
	var _arg1 *C.GstAllocator      // out
	var _arg2 C.GstVideoInfoDmaDrm // in
	var _arg3 C.guint              // in
	var _cret C.gboolean           // in

	_arg1 = (*C.GstAllocator)(unsafe.Pointer(coreglib.InternObject(allocator).Native()))

	_cret = C.gst_va_dmabuf_allocator_get_format(_arg1, &_arg2, &_arg3)
	runtime.KeepAlive(allocator)

	var _info *gstvideo.VideoInfoDmaDRM // out
	var _usageHint uint                 // out
	var _ok bool                        // out

	_info = (*gstvideo.VideoInfoDmaDRM)(gextras.NewStructNative(unsafe.Pointer((&_arg2))))
	_usageHint = uint(_arg3)
	if _cret != 0 {
		_ok = true
	}

	return _info, _usageHint, _ok
}

// VaDmabufAllocatorPrepareBuffer: this method will populate buffer with pooled
// VASurfaceID/DMABuf memories. It doesn't allocate new VASurfacesID.
//
// The function takes the following parameters:
//
//   - allocator: Allocator.
//   - buffer: empty Buffer.
//
// The function returns the following values:
//
//   - ok: TRUE if buffer was populated correctly; FALSE otherwise.
func VaDmabufAllocatorPrepareBuffer(allocator gst.Allocatorrer, buffer *gst.Buffer) bool {
	var _arg1 *C.GstAllocator // out
	var _arg2 *C.GstBuffer    // out
	var _cret C.gboolean      // in

	_arg1 = (*C.GstAllocator)(unsafe.Pointer(coreglib.InternObject(allocator).Native()))
	_arg2 = (*C.GstBuffer)(gextras.StructNative(unsafe.Pointer(buffer)))

	_cret = C.gst_va_dmabuf_allocator_prepare_buffer(_arg1, _arg2)
	runtime.KeepAlive(allocator)
	runtime.KeepAlive(buffer)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// VaDmabufAllocatorSetFormat sets the configuration defined by info and
// usage_hint for allocator, and it tries the configuration, if allocator has
// not allocated memories yet.
//
// If allocator has memory allocated already, and frame size, format and
// modifier in info are the same as currently configured in allocator, the rest
// of info parameters are updated internally.
//
// The function takes the following parameters:
//
//   - allocator: Allocator.
//   - usageHint: VA usage hint.
//
// The function returns the following values:
//
//   - info: VideoInfoDmaDrm.
//   - ok: TRUE if the configuration is valid or updated; FALSE if configuration
//     is not valid or not updated.
func VaDmabufAllocatorSetFormat(allocator gst.Allocatorrer, usageHint uint) (*gstvideo.VideoInfoDmaDRM, bool) {
	var _arg1 *C.GstAllocator      // out
	var _arg2 C.GstVideoInfoDmaDrm // in
	var _arg3 C.guint              // out
	var _cret C.gboolean           // in

	_arg1 = (*C.GstAllocator)(unsafe.Pointer(coreglib.InternObject(allocator).Native()))
	_arg3 = C.guint(usageHint)

	_cret = C.gst_va_dmabuf_allocator_set_format(_arg1, &_arg2, _arg3)
	runtime.KeepAlive(allocator)
	runtime.KeepAlive(usageHint)

	var _info *gstvideo.VideoInfoDmaDRM // out
	var _ok bool                        // out

	_info = (*gstvideo.VideoInfoDmaDRM)(gextras.NewStructNative(unsafe.Pointer((&_arg2))))
	if _cret != 0 {
		_ok = true
	}

	return _info, _ok
}

// VaDmabufAllocatorSetupBuffer: this function creates a new VASurfaceID and
// exposes its DMABufs, later it populates the buffer with those DMABufs.
//
// The function takes the following parameters:
//
//   - allocator: Allocator.
//   - buffer: empty Buffer.
//
// The function returns the following values:
//
//   - ok: TRUE if buffer is populated correctly; FALSE otherwise.
func VaDmabufAllocatorSetupBuffer(allocator gst.Allocatorrer, buffer *gst.Buffer) bool {
	var _arg1 *C.GstAllocator // out
	var _arg2 *C.GstBuffer    // out
	var _cret C.gboolean      // in

	_arg1 = (*C.GstAllocator)(unsafe.Pointer(coreglib.InternObject(allocator).Native()))
	_arg2 = (*C.GstBuffer)(gextras.StructNative(unsafe.Pointer(buffer)))

	_cret = C.gst_va_dmabuf_allocator_setup_buffer(_arg1, _arg2)
	runtime.KeepAlive(allocator)
	runtime.KeepAlive(buffer)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// VaPool is a buffer pool for VA allocators.
type VaPool struct {
	_ [0]func() // equal guard
	gst.BufferPool
}

var (
	_ gst.GstObjector = (*VaPool)(nil)
)

func wrapVaPool(obj *coreglib.Object) *VaPool {
	return &VaPool{
		BufferPool: gst.BufferPool{
			GstObject: gst.GstObject{
				InitiallyUnowned: coreglib.InitiallyUnowned{
					Object: obj,
				},
			},
		},
	}
}

func marshalVaPool(p uintptr) (interface{}, error) {
	return wrapVaPool(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// The function returns the following values:
//
//   - vaPool: new BufferPool for VA allocators.
func NewVaPool() *VaPool {
	var _cret *C.GstBufferPool // in

	_cret = C.gst_va_pool_new()

	var _vaPool *VaPool // out

	_vaPool = wrapVaPool(coreglib.Take(unsafe.Pointer(_cret)))

	return _vaPool
}

// The function takes the following parameters:
//
//   - caps of the buffers handled by the new pool.
//   - minBuffers: minimum number of frames to create.
//   - maxBuffers: maximum number of frames to create.
//   - usageHint: VA usage hint.
//   - useDerived for derived mapping (only used when VA allocator).
//   - allocator: VA allocator to use.
//   - allocParams to use.
//
// The function returns the following values:
//
//   - vaPool: new BufferPool that handles VASurfacesID-backed buffers. If the
//     pool cannot be configured correctly, NULL is returned.
func NewVaPoolWithConfig(caps *gst.Caps, minBuffers, maxBuffers, usageHint uint, useDerived VaFeature, allocator gst.Allocatorrer, allocParams *gst.AllocationParams) *VaPool {
	var _arg1 *C.GstCaps             // out
	var _arg2 C.guint                // out
	var _arg3 C.guint                // out
	var _arg4 C.guint                // out
	var _arg5 C.GstVaFeature         // out
	var _arg6 *C.GstAllocator        // out
	var _arg7 *C.GstAllocationParams // out
	var _cret *C.GstBufferPool       // in

	_arg1 = (*C.GstCaps)(gextras.StructNative(unsafe.Pointer(caps)))
	_arg2 = C.guint(minBuffers)
	_arg3 = C.guint(maxBuffers)
	_arg4 = C.guint(usageHint)
	_arg5 = C.GstVaFeature(useDerived)
	_arg6 = (*C.GstAllocator)(unsafe.Pointer(coreglib.InternObject(allocator).Native()))
	_arg7 = (*C.GstAllocationParams)(gextras.StructNative(unsafe.Pointer(allocParams)))

	_cret = C.gst_va_pool_new_with_config(_arg1, _arg2, _arg3, _arg4, _arg5, _arg6, _arg7)
	runtime.KeepAlive(caps)
	runtime.KeepAlive(minBuffers)
	runtime.KeepAlive(maxBuffers)
	runtime.KeepAlive(usageHint)
	runtime.KeepAlive(useDerived)
	runtime.KeepAlive(allocator)
	runtime.KeepAlive(allocParams)

	var _vaPool *VaPool // out

	_vaPool = wrapVaPool(coreglib.Take(unsafe.Pointer(_cret)))

	return _vaPool
}

// VaPoolGetBufferSize: helper function to retrieve the VA surface size provided
// by pool.
//
// The function takes the following parameters:
//
//   - pool: BufferPool.
//
// The function returns the following values:
//
//   - size (optional): declared surface size.
//   - ok: whether the surface size was retrieved.
func VaPoolGetBufferSize(pool *gst.BufferPool) (uint, bool) {
	var _arg1 *C.GstBufferPool // out
	var _arg2 C.guint          // in
	var _cret C.gboolean       // in

	_arg1 = (*C.GstBufferPool)(unsafe.Pointer(coreglib.InternObject(pool).Native()))

	_cret = C.gst_va_pool_get_buffer_size(_arg1, &_arg2)
	runtime.KeepAlive(pool)

	var _size uint // out
	var _ok bool   // out

	_size = uint(_arg2)
	if _cret != 0 {
		_ok = true
	}

	return _size, _ok
}

// VaPoolRequiresVideoMeta: retuns: TRUE if pool always add VideoMeta to its
// buffers. Otherwise, FALSE.
//
// The function takes the following parameters:
//
//   - pool: BufferPool.
func VaPoolRequiresVideoMeta(pool *gst.BufferPool) bool {
	var _arg1 *C.GstBufferPool // out
	var _cret C.gboolean       // in

	_arg1 = (*C.GstBufferPool)(unsafe.Pointer(coreglib.InternObject(pool).Native()))

	_cret = C.gst_va_pool_requires_video_meta(_arg1)
	runtime.KeepAlive(pool)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// VaDisplayClass: common VA display object class structure.
//
// An instance of this type is always passed by reference.
type VaDisplayClass struct {
	*vaDisplayClass
}

// vaDisplayClass is the struct that's finalized.
type vaDisplayClass struct {
	native *C.GstVaDisplayClass
}

// ParentClass: parent ObjectClass.
func (v *VaDisplayClass) ParentClass() *gst.ObjectClass {
	valptr := &v.native.parent_class
	var _v *gst.ObjectClass // out
	_v = (*gst.ObjectClass)(gextras.NewStructNative(unsafe.Pointer(valptr)))
	return _v
}
