// Code generated by girgen for Gtk-4. DO NOT EDIT.

package gtk

import (
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/userdata"
	"github.com/diamondburned/gotk4/pkg/gdk/v4"
	"github.com/diamondburned/gotk4/pkg/pango"
)

// #include <gtk/gtk.h>
import "C"

//export _gotk4_gtk4_AssistantPageFunc
func _gotk4_gtk4_AssistantPageFunc(carg1 C.int, carg2 C.gpointer) (cret C.int) {
	var fn AssistantPageFunc
	{
		v := userdata.Load(unsafe.Pointer(carg2))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(AssistantPageFunc)
	}

	var currentPage int // in, none, casted, casted C.gint
	var goret       int // return, none, casted, casted C.gint

	currentPage = int(carg1)

	goret = fn(currentPage)

	cret = C.int(goret)

	return cret
}

//export _gotk4_gtk4_ExpressionNotify
func _gotk4_gtk4_ExpressionNotify(carg1 C.gpointer) {
	var fn ExpressionNotify
	{
		v := userdata.Load(unsafe.Pointer(carg1))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(ExpressionNotify)
	}

	fn()
}

//export _gotk4_gtk4_FontFilterFunc
func _gotk4_gtk4_FontFilterFunc(carg1 *C.PangoFontFamily, carg2 *C.PangoFontFace, carg3 C.gpointer) (cret C.gboolean) {
	var fn FontFilterFunc
	{
		v := userdata.Load(unsafe.Pointer(carg3))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(FontFilterFunc)
	}

	var family pango.FontFamily // in, none, converted
	var face   pango.FontFace   // in, none, converted
	var goret  bool             // return

	family = pango.UnsafeFontFamilyFromGlibNone(unsafe.Pointer(carg1))
	face = pango.UnsafeFontFaceFromGlibNone(unsafe.Pointer(carg2))

	goret = fn(family, face)

	if goret {
		cret = C.TRUE
	}

	return cret
}

//export _gotk4_gtk4_PageSetupDoneFunc
func _gotk4_gtk4_PageSetupDoneFunc(carg1 *C.GtkPageSetup, carg2 C.gpointer) {
	var fn PageSetupDoneFunc
	{
		v := userdata.Load(unsafe.Pointer(carg2))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(PageSetupDoneFunc)
	}

	var pageSetup PageSetup // in, none, converted

	pageSetup = UnsafePageSetupFromGlibNone(unsafe.Pointer(carg1))

	fn(pageSetup)
}

//export _gotk4_gtk4_TextBufferCommitNotify
func _gotk4_gtk4_TextBufferCommitNotify(carg1 *C.GtkTextBuffer, carg2 C.GtkTextBufferNotifyFlags, carg3 C.guint, carg4 C.guint, carg5 C.gpointer) {
	var fn TextBufferCommitNotify
	{
		v := userdata.Load(unsafe.Pointer(carg5))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(TextBufferCommitNotify)
	}

	var buffer   TextBuffer            // in, none, converted
	var flags    TextBufferNotifyFlags // in, none, casted
	var position uint                  // in, none, casted
	var length   uint                  // in, none, casted

	buffer = UnsafeTextBufferFromGlibNone(unsafe.Pointer(carg1))
	flags = TextBufferNotifyFlags(carg2)
	position = uint(carg3)
	length = uint(carg4)

	fn(buffer, flags, position, length)
}

//export _gotk4_gtk4_TextCharPredicate
func _gotk4_gtk4_TextCharPredicate(carg1 C.gunichar, carg2 C.gpointer) (cret C.gboolean) {
	var fn TextCharPredicate
	{
		v := userdata.Load(unsafe.Pointer(carg2))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(TextCharPredicate)
	}

	var ch    uint32 // in, none, casted
	var goret bool   // return

	ch = uint32(carg1)

	goret = fn(ch)

	if goret {
		cret = C.TRUE
	}

	return cret
}

//export _gotk4_gtk4_TextTagTableForEach
func _gotk4_gtk4_TextTagTableForEach(carg1 *C.GtkTextTag, carg2 C.gpointer) {
	var fn TextTagTableForEach
	{
		v := userdata.Load(unsafe.Pointer(carg2))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(TextTagTableForEach)
	}

	var tag TextTag // in, none, converted

	tag = UnsafeTextTagFromGlibNone(unsafe.Pointer(carg1))

	fn(tag)
}

//export _gotk4_gtk4_TickCallback
func _gotk4_gtk4_TickCallback(carg1 *C.GtkWidget, carg2 *C.GdkFrameClock, carg3 C.gpointer) (cret C.gboolean) {
	var fn TickCallback
	{
		v := userdata.Load(unsafe.Pointer(carg3))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(TickCallback)
	}

	var widget     Widget         // in, none, converted
	var frameClock gdk.FrameClock // in, none, converted
	var goret      bool           // return

	widget = UnsafeWidgetFromGlibNone(unsafe.Pointer(carg1))
	frameClock = gdk.UnsafeFrameClockFromGlibNone(unsafe.Pointer(carg2))

	goret = fn(widget, frameClock)

	if goret {
		cret = C.TRUE
	}

	return cret
}

//export _gotk4_gtk4_FlowBoxFilterFunc
func _gotk4_gtk4_FlowBoxFilterFunc(carg1 *C.GtkFlowBoxChild, carg2 C.gpointer) (cret C.gboolean) {
	var fn FlowBoxFilterFunc
	{
		v := userdata.Load(unsafe.Pointer(carg2))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(FlowBoxFilterFunc)
	}

	var child FlowBoxChild // in, none, converted
	var goret bool         // return

	child = UnsafeFlowBoxChildFromGlibNone(unsafe.Pointer(carg1))

	goret = fn(child)

	if goret {
		cret = C.TRUE
	}

	return cret
}

//export _gotk4_gtk4_FlowBoxForEachFunc
func _gotk4_gtk4_FlowBoxForEachFunc(carg1 *C.GtkFlowBox, carg2 *C.GtkFlowBoxChild, carg3 C.gpointer) {
	var fn FlowBoxForEachFunc
	{
		v := userdata.Load(unsafe.Pointer(carg3))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(FlowBoxForEachFunc)
	}

	var box   FlowBox      // in, none, converted
	var child FlowBoxChild // in, none, converted

	box = UnsafeFlowBoxFromGlibNone(unsafe.Pointer(carg1))
	child = UnsafeFlowBoxChildFromGlibNone(unsafe.Pointer(carg2))

	fn(box, child)
}

//export _gotk4_gtk4_FlowBoxSortFunc
func _gotk4_gtk4_FlowBoxSortFunc(carg1 *C.GtkFlowBoxChild, carg2 *C.GtkFlowBoxChild, carg3 C.gpointer) (cret C.int) {
	var fn FlowBoxSortFunc
	{
		v := userdata.Load(unsafe.Pointer(carg3))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(FlowBoxSortFunc)
	}

	var child1 FlowBoxChild // in, none, converted
	var child2 FlowBoxChild // in, none, converted
	var goret  int          // return, none, casted, casted C.gint

	child1 = UnsafeFlowBoxChildFromGlibNone(unsafe.Pointer(carg1))
	child2 = UnsafeFlowBoxChildFromGlibNone(unsafe.Pointer(carg2))

	goret = fn(child1, child2)

	cret = C.int(goret)

	return cret
}

//export _gotk4_gtk4_ListBoxFilterFunc
func _gotk4_gtk4_ListBoxFilterFunc(carg1 *C.GtkListBoxRow, carg2 C.gpointer) (cret C.gboolean) {
	var fn ListBoxFilterFunc
	{
		v := userdata.Load(unsafe.Pointer(carg2))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(ListBoxFilterFunc)
	}

	var row   ListBoxRow // in, none, converted
	var goret bool       // return

	row = UnsafeListBoxRowFromGlibNone(unsafe.Pointer(carg1))

	goret = fn(row)

	if goret {
		cret = C.TRUE
	}

	return cret
}

//export _gotk4_gtk4_ListBoxForEachFunc
func _gotk4_gtk4_ListBoxForEachFunc(carg1 *C.GtkListBox, carg2 *C.GtkListBoxRow, carg3 C.gpointer) {
	var fn ListBoxForEachFunc
	{
		v := userdata.Load(unsafe.Pointer(carg3))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(ListBoxForEachFunc)
	}

	var box ListBox    // in, none, converted
	var row ListBoxRow // in, none, converted

	box = UnsafeListBoxFromGlibNone(unsafe.Pointer(carg1))
	row = UnsafeListBoxRowFromGlibNone(unsafe.Pointer(carg2))

	fn(box, row)
}

//export _gotk4_gtk4_ListBoxSortFunc
func _gotk4_gtk4_ListBoxSortFunc(carg1 *C.GtkListBoxRow, carg2 *C.GtkListBoxRow, carg3 C.gpointer) (cret C.int) {
	var fn ListBoxSortFunc
	{
		v := userdata.Load(unsafe.Pointer(carg3))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(ListBoxSortFunc)
	}

	var row1  ListBoxRow // in, none, converted
	var row2  ListBoxRow // in, none, converted
	var goret int        // return, none, casted, casted C.gint

	row1 = UnsafeListBoxRowFromGlibNone(unsafe.Pointer(carg1))
	row2 = UnsafeListBoxRowFromGlibNone(unsafe.Pointer(carg2))

	goret = fn(row1, row2)

	cret = C.int(goret)

	return cret
}

//export _gotk4_gtk4_ListBoxUpdateHeaderFunc
func _gotk4_gtk4_ListBoxUpdateHeaderFunc(carg1 *C.GtkListBoxRow, carg2 *C.GtkListBoxRow, carg3 C.gpointer) {
	var fn ListBoxUpdateHeaderFunc
	{
		v := userdata.Load(unsafe.Pointer(carg3))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(ListBoxUpdateHeaderFunc)
	}

	var row    ListBoxRow // in, none, converted
	var before ListBoxRow // in, none, converted, nullable

	row = UnsafeListBoxRowFromGlibNone(unsafe.Pointer(carg1))
	if carg2 != nil {
		before = UnsafeListBoxRowFromGlibNone(unsafe.Pointer(carg2))
	}

	fn(row, before)
}

//export _gotk4_gtk4_MenuButtonCreatePopupFunc
func _gotk4_gtk4_MenuButtonCreatePopupFunc(carg1 *C.GtkMenuButton, carg2 C.gpointer) {
	var fn MenuButtonCreatePopupFunc
	{
		v := userdata.Load(unsafe.Pointer(carg2))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(MenuButtonCreatePopupFunc)
	}

	var menuButton MenuButton // in, none, converted

	menuButton = UnsafeMenuButtonFromGlibNone(unsafe.Pointer(carg1))

	fn(menuButton)
}

//export _gotk4_gtk4_ScaleFormatValueFunc
func _gotk4_gtk4_ScaleFormatValueFunc(carg1 *C.GtkScale, carg2 C.double, carg3 C.gpointer) (cret *C.char) {
	var fn ScaleFormatValueFunc
	{
		v := userdata.Load(unsafe.Pointer(carg3))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(ScaleFormatValueFunc)
	}

	var scale Scale   // in, none, converted
	var value float64 // in, none, casted, casted C.gdouble
	var goret string  // return, full, string, casted *C.gchar

	scale = UnsafeScaleFromGlibNone(unsafe.Pointer(carg1))
	value = float64(carg2)

	goret = fn(scale, value)

	cret = (*C.char)(unsafe.Pointer(C.CString(goret)))

	return cret
}

