// Code generated by girgen for PangoCairo-1. DO NOT EDIT.

package pangocairo

import (
	"runtime"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/gobject/v2"
	"github.com/diamondburned/gotk4/pkg/pango"
)

// #cgo pkg-config: pangocairo
// #cgo CFLAGS: -Wno-deprecated-declarations
// #include <pango/pangocairo.h>
import "C"

// GType values.
var (
	TypeFont    = gobject.Type(C.pango_cairo_font_get_type())
	TypeFontMap = gobject.Type(C.pango_cairo_font_map_get_type())
)

func init() {
	gobject.RegisterGValueMarshalers([]gobject.TypeMarshaler{
		gobject.TypeMarshaler{T: TypeFont, F: marshalFontInstance},
		gobject.TypeMarshaler{T: TypeFontMap, F: marshalFontMapInstance},
	})
}

// ContextGetResolution wraps pango_cairo_context_get_resolution
// 
// The function takes the following parameters:
// 
// 	- _context pango.Context: a `PangoContext`, from a pangocairo font map 
// 
// The function returns the following values:
// 
// 	- goret float64 
//
// Gets the resolution for the context.
// 
// See [func@PangoCairo.context_set_resolution]
func ContextGetResolution(_context pango.Context) float64 {
	var carg1 *C.PangoContext // in, none, converted
	var cret  C.double        // return, none, casted, casted C.gdouble

	carg1 = (*C.PangoContext)(pango.UnsafeContextToGlibNone(_context))

	cret = C.pango_cairo_context_get_resolution(carg1)
	runtime.KeepAlive(_context)

	var goret float64

	goret = float64(cret)

	return goret
}

// ContextSetResolution wraps pango_cairo_context_set_resolution
// 
// The function takes the following parameters:
// 
// 	- _context pango.Context: a `PangoContext`, from a pangocairo font map 
// 	- dpi float64: the resolution in "dots per inch". (Physical inches aren't actually
//   involved; the terminology is conventional.) A 0 or negative value
//   means to use the resolution from the font map. 
//
// Sets the resolution for the context.
// 
// This is a scale factor between points specified in a `PangoFontDescription`
// and Cairo units. The default value is 96, meaning that a 10 point font will
// be 13 units high. (10 * 96. / 72. = 13.3).
func ContextSetResolution(_context pango.Context, dpi float64) {
	var carg1 *C.PangoContext // in, none, converted
	var carg2 C.double        // in, none, casted, casted C.gdouble

	carg1 = (*C.PangoContext)(pango.UnsafeContextToGlibNone(_context))
	carg2 = C.double(dpi)

	C.pango_cairo_context_set_resolution(carg1, carg2)
	runtime.KeepAlive(_context)
	runtime.KeepAlive(dpi)
}

// FontInstance is the instance type used by all types implementing PangoCairoFont. It is used internally by the bindings. Users should use the interface [Font] instead.
type FontInstance struct {
	_ [0]func() // equal guard
	Instance gobject.ObjectInstance
}

var _ Font = (*FontInstance)(nil)

// Font wraps PangoCairoFont
//
// `PangoCairoFont` is an interface exported by fonts for
// use with Cairo.
// 
// The actual type of the font will depend on the particular
// font technology Cairo was compiled to use.
type Font interface {
	upcastToPangoCairoFont() *FontInstance
}

var _ Font = (*FontInstance)(nil)

func unsafeWrapFont(base *gobject.ObjectInstance) *FontInstance {
	return &FontInstance{
		Instance: *base,
	}
}

func marshalFontInstance(p unsafe.Pointer) (any, error) {
	return unsafeWrapFont(gobject.ValueFromNative(p).Object()), nil
}

func (f *FontInstance) upcastToPangoCairoFont() *FontInstance {
	return f
}

// UnsafeFontFromGlibNone is used to convert raw PangoCairoFont pointers to go while taking a reference and attaching a finalizer. This is used by the bindings internally.
func UnsafeFontFromGlibNone(c unsafe.Pointer) Font {
	return gobject.UnsafeObjectFromGlibNone(c).(Font)
}

// UnsafeFontFromGlibFull is used to convert raw PangoCairoFont pointers to go while attaching a finalizer. This is used by the bindings internally.
func UnsafeFontFromGlibFull(c unsafe.Pointer) Font {
	return gobject.UnsafeObjectFromGlibFull(c).(Font)
}

// UnsafeFontToGlibNone is used to convert the instance to it's C value PangoCairoFont. This is used by the bindings internally.
func UnsafeFontToGlibNone(c Font) unsafe.Pointer {
	i := c.upcastToPangoCairoFont()
	return gobject.UnsafeObjectToGlibNone(&i.Instance)
}

// UnsafeFontToGlibFull is used to convert the instance to it's C value PangoCairoFont, while removeing the finalizer. This is used by the bindings internally.
func UnsafeFontToGlibFull(c Font) unsafe.Pointer {
	i := c.upcastToPangoCairoFont()
	return gobject.UnsafeObjectToGlibFull(&i.Instance)
}

// FontMapInstance is the instance type used by all types implementing PangoCairoFontMap. It is used internally by the bindings. Users should use the interface [FontMap] instead.
type FontMapInstance struct {
	_ [0]func() // equal guard
	Instance gobject.ObjectInstance
}

var _ FontMap = (*FontMapInstance)(nil)

// FontMap wraps PangoCairoFontMap
//
// `PangoCairoFontMap` is an interface exported by font maps for
// use with Cairo.
// 
// The actual type of the font map will depend on the particular
// font technology Cairo was compiled to use.
type FontMap interface {
	upcastToPangoCairoFontMap() *FontMapInstance

	// GetResolution wraps pango_cairo_font_map_get_resolution
	// The function returns the following values:
	// 
	// 	- goret float64 
	//
	// Gets the resolution for the fontmap.
	// 
	// See [method@PangoCairo.FontMap.set_resolution].
	GetResolution() float64
	// SetDefault wraps pango_cairo_font_map_set_default
	//
	// Sets a default `PangoCairoFontMap` to use with Cairo.
	// 
	// This can be used to change the Cairo font backend that the
	// default fontmap uses for example. The old default font map
	// is unreffed and the new font map referenced.
	// 
	// Note that since Pango 1.32.6, the default fontmap is per-thread.
	// This function only changes the default fontmap for
	// the current thread. Default fontmaps of existing threads
	// are not changed. Default fontmaps of any new threads will
	// still be created using [func@PangoCairo.FontMap.new].
	// 
	// A value of %NULL for @fontmap will cause the current default
	// font map to be released and a new default font map to be created
	// on demand, using [func@PangoCairo.FontMap.new].
	SetDefault()
	// SetResolution wraps pango_cairo_font_map_set_resolution
	// 
	// The function takes the following parameters:
	// 
	// 	- dpi float64: the resolution in "dots per inch". (Physical inches aren't actually
	//   involved; the terminology is conventional.) 
	//
	// Sets the resolution for the fontmap.
	// 
	// This is a scale factor between
	// points specified in a `PangoFontDescription` and Cairo units. The
	// default value is 96, meaning that a 10 point font will be 13
	// units high. (10 * 96. / 72. = 13.3).
	SetResolution(float64)
}

var _ FontMap = (*FontMapInstance)(nil)

func unsafeWrapFontMap(base *gobject.ObjectInstance) *FontMapInstance {
	return &FontMapInstance{
		Instance: *base,
	}
}

func marshalFontMapInstance(p unsafe.Pointer) (any, error) {
	return unsafeWrapFontMap(gobject.ValueFromNative(p).Object()), nil
}

func (f *FontMapInstance) upcastToPangoCairoFontMap() *FontMapInstance {
	return f
}

// UnsafeFontMapFromGlibNone is used to convert raw PangoCairoFontMap pointers to go while taking a reference and attaching a finalizer. This is used by the bindings internally.
func UnsafeFontMapFromGlibNone(c unsafe.Pointer) FontMap {
	return gobject.UnsafeObjectFromGlibNone(c).(FontMap)
}

// UnsafeFontMapFromGlibFull is used to convert raw PangoCairoFontMap pointers to go while attaching a finalizer. This is used by the bindings internally.
func UnsafeFontMapFromGlibFull(c unsafe.Pointer) FontMap {
	return gobject.UnsafeObjectFromGlibFull(c).(FontMap)
}

// UnsafeFontMapToGlibNone is used to convert the instance to it's C value PangoCairoFontMap. This is used by the bindings internally.
func UnsafeFontMapToGlibNone(c FontMap) unsafe.Pointer {
	i := c.upcastToPangoCairoFontMap()
	return gobject.UnsafeObjectToGlibNone(&i.Instance)
}

// UnsafeFontMapToGlibFull is used to convert the instance to it's C value PangoCairoFontMap, while removeing the finalizer. This is used by the bindings internally.
func UnsafeFontMapToGlibFull(c FontMap) unsafe.Pointer {
	i := c.upcastToPangoCairoFontMap()
	return gobject.UnsafeObjectToGlibFull(&i.Instance)
}

// FontMapGetDefault wraps pango_cairo_font_map_get_default
// The function returns the following values:
// 
// 	- goret pango.FontMap 
//
// Gets a default `PangoCairoFontMap` to use with Cairo.
// 
// Note that the type of the returned object will depend on the
// particular font backend Cairo was compiled to use; you generally
// should only use the `PangoFontMap` and `PangoCairoFontMap`
// interfaces on the returned object.
// 
// The default Cairo fontmap can be changed by using
// [method@PangoCairo.FontMap.set_default]. This can be used to
// change the Cairo font backend that the default fontmap uses
// for example.
// 
// Note that since Pango 1.32.6, the default fontmap is per-thread.
// Each thread gets its own default fontmap. In this way, PangoCairo
// can be used safely from multiple threads.
func FontMapGetDefault() pango.FontMap {
	var cret *C.PangoFontMap // return, none, converted

	cret = C.pango_cairo_font_map_get_default()

	var goret pango.FontMap

	goret = pango.UnsafeFontMapFromGlibNone(unsafe.Pointer(cret))

	return goret
}

// NewFontMap wraps pango_cairo_font_map_new
// The function returns the following values:
// 
// 	- goret pango.FontMap 
//
// Creates a new `PangoCairoFontMap` object.
// 
// A fontmap is used to cache information about available fonts,
// and holds certain global parameters such as the resolution.
// In most cases, you can use `func@PangoCairo.font_map_get_default]
// instead.
// 
// Note that the type of the returned object will depend
// on the particular font backend Cairo was compiled to use;
// You generally should only use the `PangoFontMap` and
// `PangoCairoFontMap` interfaces on the returned object.
// 
// You can override the type of backend returned by using an
// environment variable %PANGOCAIRO_BACKEND. Supported types,
// based on your build, are fc (fontconfig), win32, and coretext.
// If requested type is not available, NULL is returned. Ie.
// this is only useful for testing, when at least two backends
// are compiled in.
func NewFontMap() pango.FontMap {
	var cret *C.PangoFontMap // return, full, converted

	cret = C.pango_cairo_font_map_new()

	var goret pango.FontMap

	goret = pango.UnsafeFontMapFromGlibFull(unsafe.Pointer(cret))

	return goret
}

// GetResolution wraps pango_cairo_font_map_get_resolution
// The function returns the following values:
// 
// 	- goret float64 
//
// Gets the resolution for the fontmap.
// 
// See [method@PangoCairo.FontMap.set_resolution].
func (fontmap *FontMapInstance) GetResolution() float64 {
	var carg0 *C.PangoCairoFontMap // in, none, converted
	var cret  C.double             // return, none, casted, casted C.gdouble

	carg0 = (*C.PangoCairoFontMap)(UnsafeFontMapToGlibNone(fontmap))

	cret = C.pango_cairo_font_map_get_resolution(carg0)
	runtime.KeepAlive(fontmap)

	var goret float64

	goret = float64(cret)

	return goret
}

// SetDefault wraps pango_cairo_font_map_set_default
//
// Sets a default `PangoCairoFontMap` to use with Cairo.
// 
// This can be used to change the Cairo font backend that the
// default fontmap uses for example. The old default font map
// is unreffed and the new font map referenced.
// 
// Note that since Pango 1.32.6, the default fontmap is per-thread.
// This function only changes the default fontmap for
// the current thread. Default fontmaps of existing threads
// are not changed. Default fontmaps of any new threads will
// still be created using [func@PangoCairo.FontMap.new].
// 
// A value of %NULL for @fontmap will cause the current default
// font map to be released and a new default font map to be created
// on demand, using [func@PangoCairo.FontMap.new].
func (fontmap *FontMapInstance) SetDefault() {
	var carg0 *C.PangoCairoFontMap // in, none, converted

	carg0 = (*C.PangoCairoFontMap)(UnsafeFontMapToGlibNone(fontmap))

	C.pango_cairo_font_map_set_default(carg0)
	runtime.KeepAlive(fontmap)
}

// SetResolution wraps pango_cairo_font_map_set_resolution
// 
// The function takes the following parameters:
// 
// 	- dpi float64: the resolution in "dots per inch". (Physical inches aren't actually
//   involved; the terminology is conventional.) 
//
// Sets the resolution for the fontmap.
// 
// This is a scale factor between
// points specified in a `PangoFontDescription` and Cairo units. The
// default value is 96, meaning that a 10 point font will be 13
// units high. (10 * 96. / 72. = 13.3).
func (fontmap *FontMapInstance) SetResolution(dpi float64) {
	var carg0 *C.PangoCairoFontMap // in, none, converted
	var carg1 C.double             // in, none, casted, casted C.gdouble

	carg0 = (*C.PangoCairoFontMap)(UnsafeFontMapToGlibNone(fontmap))
	carg1 = C.double(dpi)

	C.pango_cairo_font_map_set_resolution(carg0, carg1)
	runtime.KeepAlive(fontmap)
	runtime.KeepAlive(dpi)
}

