// Code generated by girgen. DO NOT EDIT.

package gstcuda

import (
	"fmt"
	"runtime"
	_ "runtime/cgo"
	"strings"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gextras"
	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
	"github.com/diamondburned/gotk4/pkg/cudagst"
	"github.com/diamondburned/gotk4/pkg/gst"
	"github.com/diamondburned/gotk4/pkg/gstvideo"
)

// #cgo pkg-config: gstreamer-cuda-1.0 gstreamer-analytics-1.0
// #cgo CFLAGS: -Wno-deprecated-declarations
// #include <stdlib.h>
// #include <glib-object.h>
// extern gboolean _gotk4_gstcuda1_CudaAllocatorClass_set_active(GstCudaAllocator*, gboolean);
// gboolean _gotk4_gstcuda1_CudaAllocator_virtual_set_active(void* fnptr, GstCudaAllocator* arg0, gboolean arg1) {
//   return ((gboolean (*)(GstCudaAllocator*, gboolean))(fnptr))(arg0, arg1);
// };
import "C"

// GType values.
var (
	GTypeCudaMemoryAllocMethod = coreglib.Type(C.gst_cuda_memory_alloc_method_get_type())
	GTypeCudaAllocator         = coreglib.Type(C.gst_cuda_allocator_get_type())
	GTypeCudaBufferPool        = coreglib.Type(C.gst_cuda_buffer_pool_get_type())
	GTypeCudaContext           = coreglib.Type(C.gst_cuda_context_get_type())
	GTypeCudaPoolAllocator     = coreglib.Type(C.gst_cuda_pool_allocator_get_type())
	GTypeCudaStream            = coreglib.Type(C.gst_cuda_stream_get_type())
)

func init() {
	coreglib.RegisterGValueMarshalers([]coreglib.TypeMarshaler{
		coreglib.TypeMarshaler{T: GTypeCudaMemoryAllocMethod, F: marshalCudaMemoryAllocMethod},
		coreglib.TypeMarshaler{T: GTypeCudaAllocator, F: marshalCudaAllocator},
		coreglib.TypeMarshaler{T: GTypeCudaBufferPool, F: marshalCudaBufferPool},
		coreglib.TypeMarshaler{T: GTypeCudaContext, F: marshalCudaContext},
		coreglib.TypeMarshaler{T: GTypeCudaPoolAllocator, F: marshalCudaPoolAllocator},
		coreglib.TypeMarshaler{T: GTypeCudaStream, F: marshalCudaStream},
	})
}

// CAPS_FEATURE_MEMORY_CUDA_MEMORY: name of the caps feature for indicating the
// use of CudaMemory.
const CAPS_FEATURE_MEMORY_CUDA_MEMORY = "memory:CUDAMemory"
const CUDA_CONTEXT_TYPE = "gst.cuda.context"

// CUDA_MEMORY_TYPE_NAME: name of cuda memory type.
const CUDA_MEMORY_TYPE_NAME = "gst.cuda.memory"

// MAP_CUDA: flag indicating that we should map the CUDA device memory instead
// of to system memory.
//
// Combining T_MAP_CUDA with T_MAP_WRITE has the same semantics as though you
// are writing to CUDA device/host memory. Conversely, combining T_MAP_CUDA
// with T_MAP_READ has the same semantics as though you are reading from CUDA
// device/host memory.
const MAP_CUDA = 131072

type CudaGraphicsResourceType C.gint

const (
	CudaGraphicsResourceNone CudaGraphicsResourceType = iota
	CudaGraphicsResourceGLBuffer
	CudaGraphicsResourceD3D11Resource
)

// String returns the name in string for CudaGraphicsResourceType.
func (c CudaGraphicsResourceType) String() string {
	switch c {
	case CudaGraphicsResourceNone:
		return "None"
	case CudaGraphicsResourceGLBuffer:
		return "GLBuffer"
	case CudaGraphicsResourceD3D11Resource:
		return "D3D11Resource"
	default:
		return fmt.Sprintf("CudaGraphicsResourceType(%d)", c)
	}
}

// CudaMemoryAllocMethod: CUDA memory allocation method.
type CudaMemoryAllocMethod C.gint

const (
	CudaMemoryAllocUnknown CudaMemoryAllocMethod = iota
	// CudaMemoryAllocMalloc: memory allocated via cuMemAlloc or
	// cuMemAllocPitch.
	CudaMemoryAllocMalloc
	// CudaMemoryAllocMmap: memory allocated via cuMemCreate and cuMemMap.
	CudaMemoryAllocMmap
)

func marshalCudaMemoryAllocMethod(p uintptr) (interface{}, error) {
	return CudaMemoryAllocMethod(coreglib.ValueFromNative(unsafe.Pointer(p)).Enum()), nil
}

// String returns the name in string for CudaMemoryAllocMethod.
func (c CudaMemoryAllocMethod) String() string {
	switch c {
	case CudaMemoryAllocUnknown:
		return "Unknown"
	case CudaMemoryAllocMalloc:
		return "Malloc"
	case CudaMemoryAllocMmap:
		return "Mmap"
	default:
		return fmt.Sprintf("CudaMemoryAllocMethod(%d)", c)
	}
}

type CudaQuarkID C.gint

const (
	CudaQuarkGraphicsResource CudaQuarkID = iota
	CudaQuarkMax
)

// String returns the name in string for CudaQuarkID.
func (c CudaQuarkID) String() string {
	switch c {
	case CudaQuarkGraphicsResource:
		return "GraphicsResource"
	case CudaQuarkMax:
		return "Max"
	default:
		return fmt.Sprintf("CudaQuarkID(%d)", c)
	}
}

// CudaMemoryTransfer: CUDA memory transfer flags.
type CudaMemoryTransfer C.guint

const (
	// CudaMemoryTransferNeedDownload: device memory needs downloading to the
	// staging memory.
	CudaMemoryTransferNeedDownload CudaMemoryTransfer = 0b100000000000000000000
	// CudaMemoryTransferNeedUpload: staging memory needs uploading to the
	// device memory.
	CudaMemoryTransferNeedUpload CudaMemoryTransfer = 0b1000000000000000000000
	// CudaMemoryTransferNeedSync: device memory needs synchronization.
	CudaMemoryTransferNeedSync CudaMemoryTransfer = 0b10000000000000000000000
)

// String returns the names in string for CudaMemoryTransfer.
func (c CudaMemoryTransfer) String() string {
	if c == 0 {
		return "CudaMemoryTransfer(0)"
	}

	var builder strings.Builder
	builder.Grow(86)

	for c != 0 {
		next := c & (c - 1)
		bit := c - next

		switch bit {
		case CudaMemoryTransferNeedDownload:
			builder.WriteString("Download|")
		case CudaMemoryTransferNeedUpload:
			builder.WriteString("Upload|")
		case CudaMemoryTransferNeedSync:
			builder.WriteString("Sync|")
		default:
			builder.WriteString(fmt.Sprintf("CudaMemoryTransfer(0b%b)|", bit))
		}

		c = next
	}

	return strings.TrimSuffix(builder.String(), "|")
}

// Has returns true if c contains other.
func (c CudaMemoryTransfer) Has(other CudaMemoryTransfer) bool {
	return (c & other) == other
}

// BufferPoolConfigGetCudaAllocMethod gets configured allocation method.
//
// The function takes the following parameters:
//
//   - config: buffer pool config.
func BufferPoolConfigGetCudaAllocMethod(config *gst.Structure) CudaMemoryAllocMethod {
	var _arg1 *C.GstStructure            // out
	var _cret C.GstCudaMemoryAllocMethod // in

	_arg1 = (*C.GstStructure)(gextras.StructNative(unsafe.Pointer(config)))

	_cret = C.gst_buffer_pool_config_get_cuda_alloc_method(_arg1)
	runtime.KeepAlive(config)

	var _cudaMemoryAllocMethod CudaMemoryAllocMethod // out

	_cudaMemoryAllocMethod = CudaMemoryAllocMethod(_cret)

	return _cudaMemoryAllocMethod
}

// The function takes the following parameters:
//
//   - config: buffer pool config.
//
// The function returns the following values:
//
//   - cudaStream (optional): currently configured CudaStream on config or NULL
//     if config doesn't hold CudaStream.
func BufferPoolConfigGetCudaStream(config *gst.Structure) *CudaStream {
	var _arg1 *C.GstStructure  // out
	var _cret *C.GstCudaStream // in

	_arg1 = (*C.GstStructure)(gextras.StructNative(unsafe.Pointer(config)))

	_cret = C.gst_buffer_pool_config_get_cuda_stream(_arg1)
	runtime.KeepAlive(config)

	var _cudaStream *CudaStream // out

	if _cret != nil {
		_cudaStream = (*CudaStream)(gextras.NewStructNative(unsafe.Pointer(_cret)))
		runtime.SetFinalizer(
			gextras.StructIntern(unsafe.Pointer(_cudaStream)),
			func(intern *struct{ C unsafe.Pointer }) {
				C.gst_cuda_stream_unref((*C.GstCudaStream)(intern.C))
			},
		)
	}

	return _cudaStream
}

// BufferPoolConfigSetCudaAllocMethod sets allocation method.
//
// The function takes the following parameters:
//
//   - config: buffer pool config.
//   - method
func BufferPoolConfigSetCudaAllocMethod(config *gst.Structure, method CudaMemoryAllocMethod) {
	var _arg1 *C.GstStructure            // out
	var _arg2 C.GstCudaMemoryAllocMethod // out

	_arg1 = (*C.GstStructure)(gextras.StructNative(unsafe.Pointer(config)))
	_arg2 = C.GstCudaMemoryAllocMethod(method)

	C.gst_buffer_pool_config_set_cuda_alloc_method(_arg1, _arg2)
	runtime.KeepAlive(config)
	runtime.KeepAlive(method)
}

// BufferPoolConfigSetCudaStream sets stream on config.
//
// The function takes the following parameters:
//
//   - config: buffer pool config.
//   - stream: CudaStream.
func BufferPoolConfigSetCudaStream(config *gst.Structure, stream *CudaStream) {
	var _arg1 *C.GstStructure  // out
	var _arg2 *C.GstCudaStream // out

	_arg1 = (*C.GstStructure)(gextras.StructNative(unsafe.Pointer(config)))
	_arg2 = (*C.GstCudaStream)(gextras.StructNative(unsafe.Pointer(stream)))

	C.gst_buffer_pool_config_set_cuda_stream(_arg1, _arg2)
	runtime.KeepAlive(config)
	runtime.KeepAlive(stream)
}

// The function takes the following parameters:
//
//   - cudaCtx: CudaContext.
//
// The function returns the following values:
//
//   - context: new Context embedding the cuda_ctx.
func ContextNewCudaContext(cudaCtx *CudaContext) *gst.Context {
	var _arg1 *C.GstCudaContext // out
	var _cret *C.GstContext     // in

	_arg1 = (*C.GstCudaContext)(unsafe.Pointer(coreglib.InternObject(cudaCtx).Native()))

	_cret = C.gst_context_new_cuda_context(_arg1)
	runtime.KeepAlive(cudaCtx)

	var _context *gst.Context // out

	_context = (*gst.Context)(gextras.NewStructNative(unsafe.Pointer(_cret)))
	runtime.SetFinalizer(
		gextras.StructIntern(unsafe.Pointer(_context)),
		func(intern *struct{ C unsafe.Pointer }) {
			C.free(intern.C)
		},
	)

	return _context
}

// CudaCreateUserToken creates new user token value.
//
// The function returns the following values:
//
//   - gint64: user token value.
func CudaCreateUserToken() int64 {
	var _cret C.gint64 // in

	_cret = C.gst_cuda_create_user_token()

	var _gint64 int64 // out

	_gint64 = int64(_cret)

	return _gint64
}

// The function takes the following parameters:
//
//   - element: Element.
//   - query of type GST_QUERY_CONTEXT.
//   - cudaCtx (optional): CudaContext.
//
// The function returns the following values:
//
//   - ok: whether the query was successfully responded to from the passed
//     context.
func CudaHandleContextQuery(element gst.Elementer, query *gst.Query, cudaCtx *CudaContext) bool {
	var _arg1 *C.GstElement     // out
	var _arg2 *C.GstQuery       // out
	var _arg3 *C.GstCudaContext // out
	var _cret C.gboolean        // in

	_arg1 = (*C.GstElement)(unsafe.Pointer(coreglib.InternObject(element).Native()))
	_arg2 = (*C.GstQuery)(gextras.StructNative(unsafe.Pointer(query)))
	if cudaCtx != nil {
		_arg3 = (*C.GstCudaContext)(unsafe.Pointer(coreglib.InternObject(cudaCtx).Native()))
	}

	_cret = C.gst_cuda_handle_context_query(_arg1, _arg2, _arg3)
	runtime.KeepAlive(element)
	runtime.KeepAlive(query)
	runtime.KeepAlive(cudaCtx)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// CudaLoadLibrary loads the cuda library.
//
// The function returns the following values:
//
//   - ok: TRUE if the libcuda could be loaded FALSE otherwise.
func CudaLoadLibrary() bool {
	var _cret C.gboolean // in

	_cret = C.gst_cuda_load_library()

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// The function takes the following parameters:
//
//   - source: source code to compile.
func CudaNvrtcCompile(source string) string {
	var _arg1 *C.gchar // out
	var _cret *C.gchar // in

	_arg1 = (*C.gchar)(unsafe.Pointer(C.CString(source)))
	defer C.free(unsafe.Pointer(_arg1))

	_cret = C.gst_cuda_nvrtc_compile(_arg1)
	runtime.KeepAlive(source)

	var _utf8 string // out

	_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))
	defer C.free(unsafe.Pointer(_cret))

	return _utf8
}

// The function takes the following parameters:
//
//   - source: source code to compile.
//   - device: CUDA device.
//
// The function returns the following values:
//
//   - utf8: compiled CUDA assembly code if successful, otherwise NULL.
func CudaNvrtcCompileCubin(source string, device int) string {
	var _arg1 *C.gchar // out
	var _arg2 C.gint   // out
	var _cret *C.gchar // in

	_arg1 = (*C.gchar)(unsafe.Pointer(C.CString(source)))
	defer C.free(unsafe.Pointer(_arg1))
	_arg2 = C.gint(device)

	_cret = C.gst_cuda_nvrtc_compile_cubin(_arg1, _arg2)
	runtime.KeepAlive(source)
	runtime.KeepAlive(device)

	var _utf8 string // out

	_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))
	defer C.free(unsafe.Pointer(_cret))

	return _utf8
}

// CudaNvrtcLoadLibrary loads the nvrtc library.
//
// The function returns the following values:
//
//   - ok: TRUE if the library could be loaded, FALSE otherwise.
func CudaNvrtcLoadLibrary() bool {
	var _cret C.gboolean // in

	_cret = C.gst_cuda_nvrtc_load_library()

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// IsCudaMemory: check if mem is a cuda memory.
//
// The function takes the following parameters:
//
//   - mem: Memory.
func IsCudaMemory(mem *gst.Memory) bool {
	var _arg1 *C.GstMemory // out
	var _cret C.gboolean   // in

	_arg1 = (*C.GstMemory)(gextras.StructNative(unsafe.Pointer(mem)))

	_cret = C.gst_is_cuda_memory(_arg1)
	runtime.KeepAlive(mem)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// CudaAllocatorOverrides contains methods that are overridable.
type CudaAllocatorOverrides struct {
	// SetActive controls the active state of allocator. Default CudaAllocator
	// is stateless and therefore active state is ignored, but subclass
	// implementation (e.g., CudaPoolAllocator) will require explicit active
	// state control for its internal resource management.
	//
	// This method is conceptually identical to gst_buffer_pool_set_active
	// method.
	//
	// The function takes the following parameters:
	//
	//   - active: new active state.
	//
	// The function returns the following values:
	//
	//   - ok: TRUE if active state of allocator was successfully updated.
	SetActive func(active bool) bool
}

func defaultCudaAllocatorOverrides(v *CudaAllocator) CudaAllocatorOverrides {
	return CudaAllocatorOverrides{
		SetActive: v.setActive,
	}
}

// CudaAllocator subclass for cuda memory.
type CudaAllocator struct {
	_ [0]func() // equal guard
	gst.Allocator
}

var (
	_ gst.Allocatorrer = (*CudaAllocator)(nil)
)

func init() {
	coreglib.RegisterClassInfo[*CudaAllocator, *CudaAllocatorClass, CudaAllocatorOverrides](
		GTypeCudaAllocator,
		initCudaAllocatorClass,
		wrapCudaAllocator,
		defaultCudaAllocatorOverrides,
	)
}

func initCudaAllocatorClass(gclass unsafe.Pointer, overrides CudaAllocatorOverrides, classInitFunc func(*CudaAllocatorClass)) {
	pclass := (*C.GstCudaAllocatorClass)(unsafe.Pointer(C.g_type_check_class_cast((*C.GTypeClass)(gclass), C.GType(GTypeCudaAllocator))))

	if overrides.SetActive != nil {
		pclass.set_active = (*[0]byte)(C._gotk4_gstcuda1_CudaAllocatorClass_set_active)
	}

	if classInitFunc != nil {
		class := (*CudaAllocatorClass)(gextras.NewStructNative(gclass))
		classInitFunc(class)
	}
}

func wrapCudaAllocator(obj *coreglib.Object) *CudaAllocator {
	return &CudaAllocator{
		Allocator: gst.Allocator{
			GstObject: gst.GstObject{
				InitiallyUnowned: coreglib.InitiallyUnowned{
					Object: obj,
				},
			},
		},
	}
}

func marshalCudaAllocator(p uintptr) (interface{}, error) {
	return wrapCudaAllocator(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// The function takes the following parameters:
//
//   - context: CudaContext.
//   - stream (optional): CudaStream.
//   - info: VideoInfo.
//
// The function returns the following values:
//
//   - memory (optional): newly allocated CudaMemory.
func (allocator *CudaAllocator) Alloc(context *CudaContext, stream *CudaStream, info *gstvideo.VideoInfo) *gst.Memory {
	var _arg0 *C.GstCudaAllocator // out
	var _arg1 *C.GstCudaContext   // out
	var _arg2 *C.GstCudaStream    // out
	var _arg3 *C.GstVideoInfo     // out
	var _cret *C.GstMemory        // in

	if allocator != nil {
		_arg0 = (*C.GstCudaAllocator)(unsafe.Pointer(coreglib.InternObject(allocator).Native()))
	}
	_arg1 = (*C.GstCudaContext)(unsafe.Pointer(coreglib.InternObject(context).Native()))
	if stream != nil {
		_arg2 = (*C.GstCudaStream)(gextras.StructNative(unsafe.Pointer(stream)))
	}
	_arg3 = (*C.GstVideoInfo)(gextras.StructNative(unsafe.Pointer(info)))

	_cret = C.gst_cuda_allocator_alloc(_arg0, _arg1, _arg2, _arg3)
	runtime.KeepAlive(allocator)
	runtime.KeepAlive(context)
	runtime.KeepAlive(stream)
	runtime.KeepAlive(info)

	var _memory *gst.Memory // out

	if _cret != nil {
		_memory = (*gst.Memory)(gextras.NewStructNative(unsafe.Pointer(_cret)))
		runtime.SetFinalizer(
			gextras.StructIntern(unsafe.Pointer(_memory)),
			func(intern *struct{ C unsafe.Pointer }) {
				C.free(intern.C)
			},
		)
	}

	return _memory
}

// SetActive controls the active state of allocator. Default CudaAllocator is
// stateless and therefore active state is ignored, but subclass implementation
// (e.g., CudaPoolAllocator) will require explicit active state control for its
// internal resource management.
//
// This method is conceptually identical to gst_buffer_pool_set_active method.
//
// The function takes the following parameters:
//
//   - active: new active state.
//
// The function returns the following values:
//
//   - ok: TRUE if active state of allocator was successfully updated.
func (allocator *CudaAllocator) SetActive(active bool) bool {
	var _arg0 *C.GstCudaAllocator // out
	var _arg1 C.gboolean          // out
	var _cret C.gboolean          // in

	_arg0 = (*C.GstCudaAllocator)(unsafe.Pointer(coreglib.InternObject(allocator).Native()))
	if active {
		_arg1 = C.TRUE
	}

	_cret = C.gst_cuda_allocator_set_active(_arg0, _arg1)
	runtime.KeepAlive(allocator)
	runtime.KeepAlive(active)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// VirtualAlloc allocates new Memory object with CUDA virtual memory.
//
// The function takes the following parameters:
//
//   - context: CudaContext.
//   - stream: CudaStream.
//   - info: VideoInfo.
//   - prop: allocation property.
//   - granularityFlags: allocation flags.
//
// The function returns the following values:
//
//   - memory (optional): newly allocated memory object or NULL if allocation is
//     not supported.
func (allocator *CudaAllocator) VirtualAlloc(context *CudaContext, stream *CudaStream, info *gstvideo.VideoInfo, prop *cudagst.memAllocationProp, granularityFlags cudagst.memAllocationGranularity_flags) *gst.Memory {
	var _arg0 *C.GstCudaAllocator                // out
	var _arg1 *C.GstCudaContext                  // out
	var _arg2 *C.GstCudaStream                   // out
	var _arg3 *C.GstVideoInfo                    // out
	var _arg4 *C.CUmemAllocationProp             // out
	var _arg5 C.CUmemAllocationGranularity_flags // out
	var _cret *C.GstMemory                       // in

	_arg0 = (*C.GstCudaAllocator)(unsafe.Pointer(coreglib.InternObject(allocator).Native()))
	_arg1 = (*C.GstCudaContext)(unsafe.Pointer(coreglib.InternObject(context).Native()))
	_arg2 = (*C.GstCudaStream)(gextras.StructNative(unsafe.Pointer(stream)))
	_arg3 = (*C.GstVideoInfo)(gextras.StructNative(unsafe.Pointer(info)))
	_arg4 = (*C.CUmemAllocationProp)(gextras.StructNative(unsafe.Pointer(prop)))
	_arg5 = C.CUmemAllocationGranularity_flags(granularityFlags)

	_cret = C.gst_cuda_allocator_virtual_alloc(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5)
	runtime.KeepAlive(allocator)
	runtime.KeepAlive(context)
	runtime.KeepAlive(stream)
	runtime.KeepAlive(info)
	runtime.KeepAlive(prop)
	runtime.KeepAlive(granularityFlags)

	var _memory *gst.Memory // out

	if _cret != nil {
		_memory = (*gst.Memory)(gextras.NewStructNative(unsafe.Pointer(_cret)))
		runtime.SetFinalizer(
			gextras.StructIntern(unsafe.Pointer(_memory)),
			func(intern *struct{ C unsafe.Pointer }) {
				C.free(intern.C)
			},
		)
	}

	return _memory
}

// setActive controls the active state of allocator. Default CudaAllocator is
// stateless and therefore active state is ignored, but subclass implementation
// (e.g., CudaPoolAllocator) will require explicit active state control for its
// internal resource management.
//
// This method is conceptually identical to gst_buffer_pool_set_active method.
//
// The function takes the following parameters:
//
//   - active: new active state.
//
// The function returns the following values:
//
//   - ok: TRUE if active state of allocator was successfully updated.
func (allocator *CudaAllocator) setActive(active bool) bool {
	gclass := (*C.GstCudaAllocatorClass)(coreglib.PeekParentClass(allocator))
	fnarg := gclass.set_active

	var _arg0 *C.GstCudaAllocator // out
	var _arg1 C.gboolean          // out
	var _cret C.gboolean          // in

	_arg0 = (*C.GstCudaAllocator)(unsafe.Pointer(coreglib.InternObject(allocator).Native()))
	if active {
		_arg1 = C.TRUE
	}

	_cret = C._gotk4_gstcuda1_CudaAllocator_virtual_set_active(unsafe.Pointer(fnarg), _arg0, _arg1)
	runtime.KeepAlive(allocator)
	runtime.KeepAlive(active)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// CudaBufferPoolOverrides contains methods that are overridable.
type CudaBufferPoolOverrides struct {
}

func defaultCudaBufferPoolOverrides(v *CudaBufferPool) CudaBufferPoolOverrides {
	return CudaBufferPoolOverrides{}
}

type CudaBufferPool struct {
	_ [0]func() // equal guard
	gst.BufferPool
}

var (
	_ gst.GstObjector = (*CudaBufferPool)(nil)
)

func init() {
	coreglib.RegisterClassInfo[*CudaBufferPool, *CudaBufferPoolClass, CudaBufferPoolOverrides](
		GTypeCudaBufferPool,
		initCudaBufferPoolClass,
		wrapCudaBufferPool,
		defaultCudaBufferPoolOverrides,
	)
}

func initCudaBufferPoolClass(gclass unsafe.Pointer, overrides CudaBufferPoolOverrides, classInitFunc func(*CudaBufferPoolClass)) {
	if classInitFunc != nil {
		class := (*CudaBufferPoolClass)(gextras.NewStructNative(gclass))
		classInitFunc(class)
	}
}

func wrapCudaBufferPool(obj *coreglib.Object) *CudaBufferPool {
	return &CudaBufferPool{
		BufferPool: gst.BufferPool{
			GstObject: gst.GstObject{
				InitiallyUnowned: coreglib.InitiallyUnowned{
					Object: obj,
				},
			},
		},
	}
}

func marshalCudaBufferPool(p uintptr) (interface{}, error) {
	return wrapCudaBufferPool(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// The function takes the following parameters:
//
//   - context to use for the new buffer pool.
//
// The function returns the following values:
//
//   - cudaBufferPool: newly created CudaBufferPool.
func NewCudaBufferPool(context *CudaContext) *CudaBufferPool {
	var _arg1 *C.GstCudaContext // out
	var _cret *C.GstBufferPool  // in

	_arg1 = (*C.GstCudaContext)(unsafe.Pointer(coreglib.InternObject(context).Native()))

	_cret = C.gst_cuda_buffer_pool_new(_arg1)
	runtime.KeepAlive(context)

	var _cudaBufferPool *CudaBufferPool // out

	_cudaBufferPool = wrapCudaBufferPool(coreglib.Take(unsafe.Pointer(_cret)))

	return _cudaBufferPool
}

// CudaContextOverrides contains methods that are overridable.
type CudaContextOverrides struct {
}

func defaultCudaContextOverrides(v *CudaContext) CudaContextOverrides {
	return CudaContextOverrides{}
}

type CudaContext struct {
	_ [0]func() // equal guard
	gst.GstObject
}

var (
	_ gst.GstObjector = (*CudaContext)(nil)
)

func init() {
	coreglib.RegisterClassInfo[*CudaContext, *CudaContextClass, CudaContextOverrides](
		GTypeCudaContext,
		initCudaContextClass,
		wrapCudaContext,
		defaultCudaContextOverrides,
	)
}

func initCudaContextClass(gclass unsafe.Pointer, overrides CudaContextOverrides, classInitFunc func(*CudaContextClass)) {
	if classInitFunc != nil {
		class := (*CudaContextClass)(gextras.NewStructNative(gclass))
		classInitFunc(class)
	}
}

func wrapCudaContext(obj *coreglib.Object) *CudaContext {
	return &CudaContext{
		GstObject: gst.GstObject{
			InitiallyUnowned: coreglib.InitiallyUnowned{
				Object: obj,
			},
		},
	}
}

func marshalCudaContext(p uintptr) (interface{}, error) {
	return wrapCudaContext(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// NewCudaContext: create CudaContext with given device_id.
//
// The function takes the following parameters:
//
//   - deviceId: device-id for creating CudaContext.
//
// The function returns the following values:
//
//   - cudaContext (optional): new CudaContext or NULL on failure.
func NewCudaContext(deviceId uint) *CudaContext {
	var _arg1 C.guint           // out
	var _cret *C.GstCudaContext // in

	_arg1 = C.guint(deviceId)

	_cret = C.gst_cuda_context_new(_arg1)
	runtime.KeepAlive(deviceId)

	var _cudaContext *CudaContext // out

	if _cret != nil {
		_cudaContext = wrapCudaContext(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))
	}

	return _cudaContext
}

// NewCudaContextWrapped: note: The caller is responsible for ensuring that the
// CUcontext and CUdevice represented by handle and device stay alive while the
// returned CudaContext is active.
//
// The function takes the following parameters:
//
//   - handler: a CUcontext
//     (https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__TYPES.html#group__CUDA__TYPES_1gf9f5bd81658f866613785b3a0bb7d7d9)
//     to wrap.
//   - device: a CUDevice
//     (https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__TYPES.html#group__CUDA__TYPES_1gf9f5bd81658f866613785b3a0bb7d7d9)
//     to wrap.
//
// The function returns the following values:
//
//   - cudaContext (optional): newly created CudaContext.
func NewCudaContextWrapped(handler cudagst.context, device cudagst.device) *CudaContext {
	var _arg1 C.CUcontext       // out
	var _arg2 C.CUdevice        // out
	var _cret *C.GstCudaContext // in

	_arg1 = (C.CUcontext)(unsafe.Pointer(handler))
	_arg2 = C.CUdevice(device)

	_cret = C.gst_cuda_context_new_wrapped(_arg1, _arg2)
	runtime.KeepAlive(handler)
	runtime.KeepAlive(device)

	var _cudaContext *CudaContext // out

	if _cret != nil {
		_cudaContext = wrapCudaContext(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))
	}

	return _cudaContext
}

// CanAccessPeer: query whether ctx can access any memory which belongs to peer
// directly.
//
// The function takes the following parameters:
//
//   - peer: CudaContext.
//
// The function returns the following values:
//
//   - ok: TRUE if ctx can access peer directly.
func (ctx *CudaContext) CanAccessPeer(peer *CudaContext) bool {
	var _arg0 *C.GstCudaContext // out
	var _arg1 *C.GstCudaContext // out
	var _cret C.gboolean        // in

	_arg0 = (*C.GstCudaContext)(unsafe.Pointer(coreglib.InternObject(ctx).Native()))
	_arg1 = (*C.GstCudaContext)(unsafe.Pointer(coreglib.InternObject(peer).Native()))

	_cret = C.gst_cuda_context_can_access_peer(_arg0, _arg1)
	runtime.KeepAlive(ctx)
	runtime.KeepAlive(peer)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// Handle: get CUDA device context. Caller must not modify and/or destroy
// returned device context.
//
// The function returns the following values:
//
//   - gpointer (optional): CUcontext of ctx.
func (ctx *CudaContext) Handle() unsafe.Pointer {
	var _arg0 *C.GstCudaContext // out
	var _cret C.gpointer        // in

	_arg0 = (*C.GstCudaContext)(unsafe.Pointer(coreglib.InternObject(ctx).Native()))

	_cret = C.gst_cuda_context_get_handle(_arg0)
	runtime.KeepAlive(ctx)

	var _gpointer unsafe.Pointer // out

	_gpointer = (unsafe.Pointer)(unsafe.Pointer(_cret))

	return _gpointer
}

// TextureAlignment: get required texture alignment by device.
//
// The function returns the following values:
//
//   - gint: CUcontext of ctx.
func (ctx *CudaContext) TextureAlignment() int {
	var _arg0 *C.GstCudaContext // out
	var _cret C.gint            // in

	_arg0 = (*C.GstCudaContext)(unsafe.Pointer(coreglib.InternObject(ctx).Native()))

	_cret = C.gst_cuda_context_get_texture_alignment(_arg0)
	runtime.KeepAlive(ctx)

	var _gint int // out

	_gint = int(_cret)

	return _gint
}

// Push pushes the given ctx onto the CPU thread's stack of current contexts.
// The specified context becomes the CPU thread's current context, so all CUDA
// functions that operate on the current context are affected.
//
// The function returns the following values:
//
//   - ok: TRUE if ctx was pushed without error.
func (ctx *CudaContext) Push() bool {
	var _arg0 *C.GstCudaContext // out
	var _cret C.gboolean        // in

	_arg0 = (*C.GstCudaContext)(unsafe.Pointer(coreglib.InternObject(ctx).Native()))

	_cret = C.gst_cuda_context_push(_arg0)
	runtime.KeepAlive(ctx)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// CudaContextPop pops the current CUDA context from CPU thread.
//
// The function returns the following values:
//
//   - ok: TRUE if ctx was pushed without error.
func CudaContextPop(cudaCtx *cudagst.context) bool {
	var _arg1 *C.CUcontext // out
	var _cret C.gboolean   // in

	_arg1 = (*C.CUcontext)(unsafe.Pointer(cudaCtx))

	_cret = C.gst_cuda_context_pop(_arg1)
	runtime.KeepAlive(cudaCtx)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// CudaPoolAllocatorOverrides contains methods that are overridable.
type CudaPoolAllocatorOverrides struct {
}

func defaultCudaPoolAllocatorOverrides(v *CudaPoolAllocator) CudaPoolAllocatorOverrides {
	return CudaPoolAllocatorOverrides{}
}

// CudaPoolAllocator subclass for cuda memory pool.
type CudaPoolAllocator struct {
	_ [0]func() // equal guard
	CudaAllocator
}

var (
	_ gst.Allocatorrer = (*CudaPoolAllocator)(nil)
)

func init() {
	coreglib.RegisterClassInfo[*CudaPoolAllocator, *CudaPoolAllocatorClass, CudaPoolAllocatorOverrides](
		GTypeCudaPoolAllocator,
		initCudaPoolAllocatorClass,
		wrapCudaPoolAllocator,
		defaultCudaPoolAllocatorOverrides,
	)
}

func initCudaPoolAllocatorClass(gclass unsafe.Pointer, overrides CudaPoolAllocatorOverrides, classInitFunc func(*CudaPoolAllocatorClass)) {
	if classInitFunc != nil {
		class := (*CudaPoolAllocatorClass)(gextras.NewStructNative(gclass))
		classInitFunc(class)
	}
}

func wrapCudaPoolAllocator(obj *coreglib.Object) *CudaPoolAllocator {
	return &CudaPoolAllocator{
		CudaAllocator: CudaAllocator{
			Allocator: gst.Allocator{
				GstObject: gst.GstObject{
					InitiallyUnowned: coreglib.InitiallyUnowned{
						Object: obj,
					},
				},
			},
		},
	}
}

func marshalCudaPoolAllocator(p uintptr) (interface{}, error) {
	return wrapCudaPoolAllocator(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// NewCudaPoolAllocator creates a new CudaPoolAllocator instance.
//
// The function takes the following parameters:
//
//   - context: CudaContext.
//   - stream (optional): CudaStream.
//   - info: VideoInfo.
//
// The function returns the following values:
//
//   - cudaPoolAllocator: new CudaPoolAllocator instance.
func NewCudaPoolAllocator(context *CudaContext, stream *CudaStream, info *gstvideo.VideoInfo) *CudaPoolAllocator {
	var _arg1 *C.GstCudaContext       // out
	var _arg2 *C.GstCudaStream        // out
	var _arg3 *C.GstVideoInfo         // out
	var _cret *C.GstCudaPoolAllocator // in

	_arg1 = (*C.GstCudaContext)(unsafe.Pointer(coreglib.InternObject(context).Native()))
	if stream != nil {
		_arg2 = (*C.GstCudaStream)(gextras.StructNative(unsafe.Pointer(stream)))
	}
	_arg3 = (*C.GstVideoInfo)(gextras.StructNative(unsafe.Pointer(info)))

	_cret = C.gst_cuda_pool_allocator_new(_arg1, _arg2, _arg3)
	runtime.KeepAlive(context)
	runtime.KeepAlive(stream)
	runtime.KeepAlive(info)

	var _cudaPoolAllocator *CudaPoolAllocator // out

	_cudaPoolAllocator = wrapCudaPoolAllocator(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))

	return _cudaPoolAllocator
}

// NewCudaPoolAllocatorForVirtualMemory creates a new CudaPoolAllocator instance
// for virtual memory allocation.
//
// The function takes the following parameters:
//
//   - context: CudaContext.
//   - stream (optional): CudaStream.
//   - info: VideoInfo.
//   - prop
//   - granularityFlags
//
// The function returns the following values:
//
//   - cudaPoolAllocator: new CudaPoolAllocator instance.
func NewCudaPoolAllocatorForVirtualMemory(context *CudaContext, stream *CudaStream, info *gstvideo.VideoInfo, prop *cudagst.memAllocationProp, granularityFlags cudagst.memAllocationGranularity_flags) *CudaPoolAllocator {
	var _arg1 *C.GstCudaContext                  // out
	var _arg2 *C.GstCudaStream                   // out
	var _arg3 *C.GstVideoInfo                    // out
	var _arg4 *C.CUmemAllocationProp             // out
	var _arg5 C.CUmemAllocationGranularity_flags // out
	var _cret *C.GstCudaPoolAllocator            // in

	_arg1 = (*C.GstCudaContext)(unsafe.Pointer(coreglib.InternObject(context).Native()))
	if stream != nil {
		_arg2 = (*C.GstCudaStream)(gextras.StructNative(unsafe.Pointer(stream)))
	}
	_arg3 = (*C.GstVideoInfo)(gextras.StructNative(unsafe.Pointer(info)))
	_arg4 = (*C.CUmemAllocationProp)(gextras.StructNative(unsafe.Pointer(prop)))
	_arg5 = C.CUmemAllocationGranularity_flags(granularityFlags)

	_cret = C.gst_cuda_pool_allocator_new_for_virtual_memory(_arg1, _arg2, _arg3, _arg4, _arg5)
	runtime.KeepAlive(context)
	runtime.KeepAlive(stream)
	runtime.KeepAlive(info)
	runtime.KeepAlive(prop)
	runtime.KeepAlive(granularityFlags)

	var _cudaPoolAllocator *CudaPoolAllocator // out

	_cudaPoolAllocator = wrapCudaPoolAllocator(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))

	return _cudaPoolAllocator
}

// AcquireMemory acquires a Memory from allocator. memory should point to a
// memory location that can hold a pointer to the new Memory.
//
// The function returns the following values:
//
//   - memory: Memory.
//   - flowReturn such as GST_FLOW_FLUSHING when the allocator is inactive.
func (allocator *CudaPoolAllocator) AcquireMemory() (*gst.Memory, gst.FlowReturn) {
	var _arg0 *C.GstCudaPoolAllocator // out
	var _arg1 *C.GstMemory            // in
	var _cret C.GstFlowReturn         // in

	_arg0 = (*C.GstCudaPoolAllocator)(unsafe.Pointer(coreglib.InternObject(allocator).Native()))

	_cret = C.gst_cuda_pool_allocator_acquire_memory(_arg0, &_arg1)
	runtime.KeepAlive(allocator)

	var _memory *gst.Memory        // out
	var _flowReturn gst.FlowReturn // out

	_memory = (*gst.Memory)(gextras.NewStructNative(unsafe.Pointer(_arg1)))
	runtime.SetFinalizer(
		gextras.StructIntern(unsafe.Pointer(_memory)),
		func(intern *struct{ C unsafe.Pointer }) {
			C.free(intern.C)
		},
	)
	_flowReturn = gst.FlowReturn(_cret)

	return _memory, _flowReturn
}

// CudaAllocatorClass: instance of this type is always passed by reference.
type CudaAllocatorClass struct {
	*cudaAllocatorClass
}

// cudaAllocatorClass is the struct that's finalized.
type cudaAllocatorClass struct {
	native *C.GstCudaAllocatorClass
}

func (c *CudaAllocatorClass) ParentClass() *gst.AllocatorClass {
	valptr := &c.native.parent_class
	var _v *gst.AllocatorClass // out
	_v = (*gst.AllocatorClass)(gextras.NewStructNative(unsafe.Pointer(valptr)))
	return _v
}

// CudaBufferPoolClass: instance of this type is always passed by reference.
type CudaBufferPoolClass struct {
	*cudaBufferPoolClass
}

// cudaBufferPoolClass is the struct that's finalized.
type cudaBufferPoolClass struct {
	native *C.GstCudaBufferPoolClass
}

func (c *CudaBufferPoolClass) ParentClass() *gst.BufferPoolClass {
	valptr := &c.native.parent_class
	var _v *gst.BufferPoolClass // out
	_v = (*gst.BufferPoolClass)(gextras.NewStructNative(unsafe.Pointer(valptr)))
	return _v
}

// CudaContextClass: instance of this type is always passed by reference.
type CudaContextClass struct {
	*cudaContextClass
}

// cudaContextClass is the struct that's finalized.
type cudaContextClass struct {
	native *C.GstCudaContextClass
}

func (c *CudaContextClass) ParentClass() *gst.ObjectClass {
	valptr := &c.native.parent_class
	var _v *gst.ObjectClass // out
	_v = (*gst.ObjectClass)(gextras.NewStructNative(unsafe.Pointer(valptr)))
	return _v
}

// CudaGraphicsResource: instance of this type is always passed by reference.
type CudaGraphicsResource struct {
	*cudaGraphicsResource
}

// cudaGraphicsResource is the struct that's finalized.
type cudaGraphicsResource struct {
	native *C.GstCudaGraphicsResource
}

func (c *CudaGraphicsResource) CudaContext() *CudaContext {
	valptr := &c.native.cuda_context
	var _v *CudaContext // out
	_v = wrapCudaContext(coreglib.Take(unsafe.Pointer(*valptr)))
	return _v
}

func (c *CudaGraphicsResource) GraphicsContext() gst.GstObjector {
	valptr := &c.native.graphics_context
	var _v gst.GstObjector // out
	{
		objptr := unsafe.Pointer(*valptr)
		if objptr == nil {
			panic("object of type gst.GstObjector is nil")
		}

		object := coreglib.Take(objptr)
		casted := object.WalkCast(func(obj coreglib.Objector) bool {
			_, ok := obj.(gst.GstObjector)
			return ok
		})
		rv, ok := casted.(gst.GstObjector)
		if !ok {
			panic("no marshaler for " + object.TypeFromInstance().String() + " matching gst.GstObjector")
		}
		_v = rv
	}
	return _v
}

func (c *CudaGraphicsResource) Type() CudaGraphicsResourceType {
	valptr := &c.native._type
	var _v CudaGraphicsResourceType // out
	_v = CudaGraphicsResourceType(*valptr)
	return _v
}

func (c *CudaGraphicsResource) Resource() cudagst.graphicsResource {
	valptr := &c.native.resource
	var _v cudagst.graphicsResource // out
	_v = (cudagst.graphicsResource)(unsafe.Pointer(*valptr))
	return _v
}

func (c *CudaGraphicsResource) Flags() cudagst.graphicsRegisterFlags {
	valptr := &c.native.flags
	var _v cudagst.graphicsRegisterFlags // out
	_v = cudagst.graphicsRegisterFlags(*valptr)
	return _v
}

func (c *CudaGraphicsResource) Registered() bool {
	valptr := &c.native.registered
	var _v bool // out
	if *valptr != 0 {
		_v = true
	}
	return _v
}

func (c *CudaGraphicsResource) Mapped() bool {
	valptr := &c.native.mapped
	var _v bool // out
	if *valptr != 0 {
		_v = true
	}
	return _v
}

func (c *CudaGraphicsResource) SetRegistered(registered bool) {
	valptr := &c.native.registered
	if registered {
		*valptr = C.TRUE
	}
}

func (c *CudaGraphicsResource) SetMapped(mapped bool) {
	valptr := &c.native.mapped
	if mapped {
		*valptr = C.TRUE
	}
}

// CudaMemory: instance of this type is always passed by reference.
type CudaMemory struct {
	*cudaMemory
}

// cudaMemory is the struct that's finalized.
type cudaMemory struct {
	native *C.GstCudaMemory
}

func (c *CudaMemory) Mem() *gst.Memory {
	valptr := &c.native.mem
	var _v *gst.Memory // out
	_v = (*gst.Memory)(gextras.NewStructNative(unsafe.Pointer(valptr)))
	return _v
}

func (c *CudaMemory) Context() *CudaContext {
	valptr := &c.native.context
	var _v *CudaContext // out
	_v = wrapCudaContext(coreglib.Take(unsafe.Pointer(*valptr)))
	return _v
}

func (c *CudaMemory) Info() *gstvideo.VideoInfo {
	valptr := &c.native.info
	var _v *gstvideo.VideoInfo // out
	_v = (*gstvideo.VideoInfo)(gextras.NewStructNative(unsafe.Pointer(valptr)))
	return _v
}

// AllocMethod: query allocation method.
func (mem *CudaMemory) AllocMethod() CudaMemoryAllocMethod {
	var _arg0 *C.GstCudaMemory           // out
	var _cret C.GstCudaMemoryAllocMethod // in

	_arg0 = (*C.GstCudaMemory)(gextras.StructNative(unsafe.Pointer(mem)))

	_cret = C.gst_cuda_memory_get_alloc_method(_arg0)
	runtime.KeepAlive(mem)

	var _cudaMemoryAllocMethod CudaMemoryAllocMethod // out

	_cudaMemoryAllocMethod = CudaMemoryAllocMethod(_cret)

	return _cudaMemoryAllocMethod
}

// Stream gets CUDA stream object associated with mem.
//
// The function returns the following values:
//
//   - cudaStream (optional) or NULL if default CUDA stream is in use.
func (mem *CudaMemory) Stream() *CudaStream {
	var _arg0 *C.GstCudaMemory // out
	var _cret *C.GstCudaStream // in

	_arg0 = (*C.GstCudaMemory)(gextras.StructNative(unsafe.Pointer(mem)))

	_cret = C.gst_cuda_memory_get_stream(_arg0)
	runtime.KeepAlive(mem)

	var _cudaStream *CudaStream // out

	if _cret != nil {
		_cudaStream = (*CudaStream)(gextras.NewStructNative(unsafe.Pointer(_cret)))
		C.gst_cuda_stream_ref(_cret)
		runtime.SetFinalizer(
			gextras.StructIntern(unsafe.Pointer(_cudaStream)),
			func(intern *struct{ C unsafe.Pointer }) {
				C.gst_cuda_stream_unref((*C.GstCudaStream)(intern.C))
			},
		)
	}

	return _cudaStream
}

// Texture creates CUtexObject with given parameters.
//
// The function takes the following parameters:
//
//   - plane index.
//   - filterMode: filter mode.
//
// The function returns the following values:
//
//   - texture: pointer to CUtexObject object.
//   - ok: TRUE if successful.
func (mem *CudaMemory) Texture(plane uint, filterMode cudagst.filter_mode) (cudagst.texObject, bool) {
	var _arg0 *C.GstCudaMemory // out
	var _arg1 C.guint          // out
	var _arg2 C.CUfilter_mode  // out
	var _arg3 C.CUtexObject    // in
	var _cret C.gboolean       // in

	_arg0 = (*C.GstCudaMemory)(gextras.StructNative(unsafe.Pointer(mem)))
	_arg1 = C.guint(plane)
	_arg2 = C.CUfilter_mode(filterMode)

	_cret = C.gst_cuda_memory_get_texture(_arg0, _arg1, _arg2, &_arg3)
	runtime.KeepAlive(mem)
	runtime.KeepAlive(plane)
	runtime.KeepAlive(filterMode)

	var _texture cudagst.texObject // out
	var _ok bool                   // out

	_texture = cudagst.texObject(_arg3)
	if _cret != 0 {
		_ok = true
	}

	return _texture, _ok
}

// TokenData gets back user data pointer stored via
// gst_cuda_memory_set_token_data().
//
// The function takes the following parameters:
//
//   - token: user token.
//
// The function returns the following values:
//
//   - gpointer (optional): user data pointer or NULL.
func (mem *CudaMemory) TokenData(token int64) unsafe.Pointer {
	var _arg0 *C.GstCudaMemory // out
	var _arg1 C.gint64         // out
	var _cret C.gpointer       // in

	_arg0 = (*C.GstCudaMemory)(gextras.StructNative(unsafe.Pointer(mem)))
	_arg1 = C.gint64(token)

	_cret = C.gst_cuda_memory_get_token_data(_arg0, _arg1)
	runtime.KeepAlive(mem)
	runtime.KeepAlive(token)

	var _gpointer unsafe.Pointer // out

	_gpointer = (unsafe.Pointer)(unsafe.Pointer(_cret))

	return _gpointer
}

// UserData gets user data pointer stored via
// gst_cuda_allocator_alloc_wrapped().
//
// The function returns the following values:
//
//   - gpointer (optional): user data pointer.
func (mem *CudaMemory) UserData() unsafe.Pointer {
	var _arg0 *C.GstCudaMemory // out
	var _cret C.gpointer       // in

	_arg0 = (*C.GstCudaMemory)(gextras.StructNative(unsafe.Pointer(mem)))

	_cret = C.gst_cuda_memory_get_user_data(_arg0)
	runtime.KeepAlive(mem)

	var _gpointer unsafe.Pointer // out

	_gpointer = (unsafe.Pointer)(unsafe.Pointer(_cret))

	return _gpointer
}

// Sync performs synchronization if needed.
func (mem *CudaMemory) Sync() {
	var _arg0 *C.GstCudaMemory // out

	_arg0 = (*C.GstCudaMemory)(gextras.StructNative(unsafe.Pointer(mem)))

	C.gst_cuda_memory_sync(_arg0)
	runtime.KeepAlive(mem)
}

// CudaMemoryInitOnce ensures that the CudaAllocator is initialized and ready to
// be used.
func CudaMemoryInitOnce() {
	C.gst_cuda_memory_init_once()
}

// CudaPoolAllocatorClass: instance of this type is always passed by reference.
type CudaPoolAllocatorClass struct {
	*cudaPoolAllocatorClass
}

// cudaPoolAllocatorClass is the struct that's finalized.
type cudaPoolAllocatorClass struct {
	native *C.GstCudaPoolAllocatorClass
}

func (c *CudaPoolAllocatorClass) ParentClass() *CudaAllocatorClass {
	valptr := &c.native.parent_class
	var _v *CudaAllocatorClass // out
	_v = (*CudaAllocatorClass)(gextras.NewStructNative(unsafe.Pointer(valptr)))
	return _v
}

// CudaStream: instance of this type is always passed by reference.
type CudaStream struct {
	*cudaStream
}

// cudaStream is the struct that's finalized.
type cudaStream struct {
	native *C.GstCudaStream
}

func marshalCudaStream(p uintptr) (interface{}, error) {
	b := coreglib.ValueFromNative(unsafe.Pointer(p)).Boxed()
	return &CudaStream{&cudaStream{(*C.GstCudaStream)(b)}}, nil
}

// NewCudaStream constructs a struct CudaStream.
func NewCudaStream(context *CudaContext) *CudaStream {
	var _arg1 *C.GstCudaContext // out
	var _cret *C.GstCudaStream  // in

	_arg1 = (*C.GstCudaContext)(unsafe.Pointer(coreglib.InternObject(context).Native()))

	_cret = C.gst_cuda_stream_new(_arg1)
	runtime.KeepAlive(context)

	var _cudaStream *CudaStream // out

	if _cret != nil {
		_cudaStream = (*CudaStream)(gextras.NewStructNative(unsafe.Pointer(_cret)))
		runtime.SetFinalizer(
			gextras.StructIntern(unsafe.Pointer(_cudaStream)),
			func(intern *struct{ C unsafe.Pointer }) {
				C.gst_cuda_stream_unref((*C.GstCudaStream)(intern.C))
			},
		)
	}

	return _cudaStream
}

func (c *CudaStream) Parent() *gst.MiniObject {
	valptr := &c.native.parent
	var _v *gst.MiniObject // out
	_v = (*gst.MiniObject)(gextras.NewStructNative(unsafe.Pointer(valptr)))
	return _v
}

func (c *CudaStream) Context() *CudaContext {
	valptr := &c.native.context
	var _v *CudaContext // out
	_v = wrapCudaContext(coreglib.Take(unsafe.Pointer(*valptr)))
	return _v
}

// Handle: get CUDA stream handle.
//
// The function returns the following values:
//
//   - ret: CUstream handle of stream or NULL if stream is NULL.
func (stream *CudaStream) Handle() cudagst.stream {
	var _arg0 *C.GstCudaStream // out
	var _cret C.CUstream       // in

	if stream != nil {
		_arg0 = (*C.GstCudaStream)(gextras.StructNative(unsafe.Pointer(stream)))
	}

	_cret = C.gst_cuda_stream_get_handle(_arg0)
	runtime.KeepAlive(stream)

	var _ret cudagst.stream // out

	_ret = (cudagst.stream)(unsafe.Pointer(_cret))

	return _ret
}
