// Code generated by girgen for Gdk-4. DO NOT EDIT.

package gdk

import (
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/classdata"
)

// #include <gdk/gdk.h>
import "C"

//export _gotk4_gdk4_Paintable_get_current_image
func _gotk4_gdk4_Paintable_get_current_image(carg0 *C.GdkPaintable) (cret *C.GdkPaintable) {
	var fn func(carg0 *C.GdkPaintable) (cret *C.GdkPaintable)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_gotk4_gdk4_Paintable_get_current_image").(func(carg0 *C.GdkPaintable) (cret *C.GdkPaintable))
		if fn == nil {
			panic("_gotk4_gdk4_Paintable_get_current_image: no function pointer found")
		}
	}
	return fn(carg0)
}

//export _gotk4_gdk4_Paintable_get_flags
func _gotk4_gdk4_Paintable_get_flags(carg0 *C.GdkPaintable) (cret C.GdkPaintableFlags) {
	var fn func(carg0 *C.GdkPaintable) (cret C.GdkPaintableFlags)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_gotk4_gdk4_Paintable_get_flags").(func(carg0 *C.GdkPaintable) (cret C.GdkPaintableFlags))
		if fn == nil {
			panic("_gotk4_gdk4_Paintable_get_flags: no function pointer found")
		}
	}
	return fn(carg0)
}

//export _gotk4_gdk4_Paintable_get_intrinsic_aspect_ratio
func _gotk4_gdk4_Paintable_get_intrinsic_aspect_ratio(carg0 *C.GdkPaintable) (cret C.double) {
	var fn func(carg0 *C.GdkPaintable) (cret C.double)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_gotk4_gdk4_Paintable_get_intrinsic_aspect_ratio").(func(carg0 *C.GdkPaintable) (cret C.double))
		if fn == nil {
			panic("_gotk4_gdk4_Paintable_get_intrinsic_aspect_ratio: no function pointer found")
		}
	}
	return fn(carg0)
}

//export _gotk4_gdk4_Paintable_get_intrinsic_height
func _gotk4_gdk4_Paintable_get_intrinsic_height(carg0 *C.GdkPaintable) (cret C.int) {
	var fn func(carg0 *C.GdkPaintable) (cret C.int)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_gotk4_gdk4_Paintable_get_intrinsic_height").(func(carg0 *C.GdkPaintable) (cret C.int))
		if fn == nil {
			panic("_gotk4_gdk4_Paintable_get_intrinsic_height: no function pointer found")
		}
	}
	return fn(carg0)
}

//export _gotk4_gdk4_Paintable_get_intrinsic_width
func _gotk4_gdk4_Paintable_get_intrinsic_width(carg0 *C.GdkPaintable) (cret C.int) {
	var fn func(carg0 *C.GdkPaintable) (cret C.int)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_gotk4_gdk4_Paintable_get_intrinsic_width").(func(carg0 *C.GdkPaintable) (cret C.int))
		if fn == nil {
			panic("_gotk4_gdk4_Paintable_get_intrinsic_width: no function pointer found")
		}
	}
	return fn(carg0)
}

//export _gotk4_gdk4_Paintable_snapshot
func _gotk4_gdk4_Paintable_snapshot(carg0 *C.GdkPaintable, carg1 *C.GdkSnapshot, carg2 C.double, carg3 C.double) {
	var fn func(carg0 *C.GdkPaintable, carg1 *C.GdkSnapshot, carg2 C.double, carg3 C.double)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_gotk4_gdk4_Paintable_snapshot").(func(carg0 *C.GdkPaintable, carg1 *C.GdkSnapshot, carg2 C.double, carg3 C.double))
		if fn == nil {
			panic("_gotk4_gdk4_Paintable_snapshot: no function pointer found")
		}
	}
	fn(carg0, carg1, carg2, carg3)
}

//export _gotk4_gdk4_ContentProvider_attach_clipboard
func _gotk4_gdk4_ContentProvider_attach_clipboard(carg0 *C.GdkContentProvider, carg1 *C.GdkClipboard) {
	var fn func(carg0 *C.GdkContentProvider, carg1 *C.GdkClipboard)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_gotk4_gdk4_ContentProvider_attach_clipboard").(func(carg0 *C.GdkContentProvider, carg1 *C.GdkClipboard))
		if fn == nil {
			panic("_gotk4_gdk4_ContentProvider_attach_clipboard: no function pointer found")
		}
	}
	fn(carg0, carg1)
}

//export _gotk4_gdk4_ContentProvider_content_changed
func _gotk4_gdk4_ContentProvider_content_changed(carg0 *C.GdkContentProvider) {
	var fn func(carg0 *C.GdkContentProvider)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_gotk4_gdk4_ContentProvider_content_changed").(func(carg0 *C.GdkContentProvider))
		if fn == nil {
			panic("_gotk4_gdk4_ContentProvider_content_changed: no function pointer found")
		}
	}
	fn(carg0)
}

//export _gotk4_gdk4_ContentProvider_detach_clipboard
func _gotk4_gdk4_ContentProvider_detach_clipboard(carg0 *C.GdkContentProvider, carg1 *C.GdkClipboard) {
	var fn func(carg0 *C.GdkContentProvider, carg1 *C.GdkClipboard)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_gotk4_gdk4_ContentProvider_detach_clipboard").(func(carg0 *C.GdkContentProvider, carg1 *C.GdkClipboard))
		if fn == nil {
			panic("_gotk4_gdk4_ContentProvider_detach_clipboard: no function pointer found")
		}
	}
	fn(carg0, carg1)
}

//export _gotk4_gdk4_ContentProvider_get_value
func _gotk4_gdk4_ContentProvider_get_value(carg0 *C.GdkContentProvider, carg1 *C.GValue, _cerr **C.GError) (cret C.gboolean) {
	var fn func(carg0 *C.GdkContentProvider, carg1 *C.GValue, _cerr **C.GError) (cret C.gboolean)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_gotk4_gdk4_ContentProvider_get_value").(func(carg0 *C.GdkContentProvider, carg1 *C.GValue, _cerr **C.GError) (cret C.gboolean))
		if fn == nil {
			panic("_gotk4_gdk4_ContentProvider_get_value: no function pointer found")
		}
	}
	return fn(carg0, carg1, _cerr)
}

//export _gotk4_gdk4_ContentProvider_ref_formats
func _gotk4_gdk4_ContentProvider_ref_formats(carg0 *C.GdkContentProvider) (cret *C.GdkContentFormats) {
	var fn func(carg0 *C.GdkContentProvider) (cret *C.GdkContentFormats)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_gotk4_gdk4_ContentProvider_ref_formats").(func(carg0 *C.GdkContentProvider) (cret *C.GdkContentFormats))
		if fn == nil {
			panic("_gotk4_gdk4_ContentProvider_ref_formats: no function pointer found")
		}
	}
	return fn(carg0)
}

//export _gotk4_gdk4_ContentProvider_ref_storable_formats
func _gotk4_gdk4_ContentProvider_ref_storable_formats(carg0 *C.GdkContentProvider) (cret *C.GdkContentFormats) {
	var fn func(carg0 *C.GdkContentProvider) (cret *C.GdkContentFormats)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_gotk4_gdk4_ContentProvider_ref_storable_formats").(func(carg0 *C.GdkContentProvider) (cret *C.GdkContentFormats))
		if fn == nil {
			panic("_gotk4_gdk4_ContentProvider_ref_storable_formats: no function pointer found")
		}
	}
	return fn(carg0)
}

//export _gotk4_gdk4_ContentProvider_write_mime_type_async
func _gotk4_gdk4_ContentProvider_write_mime_type_async(carg0 *C.GdkContentProvider, carg1 *C.char, carg2 *C.GOutputStream, carg3 C.int, carg4 *C.GCancellable, carg5 C.GAsyncReadyCallback, carg6 C.gpointer) {
	var fn func(carg0 *C.GdkContentProvider, carg1 *C.char, carg2 *C.GOutputStream, carg3 C.int, carg4 *C.GCancellable, carg5 C.GAsyncReadyCallback, carg6 C.gpointer)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_gotk4_gdk4_ContentProvider_write_mime_type_async").(func(carg0 *C.GdkContentProvider, carg1 *C.char, carg2 *C.GOutputStream, carg3 C.int, carg4 *C.GCancellable, carg5 C.GAsyncReadyCallback, carg6 C.gpointer))
		if fn == nil {
			panic("_gotk4_gdk4_ContentProvider_write_mime_type_async: no function pointer found")
		}
	}
	fn(carg0, carg1, carg2, carg3, carg4, carg5, carg6)
}

//export _gotk4_gdk4_ContentProvider_write_mime_type_finish
func _gotk4_gdk4_ContentProvider_write_mime_type_finish(carg0 *C.GdkContentProvider, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gboolean) {
	var fn func(carg0 *C.GdkContentProvider, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gboolean)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_gotk4_gdk4_ContentProvider_write_mime_type_finish").(func(carg0 *C.GdkContentProvider, carg1 *C.GAsyncResult, _cerr **C.GError) (cret C.gboolean))
		if fn == nil {
			panic("_gotk4_gdk4_ContentProvider_write_mime_type_finish: no function pointer found")
		}
	}
	return fn(carg0, carg1, _cerr)
}

