// Code generated by girgen. DO NOT EDIT.

package gdkwayland

import (
	"github.com/diamondburned/gotk4/pkg/core/gbox"
)

// #include <gdk/wayland/gdkwayland.h>
import "C"

//export _gotk4_gdkwayland4_WaylandToplevelExported
func _gotk4_gdkwayland4_WaylandToplevelExported(carg1 *C.GdkWaylandToplevel, carg2 *C.gchar, carg3 C.gpointer) (cret C.void) {


	fn(toplevel, handle)



	return cret
}

