// Code generated by girgen. DO NOT EDIT.

package gdkwayland

import (
	"unsafe"
	"github.com/diamondburned/gotk4/pkg/gdk/v4"
	"github.com/diamondburned/gotk4/pkg/gobject/v2"
	"runtime"
	"github.com/diamondburned/gotk4/pkg/glib/v2"
	"github.com/diamondburned/gotk4/pkg/core/gbox"
)

// #cgo pkg-config: gtk4-wayland
// #cgo CFLAGS: -Wno-deprecated-declarations
// #include <gdk/wayland/gdkwayland.h>
import "C"

// GType values.
var (
	GTypeWaylandDeviceInstance    = glib.Type(C.gdk_wayland_device_get_type())
	GTypeWaylandDisplayInstance   = glib.Type(C.gdk_wayland_display_get_type())
	GTypeWaylandGLContextInstance = glib.Type(C.gdk_wayland_gl_context_get_type())
	GTypeWaylandMonitorInstance   = glib.Type(C.gdk_wayland_monitor_get_type())
	GTypeWaylandSeatInstance      = glib.Type(C.gdk_wayland_seat_get_type())
	GTypeWaylandSurfaceInstance   = glib.Type(C.gdk_wayland_surface_get_type())
	GTypeWaylandToplevelInstance  = glib.Type(C.gdk_wayland_toplevel_get_type())
	GTypeWaylandPopupInstance     = glib.Type(C.gdk_wayland_popup_get_type())
)

func init() {
	glib.RegisterGValueMarshalers([]glib.TypeMarshaler{
		glib.TypeMarshaler{T: GTypeWaylandDeviceInstance, F: marshalWaylandDeviceInstance},
		glib.TypeMarshaler{T: GTypeWaylandDisplayInstance, F: marshalWaylandDisplayInstance},
		glib.TypeMarshaler{T: GTypeWaylandGLContextInstance, F: marshalWaylandGLContextInstance},
		glib.TypeMarshaler{T: GTypeWaylandMonitorInstance, F: marshalWaylandMonitorInstance},
		glib.TypeMarshaler{T: GTypeWaylandSeatInstance, F: marshalWaylandSeatInstance},
		glib.TypeMarshaler{T: GTypeWaylandSurfaceInstance, F: marshalWaylandSurfaceInstance},
		glib.TypeMarshaler{T: GTypeWaylandToplevelInstance, F: marshalWaylandToplevelInstance},
		glib.TypeMarshaler{T: GTypeWaylandPopupInstance, F: marshalWaylandPopupInstance},
	})
}

// WaylandToplevelExported wraps GdkWaylandToplevelExported
//
// Callback that gets called when the handle for a surface has been
// obtained from the Wayland compositor.
// 
// This callback is used in [method@GdkWayland.WaylandToplevel.export_handle].
// 
// The @handle can be passed to other processes, for the purpose of
// marking surfaces as transient for out-of-process surfaces.
type WaylandToplevelExported func(toplevel WaylandToplevel, handle string)

// WaylandDeviceInstance is the instance type used by all types extending GdkWaylandDevice. It is used internally by the bindings. Users should use the interface [WaylandDevice] instead.
type WaylandDeviceInstance struct {
	_ [0]func() // equal guard
	gdk.DeviceInstance
}

var _ WaylandDevice = (*WaylandDeviceInstance)(nil)

// WaylandDeviceInstance wraps GdkWaylandDevice
//
// The Wayland implementation of `GdkDevice`.
// 
// Beyond the regular [class@Gdk.Device] API, the Wayland implementation
// provides access to Wayland objects such as the `wl_seat` with
// [method@GdkWayland.WaylandDevice.get_wl_seat], the `wl_keyboard` with
// [method@GdkWayland.WaylandDevice.get_wl_keyboard] and the `wl_pointer` with
// [method@GdkWayland.WaylandDevice.get_wl_pointer].
type WaylandDevice interface {
	gdk.Device
	upcastToGdkWaylandDevice() *WaylandDeviceInstance

	// GetNodePath wraps gdk_wayland_device_get_node_path
	// The function returns the following values:
	// 
	// 	- ret string 
	//
	// Returns the `/dev/input/event*` path of this device.
	// 
	// For `GdkDevice`s that possibly coalesce multiple hardware
	// devices (eg. mouse, keyboard, touch,...), this function
	// will return %NULL.
	// 
	// This is most notably implemented for devices of type
	// %GDK_SOURCE_PEN, %GDK_SOURCE_TABLET_PAD.
	GetNodePath() string
	// GetXkbKeymap wraps gdk_wayland_device_get_xkb_keymap
	// The function returns the following values:
	// 
	// 	- ret unsafe.Pointer 
	//
	// Returns the `xkb_keymap` of a `GdkDevice`.
	GetXkbKeymap() unsafe.Pointer
}

func unsafeWrapWaylandDevice(base *gdk.ObjectInstance) *WaylandDeviceInstance {
	return &WaylandDeviceInstance{
		ObjectInstance: gobject.ObjectInstance{
			ObjectInstance: *base,
		},
	}
}

func marshalWaylandDeviceInstance(p uintptr) (interface{}, error) {
	return unsafeWrapWaylandDevice(gobject.TODOFromGlibBorrow(unsafe.Pointer(p)).Object()), nil
}

// UnsafeWaylandDeviceFromGlibBorrow is used to convert raw GdkWaylandDevice pointers to go. This is used by the bindings internally.
func UnsafeWaylandDeviceFromGlibBorrow(c unsafe.Pointer) WaylandDevice {
	return gdk.TODOBorrow(c).(WaylandDevice)
}

// UnsafeWaylandDeviceFromGlibNone is used to convert raw GdkWaylandDevice pointers to go while taking a reference and attaching a finalizer. This is used by the bindings internally.
func UnsafeWaylandDeviceFromGlibNone(c unsafe.Pointer) WaylandDevice {
	return gdk.Take(c).(WaylandDevice)
}

// UnsafeWaylandDeviceFromGlibFull is used to convert raw GdkWaylandDevice pointers to go while attaching a finalizer. This is used by the bindings internally.
func UnsafeWaylandDeviceFromGlibFull(c unsafe.Pointer) WaylandDevice {
	return gdk.AssumeOwnership(c).(WaylandDevice)
}

func (w *WaylandDeviceInstance) upcastToGdkWaylandDevice() *WaylandDeviceInstance {
	return w
}

// UnsafeWaylandDeviceToGlibNone is used to convert the instance to it's C value GdkWaylandDevice. This is used by the bindings internally.
func UnsafeWaylandDeviceToGlibNone(c WaylandDevice) unsafe.Pointer {
	return gdk.TODOToNone(c)
}

// UnsafeWaylandDeviceToGlibFull is used to convert the instance to it's C value GdkWaylandDevice, while removeing the finalizer. This is used by the bindings internally.
func UnsafeWaylandDeviceToGlibFull(c WaylandDevice) unsafe.Pointer {
	return gdk.TODOToFull(c)
}

// GetNodePath wraps gdk_wayland_device_get_node_path
// The function returns the following values:
// 
// 	- ret string 
//
// Returns the `/dev/input/event*` path of this device.
// 
// For `GdkDevice`s that possibly coalesce multiple hardware
// devices (eg. mouse, keyboard, touch,...), this function
// will return %NULL.
// 
// This is most notably implemented for devices of type
// %GDK_SOURCE_PEN, %GDK_SOURCE_TABLET_PAD.
func (device *WaylandDeviceInstance) GetNodePath() string {
	var carg0 *C.GdkWaylandDevice // in, none, converted
	var cret  *C.gchar            // return, none, string

	carg0 = (*C.GdkWaylandDevice)(UnsafeWaylandDeviceToGlibNone(device))

	cret = C.gdk_wayland_device_get_node_path(carg0)
	runtime.KeepAlive(device)

	var ret string

	ret = C.GoString((*C.gchar)(unsafe.Pointer(cret)))

	return ret
}

// GetXkbKeymap wraps gdk_wayland_device_get_xkb_keymap
// The function returns the following values:
// 
// 	- ret unsafe.Pointer 
//
// Returns the `xkb_keymap` of a `GdkDevice`.
func (device *WaylandDeviceInstance) GetXkbKeymap() unsafe.Pointer {
	var carg0 *C.GdkWaylandDevice // in, none, converted
	var cret  *C.gpointer         // return, none, casted

	carg0 = (*C.GdkWaylandDevice)(UnsafeWaylandDeviceToGlibNone(device))

	cret = C.gdk_wayland_device_get_xkb_keymap(carg0)
	runtime.KeepAlive(device)

	var ret unsafe.Pointer

	ret = unsafe.Pointer(cret)

	return ret
}

// WaylandDisplayInstance is the instance type used by all types extending GdkWaylandDisplay. It is used internally by the bindings. Users should use the interface [WaylandDisplay] instead.
type WaylandDisplayInstance struct {
	_ [0]func() // equal guard
	gdk.DisplayInstance
}

var _ WaylandDisplay = (*WaylandDisplayInstance)(nil)

// WaylandDisplayInstance wraps GdkWaylandDisplay
//
// The Wayland implementation of `GdkDisplay`.
// 
// Beyond the regular [class@Gdk.Display] API, the Wayland implementation
// provides access to Wayland objects such as the `wl_display` with
// [method@GdkWayland.WaylandDisplay.get_wl_display], the `wl_compositor` with
// [method@GdkWayland.WaylandDisplay.get_wl_compositor].
// 
// You can find out what Wayland globals are supported by a display
// with [method@GdkWayland.WaylandDisplay.query_registry].
type WaylandDisplay interface {
	gdk.Display
	upcastToGdkWaylandDisplay() *WaylandDisplayInstance

	// GetEglDisplay wraps gdk_wayland_display_get_egl_display
	// The function returns the following values:
	// 
	// 	- ret unsafe.Pointer 
	//
	// Retrieves the EGL display connection object for the given GDK display.
	GetEglDisplay() unsafe.Pointer
	// GetStartupNotificationID wraps gdk_wayland_display_get_startup_notification_id
	// The function returns the following values:
	// 
	// 	- ret string 
	//
	// Gets the startup notification ID for a Wayland display, or %NULL
	// if no ID has been defined.
	//
	// Deprecated: (since 4.10.0) 
	GetStartupNotificationID() string
	// QueryRegistry wraps gdk_wayland_display_query_registry
	// 
	// The function takes the following parameters:
	// 
	// 	- global string: global interface to query in the registry 
	// 
	// The function returns the following values:
	// 
	// 	- ret bool 
	//
	// Returns %TRUE if the interface was found in the display
	// `wl_registry.global` handler.
	QueryRegistry(string) bool
	// SetCursorTheme wraps gdk_wayland_display_set_cursor_theme
	// 
	// The function takes the following parameters:
	// 
	// 	- name string: the new cursor theme 
	// 	- size int: the size to use for cursors 
	//
	// Sets the cursor theme for the given @display.
	//
	// Deprecated: (since 4.16.0) Use the cursor-related properties of
	//   [GtkSettings](../gtk4/class.Settings.html) to set the cursor theme
	SetCursorTheme(string, int)
	// SetStartupNotificationID wraps gdk_wayland_display_set_startup_notification_id
	// 
	// The function takes the following parameters:
	// 
	// 	- startupId string: the startup notification ID (must be valid utf8) 
	//
	// Sets the startup notification ID for a display.
	// 
	// This is usually taken from the value of the `DESKTOP_STARTUP_ID`
	// environment variable, but in some cases (such as the application not
	// being launched using exec()) it can come from other sources.
	// 
	// The startup ID is also what is used to signal that the startup is
	// complete (for example, when opening a window or when calling
	// [method@Gdk.Display.notify_startup_complete]).
	//
	// Deprecated: (since 4.10.0) Use [method@Gdk.Toplevel.set_startup_id]
	SetStartupNotificationID(string)
}

func unsafeWrapWaylandDisplay(base *gdk.ObjectInstance) *WaylandDisplayInstance {
	return &WaylandDisplayInstance{
		ObjectInstance: gobject.ObjectInstance{
			ObjectInstance: *base,
		},
	}
}

func marshalWaylandDisplayInstance(p uintptr) (interface{}, error) {
	return unsafeWrapWaylandDisplay(gobject.TODOFromGlibBorrow(unsafe.Pointer(p)).Object()), nil
}

// UnsafeWaylandDisplayFromGlibBorrow is used to convert raw GdkWaylandDisplay pointers to go. This is used by the bindings internally.
func UnsafeWaylandDisplayFromGlibBorrow(c unsafe.Pointer) WaylandDisplay {
	return gdk.TODOBorrow(c).(WaylandDisplay)
}

// UnsafeWaylandDisplayFromGlibNone is used to convert raw GdkWaylandDisplay pointers to go while taking a reference and attaching a finalizer. This is used by the bindings internally.
func UnsafeWaylandDisplayFromGlibNone(c unsafe.Pointer) WaylandDisplay {
	return gdk.Take(c).(WaylandDisplay)
}

// UnsafeWaylandDisplayFromGlibFull is used to convert raw GdkWaylandDisplay pointers to go while attaching a finalizer. This is used by the bindings internally.
func UnsafeWaylandDisplayFromGlibFull(c unsafe.Pointer) WaylandDisplay {
	return gdk.AssumeOwnership(c).(WaylandDisplay)
}

func (w *WaylandDisplayInstance) upcastToGdkWaylandDisplay() *WaylandDisplayInstance {
	return w
}

// UnsafeWaylandDisplayToGlibNone is used to convert the instance to it's C value GdkWaylandDisplay. This is used by the bindings internally.
func UnsafeWaylandDisplayToGlibNone(c WaylandDisplay) unsafe.Pointer {
	return gdk.TODOToNone(c)
}

// UnsafeWaylandDisplayToGlibFull is used to convert the instance to it's C value GdkWaylandDisplay, while removeing the finalizer. This is used by the bindings internally.
func UnsafeWaylandDisplayToGlibFull(c WaylandDisplay) unsafe.Pointer {
	return gdk.TODOToFull(c)
}

// GetEglDisplay wraps gdk_wayland_display_get_egl_display
// The function returns the following values:
// 
// 	- ret unsafe.Pointer 
//
// Retrieves the EGL display connection object for the given GDK display.
func (display *WaylandDisplayInstance) GetEglDisplay() unsafe.Pointer {
	var carg0 *C.GdkWaylandDisplay // in, none, converted
	var cret  C.gpointer           // return, none, casted

	carg0 = (*C.GdkWaylandDisplay)(UnsafeWaylandDisplayToGlibNone(display))

	cret = C.gdk_wayland_display_get_egl_display(carg0)
	runtime.KeepAlive(display)

	var ret unsafe.Pointer

	ret = unsafe.Pointer(cret)

	return ret
}

// GetStartupNotificationID wraps gdk_wayland_display_get_startup_notification_id
// The function returns the following values:
// 
// 	- ret string 
//
// Gets the startup notification ID for a Wayland display, or %NULL
// if no ID has been defined.
//
// Deprecated: (since 4.10.0) 
func (display *WaylandDisplayInstance) GetStartupNotificationID() string {
	var carg0 *C.GdkWaylandDisplay // in, none, converted
	var cret  *C.gchar             // return, none, string

	carg0 = (*C.GdkWaylandDisplay)(UnsafeWaylandDisplayToGlibNone(display))

	cret = C.gdk_wayland_display_get_startup_notification_id(carg0)
	runtime.KeepAlive(display)

	var ret string

	ret = C.GoString((*C.gchar)(unsafe.Pointer(cret)))

	return ret
}

// QueryRegistry wraps gdk_wayland_display_query_registry
// 
// The function takes the following parameters:
// 
// 	- global string: global interface to query in the registry 
// 
// The function returns the following values:
// 
// 	- ret bool 
//
// Returns %TRUE if the interface was found in the display
// `wl_registry.global` handler.
func (display *WaylandDisplayInstance) QueryRegistry(global string) bool {
	var carg0 *C.GdkWaylandDisplay // in, none, converted
	var carg1 *C.gchar             // in, none, string
	var cret  C.gboolean           // return

	carg0 = (*C.GdkWaylandDisplay)(UnsafeWaylandDisplayToGlibNone(display))
	carg1 = (*C.gchar)(unsafe.Pointer(C.CString(global)))
	defer C.free(unsafe.Pointer(carg1))

	cret = C.gdk_wayland_display_query_registry(carg0, carg1)
	runtime.KeepAlive(display)
	runtime.KeepAlive(global)

	var ret bool

	if cret != 0 {
		ret = true
	}

	return ret
}

// SetCursorTheme wraps gdk_wayland_display_set_cursor_theme
// 
// The function takes the following parameters:
// 
// 	- name string: the new cursor theme 
// 	- size int: the size to use for cursors 
//
// Sets the cursor theme for the given @display.
//
// Deprecated: (since 4.16.0) Use the cursor-related properties of
//   [GtkSettings](../gtk4/class.Settings.html) to set the cursor theme
func (display *WaylandDisplayInstance) SetCursorTheme(name string, size int) {
	var carg0 *C.GdkWaylandDisplay // in, none, converted
	var carg1 *C.gchar             // in, none, string
	var carg2 C.int                // in, none, casted

	carg0 = (*C.GdkWaylandDisplay)(UnsafeWaylandDisplayToGlibNone(display))
	carg1 = (*C.gchar)(unsafe.Pointer(C.CString(name)))
	defer C.free(unsafe.Pointer(carg1))
	carg2 = C.int(size)

	C.gdk_wayland_display_set_cursor_theme(carg0, carg1, carg2)
	runtime.KeepAlive(display)
	runtime.KeepAlive(name)
	runtime.KeepAlive(size)
}

// SetStartupNotificationID wraps gdk_wayland_display_set_startup_notification_id
// 
// The function takes the following parameters:
// 
// 	- startupId string: the startup notification ID (must be valid utf8) 
//
// Sets the startup notification ID for a display.
// 
// This is usually taken from the value of the `DESKTOP_STARTUP_ID`
// environment variable, but in some cases (such as the application not
// being launched using exec()) it can come from other sources.
// 
// The startup ID is also what is used to signal that the startup is
// complete (for example, when opening a window or when calling
// [method@Gdk.Display.notify_startup_complete]).
//
// Deprecated: (since 4.10.0) Use [method@Gdk.Toplevel.set_startup_id]
func (display *WaylandDisplayInstance) SetStartupNotificationID(startupId string) {
	var carg0 *C.GdkWaylandDisplay // in, none, converted
	var carg1 *C.gchar             // in, none, string

	carg0 = (*C.GdkWaylandDisplay)(UnsafeWaylandDisplayToGlibNone(display))
	carg1 = (*C.gchar)(unsafe.Pointer(C.CString(startupId)))
	defer C.free(unsafe.Pointer(carg1))

	C.gdk_wayland_display_set_startup_notification_id(carg0, carg1)
	runtime.KeepAlive(display)
	runtime.KeepAlive(startupId)
}

// WaylandGLContextInstance is the instance type used by all types extending GdkWaylandGLContext. It is used internally by the bindings. Users should use the interface [WaylandGLContext] instead.
type WaylandGLContextInstance struct {
	_ [0]func() // equal guard
	gdk.GLContextInstance
}

var _ WaylandGLContext = (*WaylandGLContextInstance)(nil)

// WaylandGLContextInstance wraps GdkWaylandGLContext
//
// The Wayland implementation of `GdkGLContext`.
type WaylandGLContext interface {
	gdk.GLContext
	upcastToGdkWaylandGLContext() *WaylandGLContextInstance

}

func unsafeWrapWaylandGLContext(base *gobject.ObjectInstance) *WaylandGLContextInstance {
	return &WaylandGLContextInstance{
		DrawContextInstance: gdk.DrawContextInstance{
			ObjectInstance: gobject.ObjectInstance{
				ObjectInstance: *base,
			},
		},
	}
}

func marshalWaylandGLContextInstance(p uintptr) (interface{}, error) {
	return unsafeWrapWaylandGLContext(gobject.TODOFromGlibBorrow(unsafe.Pointer(p)).Object()), nil
}

// UnsafeWaylandGLContextFromGlibBorrow is used to convert raw GdkWaylandGLContext pointers to go. This is used by the bindings internally.
func UnsafeWaylandGLContextFromGlibBorrow(c unsafe.Pointer) WaylandGLContext {
	return gobject.TODOBorrow(c).(WaylandGLContext)
}

// UnsafeWaylandGLContextFromGlibNone is used to convert raw GdkWaylandGLContext pointers to go while taking a reference and attaching a finalizer. This is used by the bindings internally.
func UnsafeWaylandGLContextFromGlibNone(c unsafe.Pointer) WaylandGLContext {
	return gobject.Take(c).(WaylandGLContext)
}

// UnsafeWaylandGLContextFromGlibFull is used to convert raw GdkWaylandGLContext pointers to go while attaching a finalizer. This is used by the bindings internally.
func UnsafeWaylandGLContextFromGlibFull(c unsafe.Pointer) WaylandGLContext {
	return gobject.AssumeOwnership(c).(WaylandGLContext)
}

func (w *WaylandGLContextInstance) upcastToGdkWaylandGLContext() *WaylandGLContextInstance {
	return w
}

// UnsafeWaylandGLContextToGlibNone is used to convert the instance to it's C value GdkWaylandGLContext. This is used by the bindings internally.
func UnsafeWaylandGLContextToGlibNone(c WaylandGLContext) unsafe.Pointer {
	return gobject.TODOToNone(c)
}

// UnsafeWaylandGLContextToGlibFull is used to convert the instance to it's C value GdkWaylandGLContext, while removeing the finalizer. This is used by the bindings internally.
func UnsafeWaylandGLContextToGlibFull(c WaylandGLContext) unsafe.Pointer {
	return gobject.TODOToFull(c)
}

// WaylandMonitorInstance is the instance type used by all types extending GdkWaylandMonitor. It is used internally by the bindings. Users should use the interface [WaylandMonitor] instead.
type WaylandMonitorInstance struct {
	_ [0]func() // equal guard
	gdk.MonitorInstance
}

var _ WaylandMonitor = (*WaylandMonitorInstance)(nil)

// WaylandMonitorInstance wraps GdkWaylandMonitor
//
// The Wayland implementation of `GdkMonitor`.
// 
// Beyond the [class@Gdk.Monitor] API, the Wayland implementation
// offers access to the Wayland `wl_output` object with
// [method@GdkWayland.WaylandMonitor.get_wl_output].
type WaylandMonitor interface {
	gdk.Monitor
	upcastToGdkWaylandMonitor() *WaylandMonitorInstance

}

func unsafeWrapWaylandMonitor(base *gdk.ObjectInstance) *WaylandMonitorInstance {
	return &WaylandMonitorInstance{
		ObjectInstance: gobject.ObjectInstance{
			ObjectInstance: *base,
		},
	}
}

func marshalWaylandMonitorInstance(p uintptr) (interface{}, error) {
	return unsafeWrapWaylandMonitor(gobject.TODOFromGlibBorrow(unsafe.Pointer(p)).Object()), nil
}

// UnsafeWaylandMonitorFromGlibBorrow is used to convert raw GdkWaylandMonitor pointers to go. This is used by the bindings internally.
func UnsafeWaylandMonitorFromGlibBorrow(c unsafe.Pointer) WaylandMonitor {
	return gdk.TODOBorrow(c).(WaylandMonitor)
}

// UnsafeWaylandMonitorFromGlibNone is used to convert raw GdkWaylandMonitor pointers to go while taking a reference and attaching a finalizer. This is used by the bindings internally.
func UnsafeWaylandMonitorFromGlibNone(c unsafe.Pointer) WaylandMonitor {
	return gdk.Take(c).(WaylandMonitor)
}

// UnsafeWaylandMonitorFromGlibFull is used to convert raw GdkWaylandMonitor pointers to go while attaching a finalizer. This is used by the bindings internally.
func UnsafeWaylandMonitorFromGlibFull(c unsafe.Pointer) WaylandMonitor {
	return gdk.AssumeOwnership(c).(WaylandMonitor)
}

func (w *WaylandMonitorInstance) upcastToGdkWaylandMonitor() *WaylandMonitorInstance {
	return w
}

// UnsafeWaylandMonitorToGlibNone is used to convert the instance to it's C value GdkWaylandMonitor. This is used by the bindings internally.
func UnsafeWaylandMonitorToGlibNone(c WaylandMonitor) unsafe.Pointer {
	return gdk.TODOToNone(c)
}

// UnsafeWaylandMonitorToGlibFull is used to convert the instance to it's C value GdkWaylandMonitor, while removeing the finalizer. This is used by the bindings internally.
func UnsafeWaylandMonitorToGlibFull(c WaylandMonitor) unsafe.Pointer {
	return gdk.TODOToFull(c)
}

// WaylandSeatInstance is the instance type used by all types extending GdkWaylandSeat. It is used internally by the bindings. Users should use the interface [WaylandSeat] instead.
type WaylandSeatInstance struct {
	_ [0]func() // equal guard
	gdk.SeatInstance
}

var _ WaylandSeat = (*WaylandSeatInstance)(nil)

// WaylandSeatInstance wraps GdkWaylandSeat
//
// The Wayland implementation of `GdkSeat`.
// 
// Beyond the regular [class@Gdk.Seat] API, the Wayland implementation
// provides access to the Wayland `wl_seat` object with
// [method@GdkWayland.WaylandSeat.get_wl_seat].
type WaylandSeat interface {
	gdk.Seat
	upcastToGdkWaylandSeat() *WaylandSeatInstance

}

func unsafeWrapWaylandSeat(base *gdk.ObjectInstance) *WaylandSeatInstance {
	return &WaylandSeatInstance{
		ObjectInstance: gobject.ObjectInstance{
			ObjectInstance: *base,
		},
	}
}

func marshalWaylandSeatInstance(p uintptr) (interface{}, error) {
	return unsafeWrapWaylandSeat(gobject.TODOFromGlibBorrow(unsafe.Pointer(p)).Object()), nil
}

// UnsafeWaylandSeatFromGlibBorrow is used to convert raw GdkWaylandSeat pointers to go. This is used by the bindings internally.
func UnsafeWaylandSeatFromGlibBorrow(c unsafe.Pointer) WaylandSeat {
	return gdk.TODOBorrow(c).(WaylandSeat)
}

// UnsafeWaylandSeatFromGlibNone is used to convert raw GdkWaylandSeat pointers to go while taking a reference and attaching a finalizer. This is used by the bindings internally.
func UnsafeWaylandSeatFromGlibNone(c unsafe.Pointer) WaylandSeat {
	return gdk.Take(c).(WaylandSeat)
}

// UnsafeWaylandSeatFromGlibFull is used to convert raw GdkWaylandSeat pointers to go while attaching a finalizer. This is used by the bindings internally.
func UnsafeWaylandSeatFromGlibFull(c unsafe.Pointer) WaylandSeat {
	return gdk.AssumeOwnership(c).(WaylandSeat)
}

func (w *WaylandSeatInstance) upcastToGdkWaylandSeat() *WaylandSeatInstance {
	return w
}

// UnsafeWaylandSeatToGlibNone is used to convert the instance to it's C value GdkWaylandSeat. This is used by the bindings internally.
func UnsafeWaylandSeatToGlibNone(c WaylandSeat) unsafe.Pointer {
	return gdk.TODOToNone(c)
}

// UnsafeWaylandSeatToGlibFull is used to convert the instance to it's C value GdkWaylandSeat, while removeing the finalizer. This is used by the bindings internally.
func UnsafeWaylandSeatToGlibFull(c WaylandSeat) unsafe.Pointer {
	return gdk.TODOToFull(c)
}

// WaylandSurfaceInstance is the instance type used by all types extending GdkWaylandSurface. It is used internally by the bindings. Users should use the interface [WaylandSurface] instead.
type WaylandSurfaceInstance struct {
	_ [0]func() // equal guard
	gdk.SurfaceInstance
}

var _ WaylandSurface = (*WaylandSurfaceInstance)(nil)

// WaylandSurfaceInstance wraps GdkWaylandSurface
//
// The Wayland implementation of `GdkSurface`.
// 
// Beyond the [class@Gdk.Surface] API, the Wayland implementation offers
// access to the Wayland `wl_surface` object with
// [method@GdkWayland.WaylandSurface.get_wl_surface].
type WaylandSurface interface {
	gdk.Surface
	upcastToGdkWaylandSurface() *WaylandSurfaceInstance

}

func unsafeWrapWaylandSurface(base *gdk.ObjectInstance) *WaylandSurfaceInstance {
	return &WaylandSurfaceInstance{
		ObjectInstance: gobject.ObjectInstance{
			ObjectInstance: *base,
		},
	}
}

func marshalWaylandSurfaceInstance(p uintptr) (interface{}, error) {
	return unsafeWrapWaylandSurface(gobject.TODOFromGlibBorrow(unsafe.Pointer(p)).Object()), nil
}

// UnsafeWaylandSurfaceFromGlibBorrow is used to convert raw GdkWaylandSurface pointers to go. This is used by the bindings internally.
func UnsafeWaylandSurfaceFromGlibBorrow(c unsafe.Pointer) WaylandSurface {
	return gdk.TODOBorrow(c).(WaylandSurface)
}

// UnsafeWaylandSurfaceFromGlibNone is used to convert raw GdkWaylandSurface pointers to go while taking a reference and attaching a finalizer. This is used by the bindings internally.
func UnsafeWaylandSurfaceFromGlibNone(c unsafe.Pointer) WaylandSurface {
	return gdk.Take(c).(WaylandSurface)
}

// UnsafeWaylandSurfaceFromGlibFull is used to convert raw GdkWaylandSurface pointers to go while attaching a finalizer. This is used by the bindings internally.
func UnsafeWaylandSurfaceFromGlibFull(c unsafe.Pointer) WaylandSurface {
	return gdk.AssumeOwnership(c).(WaylandSurface)
}

func (w *WaylandSurfaceInstance) upcastToGdkWaylandSurface() *WaylandSurfaceInstance {
	return w
}

// UnsafeWaylandSurfaceToGlibNone is used to convert the instance to it's C value GdkWaylandSurface. This is used by the bindings internally.
func UnsafeWaylandSurfaceToGlibNone(c WaylandSurface) unsafe.Pointer {
	return gdk.TODOToNone(c)
}

// UnsafeWaylandSurfaceToGlibFull is used to convert the instance to it's C value GdkWaylandSurface, while removeing the finalizer. This is used by the bindings internally.
func UnsafeWaylandSurfaceToGlibFull(c WaylandSurface) unsafe.Pointer {
	return gdk.TODOToFull(c)
}

// WaylandToplevelInstance is the instance type used by all types extending GdkWaylandToplevel. It is used internally by the bindings. Users should use the interface [WaylandToplevel] instead.
type WaylandToplevelInstance struct {
	_ [0]func() // equal guard
	WaylandSurfaceInstance
	// implemented interfaces:
gdk.Toplevel
}

var _ WaylandToplevel = (*WaylandToplevelInstance)(nil)

// WaylandToplevelInstance wraps GdkWaylandToplevel
//
// The Wayland implementation of `GdkToplevel`.
// 
// Beyond the [iface@Gdk.Toplevel] API, the Wayland implementation
// has API to set up cross-process parent-child relationships between
// surfaces with [method@GdkWayland.WaylandToplevel.export_handle] and
// [method@GdkWayland.WaylandToplevel.set_transient_for_exported].
type WaylandToplevel interface {
	WaylandSurface
	gdk.Toplevel
	upcastToGdkWaylandToplevel() *WaylandToplevelInstance

	// DropExportedHandle wraps gdk_wayland_toplevel_drop_exported_handle
	// 
	// The function takes the following parameters:
	// 
	// 	- handle string: the handle to drop 
	//
	// Destroy a handle that was obtained with gdk_wayland_toplevel_export_handle().
	// 
	// Note that this API depends on an unstable Wayland protocol,
	// and thus may require changes in the future.
	DropExportedHandle(string)
	// ExportHandle wraps gdk_wayland_toplevel_export_handle
	// 
	// The function takes the following parameters:
	// 
	// 	- callback WaylandToplevelExported: callback to call with the handle 
	// 
	// The function returns the following values:
	// 
	// 	- ret bool 
	//
	// Asynchronously obtains a handle for a surface that can be passed
	// to other processes.
	// 
	// When the handle has been obtained, @callback will be called.
	// 
	// It is an error to call this function on a surface that is already
	// exported.
	// 
	// When the handle is no longer needed, [method@GdkWayland.WaylandToplevel.unexport_handle]
	// should be called to clean up resources.
	// 
	// The main purpose for obtaining a handle is to mark a surface
	// from another surface as transient for this one, see
	// [method@GdkWayland.WaylandToplevel.set_transient_for_exported].
	// 
	// Before 4.12, this API could not safely be used multiple times,
	// since there was no reference counting for handles. Starting with
	// 4.12, every call to this function obtains a new handle, and every
	// call to [method@GdkWayland.WaylandToplevel.drop_exported_handle] drops
	// just the handle that it is given.
	// 
	// Note that this API depends on an unstable Wayland protocol,
	// and thus may require changes in the future.
	ExportHandle(WaylandToplevelExported) bool
	// SetApplicationID wraps gdk_wayland_toplevel_set_application_id
	// 
	// The function takes the following parameters:
	// 
	// 	- applicationId string: the application id for the @toplevel 
	//
	// Sets the application id on a `GdkToplevel`.
	SetApplicationID(string)
	// SetTransientForExported wraps gdk_wayland_toplevel_set_transient_for_exported
	// 
	// The function takes the following parameters:
	// 
	// 	- parentHandleStr string: an exported handle for a surface 
	// 
	// The function returns the following values:
	// 
	// 	- ret bool 
	//
	// Marks @toplevel as transient for the surface to which the given
	// @parent_handle_str refers.
	// 
	// Typically, the handle will originate from a
	// [method@GdkWayland.WaylandToplevel.export_handle] call in another process.
	// 
	// Note that this API depends on an unstable Wayland protocol,
	// and thus may require changes in the future.
	SetTransientForExported(string) bool
	// UnexportHandle wraps gdk_wayland_toplevel_unexport_handle
	//
	// Destroys the handle that was obtained with
	// gdk_wayland_toplevel_export_handle().
	// 
	// It is an error to call this function on a surface that
	// does not have a handle.
	// 
	// Since 4.12, this function does nothing. Use
	// [method@GdkWayland.WaylandToplevel.drop_exported_handle] instead to drop a
	// handle that was obtained with [method@GdkWayland.WaylandToplevel.export_handle].
	// 
	// Note that this API depends on an unstable Wayland protocol,
	// and thus may require changes in the future.
	//
	// Deprecated: (since 4.12.0) Use [method@GdkWayland.WaylandToplevel.drop_exported_handle]
	//   instead, this function does nothing
	UnexportHandle()
}

func unsafeWrapWaylandToplevel(base *gobject.ObjectInstance) *WaylandToplevelInstance {
	return &WaylandToplevelInstance{
		SurfaceInstance: gdk.SurfaceInstance{
			ObjectInstance: gobject.ObjectInstance{
				ObjectInstance: *base,
			},
		},
		ToplevelInstance: gdk.ToplevelInstance{
			ObjectInstance: *base,
		},
	}
}

func marshalWaylandToplevelInstance(p uintptr) (interface{}, error) {
	return unsafeWrapWaylandToplevel(gobject.TODOFromGlibBorrow(unsafe.Pointer(p)).Object()), nil
}

// UnsafeWaylandToplevelFromGlibBorrow is used to convert raw GdkWaylandToplevel pointers to go. This is used by the bindings internally.
func UnsafeWaylandToplevelFromGlibBorrow(c unsafe.Pointer) WaylandToplevel {
	return gobject.TODOBorrow(c).(WaylandToplevel)
}

// UnsafeWaylandToplevelFromGlibNone is used to convert raw GdkWaylandToplevel pointers to go while taking a reference and attaching a finalizer. This is used by the bindings internally.
func UnsafeWaylandToplevelFromGlibNone(c unsafe.Pointer) WaylandToplevel {
	return gobject.Take(c).(WaylandToplevel)
}

// UnsafeWaylandToplevelFromGlibFull is used to convert raw GdkWaylandToplevel pointers to go while attaching a finalizer. This is used by the bindings internally.
func UnsafeWaylandToplevelFromGlibFull(c unsafe.Pointer) WaylandToplevel {
	return gobject.AssumeOwnership(c).(WaylandToplevel)
}

func (w *WaylandToplevelInstance) upcastToGdkWaylandToplevel() *WaylandToplevelInstance {
	return w
}

// UnsafeWaylandToplevelToGlibNone is used to convert the instance to it's C value GdkWaylandToplevel. This is used by the bindings internally.
func UnsafeWaylandToplevelToGlibNone(c WaylandToplevel) unsafe.Pointer {
	return gobject.TODOToNone(c)
}

// UnsafeWaylandToplevelToGlibFull is used to convert the instance to it's C value GdkWaylandToplevel, while removeing the finalizer. This is used by the bindings internally.
func UnsafeWaylandToplevelToGlibFull(c WaylandToplevel) unsafe.Pointer {
	return gobject.TODOToFull(c)
}

// DropExportedHandle wraps gdk_wayland_toplevel_drop_exported_handle
// 
// The function takes the following parameters:
// 
// 	- handle string: the handle to drop 
//
// Destroy a handle that was obtained with gdk_wayland_toplevel_export_handle().
// 
// Note that this API depends on an unstable Wayland protocol,
// and thus may require changes in the future.
func (toplevel *WaylandToplevelInstance) DropExportedHandle(handle string) {
	var carg0 *C.GdkWaylandToplevel // in, none, converted
	var carg1 *C.gchar              // in, none, string

	carg0 = (*C.GdkWaylandToplevel)(UnsafeWaylandToplevelToGlibNone(toplevel))
	carg1 = (*C.gchar)(unsafe.Pointer(C.CString(handle)))
	defer C.free(unsafe.Pointer(carg1))

	C.gdk_wayland_toplevel_drop_exported_handle(carg0, carg1)
	runtime.KeepAlive(toplevel)
	runtime.KeepAlive(handle)
}

// ExportHandle wraps gdk_wayland_toplevel_export_handle
// 
// The function takes the following parameters:
// 
// 	- callback WaylandToplevelExported: callback to call with the handle 
// 
// The function returns the following values:
// 
// 	- ret bool 
//
// Asynchronously obtains a handle for a surface that can be passed
// to other processes.
// 
// When the handle has been obtained, @callback will be called.
// 
// It is an error to call this function on a surface that is already
// exported.
// 
// When the handle is no longer needed, [method@GdkWayland.WaylandToplevel.unexport_handle]
// should be called to clean up resources.
// 
// The main purpose for obtaining a handle is to mark a surface
// from another surface as transient for this one, see
// [method@GdkWayland.WaylandToplevel.set_transient_for_exported].
// 
// Before 4.12, this API could not safely be used multiple times,
// since there was no reference counting for handles. Starting with
// 4.12, every call to this function obtains a new handle, and every
// call to [method@GdkWayland.WaylandToplevel.drop_exported_handle] drops
// just the handle that it is given.
// 
// Note that this API depends on an unstable Wayland protocol,
// and thus may require changes in the future.
func (toplevel *WaylandToplevelInstance) ExportHandle(callback WaylandToplevelExported) bool {
	var carg0 *C.GdkWaylandToplevel        // in, none, converted
	var carg1 C.GdkWaylandToplevelExported // callback, scope: notified, closure: carg2, destroy: carg3
	var carg2 C.gpointer                   // implicit
	var carg3 C.GDestroyNotify             // implicit
	var cret  C.gboolean                   // return

	carg0 = (*C.GdkWaylandToplevel)(UnsafeWaylandToplevelToGlibNone(toplevel))
	carg1 = (*[0]byte)(C._gotk4_gdkwayland4_WaylandToplevelExported)
	carg2 = C.gpointer(gbox.Assign(callback))
	carg3 = (C.GDestroyNotify)((*[0]byte)(C.callbackDelete))

	cret = C.gdk_wayland_toplevel_export_handle(carg0, carg1, carg2, carg3)
	runtime.KeepAlive(toplevel)
	runtime.KeepAlive(callback)

	var ret bool

	if cret != 0 {
		ret = true
	}

	return ret
}

// SetApplicationID wraps gdk_wayland_toplevel_set_application_id
// 
// The function takes the following parameters:
// 
// 	- applicationId string: the application id for the @toplevel 
//
// Sets the application id on a `GdkToplevel`.
func (toplevel *WaylandToplevelInstance) SetApplicationID(applicationId string) {
	var carg0 *C.GdkWaylandToplevel // in, none, converted
	var carg1 *C.gchar              // in, none, string

	carg0 = (*C.GdkWaylandToplevel)(UnsafeWaylandToplevelToGlibNone(toplevel))
	carg1 = (*C.gchar)(unsafe.Pointer(C.CString(applicationId)))
	defer C.free(unsafe.Pointer(carg1))

	C.gdk_wayland_toplevel_set_application_id(carg0, carg1)
	runtime.KeepAlive(toplevel)
	runtime.KeepAlive(applicationId)
}

// SetTransientForExported wraps gdk_wayland_toplevel_set_transient_for_exported
// 
// The function takes the following parameters:
// 
// 	- parentHandleStr string: an exported handle for a surface 
// 
// The function returns the following values:
// 
// 	- ret bool 
//
// Marks @toplevel as transient for the surface to which the given
// @parent_handle_str refers.
// 
// Typically, the handle will originate from a
// [method@GdkWayland.WaylandToplevel.export_handle] call in another process.
// 
// Note that this API depends on an unstable Wayland protocol,
// and thus may require changes in the future.
func (toplevel *WaylandToplevelInstance) SetTransientForExported(parentHandleStr string) bool {
	var carg0 *C.GdkWaylandToplevel // in, none, converted
	var carg1 *C.gchar              // in, none, string
	var cret  C.gboolean            // return

	carg0 = (*C.GdkWaylandToplevel)(UnsafeWaylandToplevelToGlibNone(toplevel))
	carg1 = (*C.gchar)(unsafe.Pointer(C.CString(parentHandleStr)))
	defer C.free(unsafe.Pointer(carg1))

	cret = C.gdk_wayland_toplevel_set_transient_for_exported(carg0, carg1)
	runtime.KeepAlive(toplevel)
	runtime.KeepAlive(parentHandleStr)

	var ret bool

	if cret != 0 {
		ret = true
	}

	return ret
}

// UnexportHandle wraps gdk_wayland_toplevel_unexport_handle
//
// Destroys the handle that was obtained with
// gdk_wayland_toplevel_export_handle().
// 
// It is an error to call this function on a surface that
// does not have a handle.
// 
// Since 4.12, this function does nothing. Use
// [method@GdkWayland.WaylandToplevel.drop_exported_handle] instead to drop a
// handle that was obtained with [method@GdkWayland.WaylandToplevel.export_handle].
// 
// Note that this API depends on an unstable Wayland protocol,
// and thus may require changes in the future.
//
// Deprecated: (since 4.12.0) Use [method@GdkWayland.WaylandToplevel.drop_exported_handle]
//   instead, this function does nothing
func (toplevel *WaylandToplevelInstance) UnexportHandle() {
	var carg0 *C.GdkWaylandToplevel // in, none, converted

	carg0 = (*C.GdkWaylandToplevel)(UnsafeWaylandToplevelToGlibNone(toplevel))

	C.gdk_wayland_toplevel_unexport_handle(carg0)
	runtime.KeepAlive(toplevel)
}

// WaylandPopupInstance is the instance type used by all types extending GdkWaylandPopup. It is used internally by the bindings. Users should use the interface [WaylandPopup] instead.
type WaylandPopupInstance struct {
	_ [0]func() // equal guard
	WaylandSurfaceInstance
	// implemented interfaces:
gdk.Popup
}

var _ WaylandPopup = (*WaylandPopupInstance)(nil)

// WaylandPopupInstance wraps GdkWaylandPopup
//
// The Wayland implementation of `GdkPopup`.
type WaylandPopup interface {
	WaylandSurface
	gdk.Popup
	upcastToGdkWaylandPopup() *WaylandPopupInstance

}

func unsafeWrapWaylandPopup(base *gobject.ObjectInstance) *WaylandPopupInstance {
	return &WaylandPopupInstance{
		SurfaceInstance: gdk.SurfaceInstance{
			ObjectInstance: gobject.ObjectInstance{
				ObjectInstance: *base,
			},
		},
		PopupInstance: gdk.PopupInstance{
			ObjectInstance: *base,
		},
	}
}

func marshalWaylandPopupInstance(p uintptr) (interface{}, error) {
	return unsafeWrapWaylandPopup(gobject.TODOFromGlibBorrow(unsafe.Pointer(p)).Object()), nil
}

// UnsafeWaylandPopupFromGlibBorrow is used to convert raw GdkWaylandPopup pointers to go. This is used by the bindings internally.
func UnsafeWaylandPopupFromGlibBorrow(c unsafe.Pointer) WaylandPopup {
	return gobject.TODOBorrow(c).(WaylandPopup)
}

// UnsafeWaylandPopupFromGlibNone is used to convert raw GdkWaylandPopup pointers to go while taking a reference and attaching a finalizer. This is used by the bindings internally.
func UnsafeWaylandPopupFromGlibNone(c unsafe.Pointer) WaylandPopup {
	return gobject.Take(c).(WaylandPopup)
}

// UnsafeWaylandPopupFromGlibFull is used to convert raw GdkWaylandPopup pointers to go while attaching a finalizer. This is used by the bindings internally.
func UnsafeWaylandPopupFromGlibFull(c unsafe.Pointer) WaylandPopup {
	return gobject.AssumeOwnership(c).(WaylandPopup)
}

func (w *WaylandPopupInstance) upcastToGdkWaylandPopup() *WaylandPopupInstance {
	return w
}

// UnsafeWaylandPopupToGlibNone is used to convert the instance to it's C value GdkWaylandPopup. This is used by the bindings internally.
func UnsafeWaylandPopupToGlibNone(c WaylandPopup) unsafe.Pointer {
	return gobject.TODOToNone(c)
}

// UnsafeWaylandPopupToGlibFull is used to convert the instance to it's C value GdkWaylandPopup, while removeing the finalizer. This is used by the bindings internally.
func UnsafeWaylandPopupToGlibFull(c WaylandPopup) unsafe.Pointer {
	return gobject.TODOToFull(c)
}

// WaylandDeviceClass wraps GdkWaylandDeviceClass
type WaylandDeviceClass struct {
	*waylandDeviceClass
}

// waylandDeviceClass is the struct that's finalized
type waylandDeviceClass struct {
	native *C.GdkWaylandDeviceClass
}

// UnsafeWaylandDeviceClassFromGlibBorrow is used to convert raw C.GdkWaylandDeviceClass pointers to go. This is used by the bindings internally.
func UnsafeWaylandDeviceClassFromGlibBorrow(p unsafe.Pointer) *WaylandDeviceClass {
	return &WaylandDeviceClass{&waylandDeviceClass{(*C.GdkWaylandDeviceClass)(p)}}
}

// UnsafeWaylandDeviceClassFromGlibFull is used to convert raw C.GdkWaylandDeviceClass pointers to go while taking a reference. This is used by the bindings internally.
func UnsafeWaylandDeviceClassFromGlibFull(p unsafe.Pointer) *WaylandDeviceClass {
	wrapped := UnsafeWaylandDeviceClassFromGlibBorrow(p)
	runtime.SetFinalizer(
		wrapped.waylandDeviceClass,
		func (intern *waylandDeviceClass) {
			C.free(unsafe.Pointer(intern.native))
		},
	)
	return wrapped
}

// UnsafeWaylandDeviceClassFree unrefs/frees the underlying resource. This is used by the bindings internally.
// 
// After this is called, no other method on [WaylandDeviceClass] is expected to work anymore.
func UnsafeWaylandDeviceClassFree(w *WaylandDeviceClass) {
	C.free(unsafe.Pointer(w.native))
}

// UnsafeWaylandDeviceClassToGlibNone returns the underlying C pointer. This is used by the bindings internally.
func UnsafeWaylandDeviceClassToGlibNone(w *WaylandDeviceClass) unsafe.Pointer {
	return unsafe.Pointer(w.native)
}

// UnsafeWaylandDeviceClassToGlibFull returns the underlying C pointer and gives up ownership.
// This is used by the bindings internally.
func UnsafeWaylandDeviceClassToGlibFull(w *WaylandDeviceClass) unsafe.Pointer {
	runtime.SetFinalizer(w.waylandDeviceClass, nil)
	_p := unsafe.Pointer(w.native)
	w.native = nil // WaylandDeviceClass is invalid from here on
	return _p
}
// WaylandDisplayClass wraps GdkWaylandDisplayClass
type WaylandDisplayClass struct {
	*waylandDisplayClass
}

// waylandDisplayClass is the struct that's finalized
type waylandDisplayClass struct {
	native *C.GdkWaylandDisplayClass
}

// UnsafeWaylandDisplayClassFromGlibBorrow is used to convert raw C.GdkWaylandDisplayClass pointers to go. This is used by the bindings internally.
func UnsafeWaylandDisplayClassFromGlibBorrow(p unsafe.Pointer) *WaylandDisplayClass {
	return &WaylandDisplayClass{&waylandDisplayClass{(*C.GdkWaylandDisplayClass)(p)}}
}

// UnsafeWaylandDisplayClassFromGlibFull is used to convert raw C.GdkWaylandDisplayClass pointers to go while taking a reference. This is used by the bindings internally.
func UnsafeWaylandDisplayClassFromGlibFull(p unsafe.Pointer) *WaylandDisplayClass {
	wrapped := UnsafeWaylandDisplayClassFromGlibBorrow(p)
	runtime.SetFinalizer(
		wrapped.waylandDisplayClass,
		func (intern *waylandDisplayClass) {
			C.free(unsafe.Pointer(intern.native))
		},
	)
	return wrapped
}

// UnsafeWaylandDisplayClassFree unrefs/frees the underlying resource. This is used by the bindings internally.
// 
// After this is called, no other method on [WaylandDisplayClass] is expected to work anymore.
func UnsafeWaylandDisplayClassFree(w *WaylandDisplayClass) {
	C.free(unsafe.Pointer(w.native))
}

// UnsafeWaylandDisplayClassToGlibNone returns the underlying C pointer. This is used by the bindings internally.
func UnsafeWaylandDisplayClassToGlibNone(w *WaylandDisplayClass) unsafe.Pointer {
	return unsafe.Pointer(w.native)
}

// UnsafeWaylandDisplayClassToGlibFull returns the underlying C pointer and gives up ownership.
// This is used by the bindings internally.
func UnsafeWaylandDisplayClassToGlibFull(w *WaylandDisplayClass) unsafe.Pointer {
	runtime.SetFinalizer(w.waylandDisplayClass, nil)
	_p := unsafe.Pointer(w.native)
	w.native = nil // WaylandDisplayClass is invalid from here on
	return _p
}
// WaylandGLContextClass wraps GdkWaylandGLContextClass
type WaylandGLContextClass struct {
	*waylandGLContextClass
}

// waylandGLContextClass is the struct that's finalized
type waylandGLContextClass struct {
	native *C.GdkWaylandGLContextClass
}

// UnsafeWaylandGLContextClassFromGlibBorrow is used to convert raw C.GdkWaylandGLContextClass pointers to go. This is used by the bindings internally.
func UnsafeWaylandGLContextClassFromGlibBorrow(p unsafe.Pointer) *WaylandGLContextClass {
	return &WaylandGLContextClass{&waylandGLContextClass{(*C.GdkWaylandGLContextClass)(p)}}
}

// UnsafeWaylandGLContextClassFromGlibFull is used to convert raw C.GdkWaylandGLContextClass pointers to go while taking a reference. This is used by the bindings internally.
func UnsafeWaylandGLContextClassFromGlibFull(p unsafe.Pointer) *WaylandGLContextClass {
	wrapped := UnsafeWaylandGLContextClassFromGlibBorrow(p)
	runtime.SetFinalizer(
		wrapped.waylandGLContextClass,
		func (intern *waylandGLContextClass) {
			C.free(unsafe.Pointer(intern.native))
		},
	)
	return wrapped
}

// UnsafeWaylandGLContextClassFree unrefs/frees the underlying resource. This is used by the bindings internally.
// 
// After this is called, no other method on [WaylandGLContextClass] is expected to work anymore.
func UnsafeWaylandGLContextClassFree(w *WaylandGLContextClass) {
	C.free(unsafe.Pointer(w.native))
}

// UnsafeWaylandGLContextClassToGlibNone returns the underlying C pointer. This is used by the bindings internally.
func UnsafeWaylandGLContextClassToGlibNone(w *WaylandGLContextClass) unsafe.Pointer {
	return unsafe.Pointer(w.native)
}

// UnsafeWaylandGLContextClassToGlibFull returns the underlying C pointer and gives up ownership.
// This is used by the bindings internally.
func UnsafeWaylandGLContextClassToGlibFull(w *WaylandGLContextClass) unsafe.Pointer {
	runtime.SetFinalizer(w.waylandGLContextClass, nil)
	_p := unsafe.Pointer(w.native)
	w.native = nil // WaylandGLContextClass is invalid from here on
	return _p
}
// WaylandMonitorClass wraps GdkWaylandMonitorClass
type WaylandMonitorClass struct {
	*waylandMonitorClass
}

// waylandMonitorClass is the struct that's finalized
type waylandMonitorClass struct {
	native *C.GdkWaylandMonitorClass
}

// UnsafeWaylandMonitorClassFromGlibBorrow is used to convert raw C.GdkWaylandMonitorClass pointers to go. This is used by the bindings internally.
func UnsafeWaylandMonitorClassFromGlibBorrow(p unsafe.Pointer) *WaylandMonitorClass {
	return &WaylandMonitorClass{&waylandMonitorClass{(*C.GdkWaylandMonitorClass)(p)}}
}

// UnsafeWaylandMonitorClassFromGlibFull is used to convert raw C.GdkWaylandMonitorClass pointers to go while taking a reference. This is used by the bindings internally.
func UnsafeWaylandMonitorClassFromGlibFull(p unsafe.Pointer) *WaylandMonitorClass {
	wrapped := UnsafeWaylandMonitorClassFromGlibBorrow(p)
	runtime.SetFinalizer(
		wrapped.waylandMonitorClass,
		func (intern *waylandMonitorClass) {
			C.free(unsafe.Pointer(intern.native))
		},
	)
	return wrapped
}

// UnsafeWaylandMonitorClassFree unrefs/frees the underlying resource. This is used by the bindings internally.
// 
// After this is called, no other method on [WaylandMonitorClass] is expected to work anymore.
func UnsafeWaylandMonitorClassFree(w *WaylandMonitorClass) {
	C.free(unsafe.Pointer(w.native))
}

// UnsafeWaylandMonitorClassToGlibNone returns the underlying C pointer. This is used by the bindings internally.
func UnsafeWaylandMonitorClassToGlibNone(w *WaylandMonitorClass) unsafe.Pointer {
	return unsafe.Pointer(w.native)
}

// UnsafeWaylandMonitorClassToGlibFull returns the underlying C pointer and gives up ownership.
// This is used by the bindings internally.
func UnsafeWaylandMonitorClassToGlibFull(w *WaylandMonitorClass) unsafe.Pointer {
	runtime.SetFinalizer(w.waylandMonitorClass, nil)
	_p := unsafe.Pointer(w.native)
	w.native = nil // WaylandMonitorClass is invalid from here on
	return _p
}
// WaylandSeatClass wraps GdkWaylandSeatClass
type WaylandSeatClass struct {
	*waylandSeatClass
}

// waylandSeatClass is the struct that's finalized
type waylandSeatClass struct {
	native *C.GdkWaylandSeatClass
}

// UnsafeWaylandSeatClassFromGlibBorrow is used to convert raw C.GdkWaylandSeatClass pointers to go. This is used by the bindings internally.
func UnsafeWaylandSeatClassFromGlibBorrow(p unsafe.Pointer) *WaylandSeatClass {
	return &WaylandSeatClass{&waylandSeatClass{(*C.GdkWaylandSeatClass)(p)}}
}

// UnsafeWaylandSeatClassFromGlibFull is used to convert raw C.GdkWaylandSeatClass pointers to go while taking a reference. This is used by the bindings internally.
func UnsafeWaylandSeatClassFromGlibFull(p unsafe.Pointer) *WaylandSeatClass {
	wrapped := UnsafeWaylandSeatClassFromGlibBorrow(p)
	runtime.SetFinalizer(
		wrapped.waylandSeatClass,
		func (intern *waylandSeatClass) {
			C.free(unsafe.Pointer(intern.native))
		},
	)
	return wrapped
}

// UnsafeWaylandSeatClassFree unrefs/frees the underlying resource. This is used by the bindings internally.
// 
// After this is called, no other method on [WaylandSeatClass] is expected to work anymore.
func UnsafeWaylandSeatClassFree(w *WaylandSeatClass) {
	C.free(unsafe.Pointer(w.native))
}

// UnsafeWaylandSeatClassToGlibNone returns the underlying C pointer. This is used by the bindings internally.
func UnsafeWaylandSeatClassToGlibNone(w *WaylandSeatClass) unsafe.Pointer {
	return unsafe.Pointer(w.native)
}

// UnsafeWaylandSeatClassToGlibFull returns the underlying C pointer and gives up ownership.
// This is used by the bindings internally.
func UnsafeWaylandSeatClassToGlibFull(w *WaylandSeatClass) unsafe.Pointer {
	runtime.SetFinalizer(w.waylandSeatClass, nil)
	_p := unsafe.Pointer(w.native)
	w.native = nil // WaylandSeatClass is invalid from here on
	return _p
}
