// Code generated by girgen for GdkPixdata-2. DO NOT EDIT.

package gdkpixdata

import (
	"runtime"
	"strings"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/gdkpixbuf/v2"
	"github.com/diamondburned/gotk4/pkg/glib/v2"
)

// #cgo pkg-config: gdk-pixbuf-2.0
// #cgo CFLAGS: -Wno-deprecated-declarations
// #include <gdk-pixbuf/gdk-pixdata.h>
import "C"


// PIXBUF_MAGIC_NUMBER wraps GDK_PIXBUF_MAGIC_NUMBER
//
// Magic number for #GdkPixdata structures.
const PIXBUF_MAGIC_NUMBER = 1197763408
// PIXDATA_HEADER_LENGTH wraps GDK_PIXDATA_HEADER_LENGTH
//
// The length of a #GdkPixdata structure without the @pixel_data pointer.
//
// Deprecated: (since 2.32.0) 
const PIXDATA_HEADER_LENGTH = 24
// PixdataDumpType wraps GdkPixdataDumpType
//
// An enumeration which is used by gdk_pixdata_to_csource() to
// determine the form of C source to be generated. The three values
// @GDK_PIXDATA_DUMP_PIXDATA_STREAM, @GDK_PIXDATA_DUMP_PIXDATA_STRUCT
// and @GDK_PIXDATA_DUMP_MACROS are mutually exclusive, as are
// @GDK_PIXBUF_DUMP_GTYPES and @GDK_PIXBUF_DUMP_CTYPES. The remaining
// elements are optional flags that can be freely added.
//
// Deprecated: (since 2.32.0) 
type PixdataDumpType C.gint

const (
	// PixdataDumpPixdataStream wraps GDK_PIXDATA_DUMP_PIXDATA_STREAM
	//
	// Generate pixbuf data stream (a single
	//    string containing a serialized #GdkPixdata structure in network byte
	//    order).
	PixdataDumpPixdataStream PixdataDumpType = 0
	// PixdataDumpPixdataStruct wraps GDK_PIXDATA_DUMP_PIXDATA_STRUCT
	//
	// Generate #GdkPixdata structure (needs
	//    the #GdkPixdata structure definition from gdk-pixdata.h).
	PixdataDumpPixdataStruct PixdataDumpType = 1
	// PixdataDumpMacros wraps GDK_PIXDATA_DUMP_MACROS
	//
	// Generate &lt;function&gt;*_ROWSTRIDE&lt;/function&gt;,
	//    &lt;function&gt;*_WIDTH&lt;/function&gt;, &lt;function&gt;*_HEIGHT&lt;/function&gt;,
	//    &lt;function&gt;*_BYTES_PER_PIXEL&lt;/function&gt; and
	//    &lt;function&gt;*_RLE_PIXEL_DATA&lt;/function&gt; or &lt;function&gt;*_PIXEL_DATA&lt;/function&gt;
	//    macro definitions for the image.
	PixdataDumpMacros PixdataDumpType = 2
	// PixdataDumpGTypes wraps GDK_PIXDATA_DUMP_GTYPES
	//
	// Generate GLib data types instead of
	//    standard C data types.
	PixdataDumpGTypes PixdataDumpType = 0
	// PixdataDumpCtypes wraps GDK_PIXDATA_DUMP_CTYPES
	//
	// Generate standard C data types instead of
	//    GLib data types.
	PixdataDumpCtypes PixdataDumpType = 256
	// PixdataDumpStatic wraps GDK_PIXDATA_DUMP_STATIC
	//
	// Generate static symbols.
	PixdataDumpStatic PixdataDumpType = 512
	// PixdataDumpConst wraps GDK_PIXDATA_DUMP_CONST
	//
	// Generate const symbols.
	PixdataDumpConst PixdataDumpType = 1024
	// PixdataDumpRLEDecoder wraps GDK_PIXDATA_DUMP_RLE_DECODER
	//
	// Provide a &lt;function&gt;*_RUN_LENGTH_DECODE(image_buf, rle_data, size, bpp)&lt;/function&gt;
	//    macro definition  to  decode  run-length encoded image data.
	PixdataDumpRLEDecoder PixdataDumpType = 65536
)

// Has returns true if p contains other
func (p PixdataDumpType) Has(other PixdataDumpType) bool {
	return (p & other) == other
}

func (f PixdataDumpType) String() string {
	if f == 0 {
		return "PixdataDumpType(0)"
	}

	var parts []string
	if (f & PixdataDumpPixdataStream) != 0 {
		parts = append(parts, "PixdataDumpPixdataStream")
	}
	if (f & PixdataDumpPixdataStruct) != 0 {
		parts = append(parts, "PixdataDumpPixdataStruct")
	}
	if (f & PixdataDumpMacros) != 0 {
		parts = append(parts, "PixdataDumpMacros")
	}
	if (f & PixdataDumpGTypes) != 0 {
		parts = append(parts, "PixdataDumpGTypes")
	}
	if (f & PixdataDumpCtypes) != 0 {
		parts = append(parts, "PixdataDumpCtypes")
	}
	if (f & PixdataDumpStatic) != 0 {
		parts = append(parts, "PixdataDumpStatic")
	}
	if (f & PixdataDumpConst) != 0 {
		parts = append(parts, "PixdataDumpConst")
	}
	if (f & PixdataDumpRLEDecoder) != 0 {
		parts = append(parts, "PixdataDumpRLEDecoder")
	}
	return "PixdataDumpType(" + strings.Join(parts, "|") + ")"
}

// PixdataType wraps GdkPixdataType
//
// An enumeration containing three sets of flags for a #GdkPixdata struct:
// one for the used colorspace, one for the width of the samples and one
// for the encoding of the pixel data.
//
// Deprecated: (since 2.32.0) 
type PixdataType C.gint

const (
	// PixdataColorTypeRGB wraps GDK_PIXDATA_COLOR_TYPE_RGB
	//
	// each pixel has red, green and blue samples.
	PixdataColorTypeRGB PixdataType = 1
	// PixdataColorTypeRGBA wraps GDK_PIXDATA_COLOR_TYPE_RGBA
	//
	// each pixel has red, green and blue samples
	//    and an alpha value.
	PixdataColorTypeRGBA PixdataType = 2
	// PixdataColorTypeMask wraps GDK_PIXDATA_COLOR_TYPE_MASK
	//
	// mask for the colortype flags of the enum.
	PixdataColorTypeMask PixdataType = 255
	// PixdataSampleWidth8 wraps GDK_PIXDATA_SAMPLE_WIDTH_8
	//
	// each sample has 8 bits.
	PixdataSampleWidth8 PixdataType = 65536
	// PixdataSampleWidthMask wraps GDK_PIXDATA_SAMPLE_WIDTH_MASK
	//
	// mask for the sample width flags of the enum.
	PixdataSampleWidthMask PixdataType = 983040
	// PixdataEncodingRaw wraps GDK_PIXDATA_ENCODING_RAW
	//
	// the pixel data is in raw form.
	PixdataEncodingRaw PixdataType = 16777216
	// PixdataEncodingRLE wraps GDK_PIXDATA_ENCODING_RLE
	//
	// the pixel data is run-length encoded. Runs may
	//    be up to 127 bytes long; their length is stored in a single byte
	//    preceding the pixel data for the run. If a run is constant, its length
	//    byte has the high bit set and the pixel data consists of a single pixel
	//    which must be repeated.
	PixdataEncodingRLE PixdataType = 33554432
	// PixdataEncodingMask wraps GDK_PIXDATA_ENCODING_MASK
	//
	// mask for the encoding flags of the enum.
	PixdataEncodingMask PixdataType = 251658240
)

// Has returns true if p contains other
func (p PixdataType) Has(other PixdataType) bool {
	return (p & other) == other
}

func (f PixdataType) String() string {
	if f == 0 {
		return "PixdataType(0)"
	}

	var parts []string
	if (f & PixdataColorTypeRGB) != 0 {
		parts = append(parts, "PixdataColorTypeRGB")
	}
	if (f & PixdataColorTypeRGBA) != 0 {
		parts = append(parts, "PixdataColorTypeRGBA")
	}
	if (f & PixdataColorTypeMask) != 0 {
		parts = append(parts, "PixdataColorTypeMask")
	}
	if (f & PixdataSampleWidth8) != 0 {
		parts = append(parts, "PixdataSampleWidth8")
	}
	if (f & PixdataSampleWidthMask) != 0 {
		parts = append(parts, "PixdataSampleWidthMask")
	}
	if (f & PixdataEncodingRaw) != 0 {
		parts = append(parts, "PixdataEncodingRaw")
	}
	if (f & PixdataEncodingRLE) != 0 {
		parts = append(parts, "PixdataEncodingRLE")
	}
	if (f & PixdataEncodingMask) != 0 {
		parts = append(parts, "PixdataEncodingMask")
	}
	return "PixdataType(" + strings.Join(parts, "|") + ")"
}

// PixbufFromPixdata wraps gdk_pixbuf_from_pixdata
// 
// The function takes the following parameters:
// 
// 	- pixdata *Pixdata: a #GdkPixdata to convert into a `GdkPixbuf`. 
// 	- copyPixels bool: whether to copy raw pixel data; run-length encoded
//   pixel data is always copied. 
// 
// The function returns the following values:
// 
// 	- goret gdkpixbuf.Pixbuf 
// 	- _goerr error (nullable): an error 
//
// Converts a `GdkPixdata` to a `GdkPixbuf`.
// 
// If `copy_pixels` is `TRUE` or if the pixel data is run-length-encoded,
// the pixel data is copied into newly-allocated memory; otherwise it is
// reused.
//
// Deprecated: (since 2.32.0) Use `GResource` instead.
func PixbufFromPixdata(pixdata *Pixdata, copyPixels bool) (gdkpixbuf.Pixbuf, error) {
	var carg1 *C.GdkPixdata // in, none, converted
	var carg2 C.gboolean    // in
	var cret  *C.GdkPixbuf  // return, full, converted
	var _cerr *C.GError     // out, full, converted, nullable

	carg1 = (*C.GdkPixdata)(UnsafePixdataToGlibNone(pixdata))
	if copyPixels {
		carg2 = C.TRUE
	}

	cret = C.gdk_pixbuf_from_pixdata(carg1, carg2, &_cerr)
	runtime.KeepAlive(pixdata)
	runtime.KeepAlive(copyPixels)

	var goret  gdkpixbuf.Pixbuf
	var _goerr error

	goret = gdkpixbuf.UnsafePixbufFromGlibFull(unsafe.Pointer(cret))
	if _cerr != nil {
		_goerr = glib.UnsafeErrorFromGlibFull(unsafe.Pointer(_cerr))
	}

	return goret, _goerr
}

// Pixdata wraps GdkPixdata
//
// A pixel buffer suitable for serialization and streaming.
// 
// Using `GdkPixdata`, images can be compiled into an application,
// making it unnecessary to refer to external image files at runtime.
// 
// `GdkPixbuf` includes a utility named `gdk-pixbuf-csource`, which
// can be used to convert image files into `GdkPixdata` structures suitable
// for inclusion in C sources. To convert the `GdkPixdata` structures back
// into a `GdkPixbuf`, use `gdk_pixbuf_from_pixdata()`.
//
// Deprecated: (since 2.32.0) `GdkPixdata` should not be used any more. `GResource`
//   should be used to save the original compressed images inside the
//   program's binary
type Pixdata struct {
	*pixdata
}

// pixdata is the struct that's finalized
type pixdata struct {
	native *C.GdkPixdata
}

// UnsafePixdataFromGlibBorrow is used to convert raw C.GdkPixdata pointers to go. This is used by the bindings internally.
func UnsafePixdataFromGlibBorrow(p unsafe.Pointer) *Pixdata {
	return &Pixdata{&pixdata{(*C.GdkPixdata)(p)}}
}

// UnsafePixdataFromGlibNone is used to convert raw C.GdkPixdata pointers to go while taking a reference. This is used by the bindings internally.
func UnsafePixdataFromGlibNone(p unsafe.Pointer) *Pixdata {
	// FIXME: this has no ref function, what should we do here?
	wrapped := UnsafePixdataFromGlibBorrow(p)
	runtime.SetFinalizer(
		wrapped.pixdata,
		func (intern *pixdata) {
			C.free(unsafe.Pointer(intern.native))
		},
	)
	return wrapped
}

// UnsafePixdataFromGlibFull is used to convert raw C.GdkPixdata pointers to go while taking a reference. This is used by the bindings internally.
func UnsafePixdataFromGlibFull(p unsafe.Pointer) *Pixdata {
	wrapped := UnsafePixdataFromGlibBorrow(p)
	runtime.SetFinalizer(
		wrapped.pixdata,
		func (intern *pixdata) {
			C.free(unsafe.Pointer(intern.native))
		},
	)
	return wrapped
}

// UnsafePixdataFree unrefs/frees the underlying resource. This is used by the bindings internally.
// 
// After this is called, no other method on [Pixdata] is expected to work anymore.
func UnsafePixdataFree(p *Pixdata) {
	C.free(unsafe.Pointer(p.native))
}

// UnsafePixdataToGlibNone returns the underlying C pointer. This is used by the bindings internally.
func UnsafePixdataToGlibNone(p *Pixdata) unsafe.Pointer {
	return unsafe.Pointer(p.native)
}

// UnsafePixdataToGlibFull returns the underlying C pointer and gives up ownership.
// This is used by the bindings internally.
func UnsafePixdataToGlibFull(p *Pixdata) unsafe.Pointer {
	runtime.SetFinalizer(p.pixdata, nil)
	_p := unsafe.Pointer(p.native)
	p.native = nil // Pixdata is invalid from here on
	return _p
}
// Deserialize wraps gdk_pixdata_deserialize
// 
// The function takes the following parameters:
// 
// 	- stream []uint8: stream of bytes containing a
//   serialized #GdkPixdata structure. 
// 
// The function returns the following values:
// 
// 	- goret bool 
// 	- _goerr error (nullable): an error 
//
// Deserializes (reconstruct) a #GdkPixdata structure from a byte stream.
// 
// The byte stream consists of a straightforward writeout of the
// `GdkPixdata` fields in network byte order, plus the `pixel_data`
// bytes the structure points to.
// 
// The `pixdata` contents are reconstructed byte by byte and are checked
// for validity.
// 
// This function may fail with `GDK_PIXBUF_ERROR_CORRUPT_IMAGE`
// or `GDK_PIXBUF_ERROR_UNKNOWN_TYPE`.
//
// Deprecated: (since 2.32.0) Use `GResource` instead.
func (pixdata *Pixdata) Deserialize(stream []uint8) (bool, error) {
	var carg0 *C.GdkPixdata // in, none, converted
	var carg1 C.guint       // implicit
	var carg2 *C.guint8     // in, transfer: none, C Pointers: 1, Name: array[guint8], array (inner: *typesystem.CastablePrimitive, length-by: carg1)
	var cret  C.gboolean    // return
	var _cerr *C.GError     // out, full, converted, nullable

	carg0 = (*C.GdkPixdata)(UnsafePixdataToGlibNone(pixdata))
	_ = stream
	_ = carg2
	_ = carg1
	panic("unimplemented conversion of []uint8 (const guint8*)")

	cret = C.gdk_pixdata_deserialize(carg0, carg1, carg2, &_cerr)
	runtime.KeepAlive(pixdata)
	runtime.KeepAlive(stream)

	var goret  bool
	var _goerr error

	if cret != 0 {
		goret = true
	}
	if _cerr != nil {
		_goerr = glib.UnsafeErrorFromGlibFull(unsafe.Pointer(_cerr))
	}

	return goret, _goerr
}

// Serialize wraps gdk_pixdata_serialize
// The function returns the following values:
// 
// 	- streamLengthP uint: location to store the resulting stream length in. 
// 	- goret []uint8 
//
// Serializes a #GdkPixdata structure into a byte stream.
// The byte stream consists of a straightforward writeout of the
// #GdkPixdata fields in network byte order, plus the @pixel_data
// bytes the structure points to.
//
// Deprecated: (since 2.32.0) Use #GResource instead.
func (pixdata *Pixdata) Serialize() (uint, []uint8) {
	var carg0 *C.GdkPixdata // in, none, converted
	var carg1 C.guint       // out, full, casted
	var cret  *C.guint8     // return, transfer: full, C Pointers: 1, Name: array[guint8], scope: , array (inner: *typesystem.CastablePrimitive)

	carg0 = (*C.GdkPixdata)(UnsafePixdataToGlibNone(pixdata))

	cret = C.gdk_pixdata_serialize(carg0, &carg1)
	runtime.KeepAlive(pixdata)

	var streamLengthP uint
	var goret         []uint8

	streamLengthP = uint(carg1)
	_ = goret
	_ = cret
	panic("unimplemented conversion of []uint8 (guint8*)")

	return streamLengthP, goret
}

