// Code generated by girgen. DO NOT EDIT.

package gstvalidate

import (
	"runtime"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gbox"
	"github.com/diamondburned/gotk4/pkg/core/gextras"
	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
	"github.com/diamondburned/gotk4/pkg/gst"
)

// #include <stdlib.h>
// #include <gst/validate/validate.h>
import "C"

//export _gotk4_gstvalidate1_ParseVariableFunc
func _gotk4_gstvalidate1_ParseVariableFunc(arg1 *C.gchar, arg2 *C.double, arg3 C.gpointer) (cret C.int) {
	var fn ParseVariableFunc
	{
		v := gbox.Get(uintptr(arg3))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(ParseVariableFunc)
	}

	var _name string    // out
	var _value *float64 // out

	_name = C.GoString((*C.gchar)(unsafe.Pointer(arg1)))
	_value = (*float64)(unsafe.Pointer(arg2))

	gint := fn(_name, _value)

	var _ int

	cret = C.int(gint)

	return cret
}

//export _gotk4_gstvalidate1_MonitorClass_get_element
func _gotk4_gstvalidate1_MonitorClass_get_element(arg0 *C.GstValidateMonitor) (cret *C.GstElement) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[MonitorOverrides](instance0)
	if overrides.Element == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected MonitorOverrides.Element, got none")
	}

	element := overrides.Element()

	var _ gst.Elementer

	if element != nil {
		cret = (*C.GstElement)(unsafe.Pointer(coreglib.InternObject(element).Native()))
	}

	return cret
}

//export _gotk4_gstvalidate1_MonitorClass_set_media_descriptor
func _gotk4_gstvalidate1_MonitorClass_set_media_descriptor(arg0 *C.GstValidateMonitor, arg1 *C.GstValidateMediaDescriptor) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[MonitorOverrides](instance0)
	if overrides.SetMediaDescriptor == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected MonitorOverrides.SetMediaDescriptor, got none")
	}

	var _mediaDescriptor MediaDescriptorrer // out

	{
		objptr := unsafe.Pointer(arg1)
		if objptr == nil {
			panic("object of type gstvalidate.MediaDescriptorrer is nil")
		}

		object := coreglib.Take(objptr)
		casted := object.WalkCast(func(obj coreglib.Objector) bool {
			_, ok := obj.(MediaDescriptorrer)
			return ok
		})
		rv, ok := casted.(MediaDescriptorrer)
		if !ok {
			panic("no marshaler for " + object.TypeFromInstance().String() + " matching gstvalidate.MediaDescriptorrer")
		}
		_mediaDescriptor = rv
	}

	overrides.SetMediaDescriptor(_mediaDescriptor)
}

//export _gotk4_gstvalidate1_MonitorClass_setup
func _gotk4_gstvalidate1_MonitorClass_setup(arg0 *C.GstValidateMonitor) (cret C.gboolean) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[MonitorOverrides](instance0)
	if overrides.Setup == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected MonitorOverrides.Setup, got none")
	}

	ok := overrides.Setup()

	var _ bool

	if ok {
		cret = C.TRUE
	}

	return cret
}

//export _gotk4_gstvalidate1_OverrideClass_attached
func _gotk4_gstvalidate1_OverrideClass_attached(arg0 *C.GstValidateOverride) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[OverrideOverrides](instance0)
	if overrides.Attached == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected OverrideOverrides.Attached, got none")
	}

	overrides.Attached()
}

//export _gotk4_gstvalidate1_Runner_ConnectReportAdded
func _gotk4_gstvalidate1_Runner_ConnectReportAdded(arg0 C.gpointer, arg1 *C.GstValidateReport, arg2 C.guintptr) {
	var f func(object *Report)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg2))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(object *Report))
	}

	var _object *Report // out

	_object = (*Report)(gextras.NewStructNative(unsafe.Pointer(arg1)))
	C.gst_validate_report_ref(arg1)
	runtime.SetFinalizer(
		gextras.StructIntern(unsafe.Pointer(_object)),
		func(intern *struct{ C unsafe.Pointer }) {
			C.gst_validate_report_unref((*C.GstValidateReport)(intern.C))
		},
	)

	f(_object)
}

//export _gotk4_gstvalidate1_Runner_ConnectStopping
func _gotk4_gstvalidate1_Runner_ConnectStopping(arg0 C.gpointer, arg1 C.guintptr) {
	var f func()
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg1))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func())
	}

	f()
}

//export _gotk4_gstvalidate1_Scenario_ConnectActionDone
func _gotk4_gstvalidate1_Scenario_ConnectActionDone(arg0 C.gpointer, arg1 *C.GstValidateAction, arg2 C.guintptr) {
	var f func(action *Action)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg2))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(action *Action))
	}

	var _action *Action // out

	_action = (*Action)(gextras.NewStructNative(unsafe.Pointer(arg1)))
	C.gst_validate_action_ref(arg1)
	runtime.SetFinalizer(
		gextras.StructIntern(unsafe.Pointer(_action)),
		func(intern *struct{ C unsafe.Pointer }) {
			C.gst_validate_action_unref((*C.GstValidateAction)(intern.C))
		},
	)

	f(_action)
}

//export _gotk4_gstvalidate1_Scenario_ConnectDone
func _gotk4_gstvalidate1_Scenario_ConnectDone(arg0 C.gpointer, arg1 C.guintptr) {
	var f func()
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg1))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func())
	}

	f()
}
