package file

import (
	"fmt"
	"io"
	"os"
	"path"
	"strings"

	"golang.org/x/exp/maps"
)

// Writer is repsonsible of collecting everything that the generators want to output. Pushing more data
// after comitting the Writer is undefined
//
// It keeps track of the file.go but also file_export.go for C exports when needed.
type Writer struct {
	basepath     string
	packageIdent string
	majorVersion int

	filedata
	Exported filedata

	// cflags are only present on the file.go
	cflags map[string]struct{}
	// pkg-config packages
	packages map[string]struct{}
}

func NewWriter(basepath string) *Writer {
	return &Writer{
		basepath:     basepath,
		packageIdent: "", // must be set by user
	}
}

func (w *Writer) SetGoPackageName(ns string, majorVersion int) {
	w.packageIdent = ns
	w.majorVersion = majorVersion
}

func (w *Writer) AddPackage(pkg string) {
	if w.packages == nil {
		w.packages = make(map[string]struct{})
	}

	w.packages[pkg] = struct{}{}
}

func (w *Writer) AddCFlag(flag string) {
	if w.cflags == nil {
		w.cflags = make(map[string]struct{})
	}

	w.cflags[flag] = struct{}{}
}

func (w *Writer) Commit() error {
	err := os.MkdirAll(w.folder(), 0700)

	if err != nil {
		return err
	}

	// TODO: concurrent writing
	if !w.Exported.empty() {
		exportsFile := path.Join(w.folder(), fmt.Sprintf("%s_export.go", w.packageIdent))

		err := w.writeFile(exportsFile, w.exportFile())

		if err != nil {
			return err
		}
	}

	goFile := path.Join(w.folder(), fmt.Sprintf("%s.go", w.packageIdent))

	err = w.writeFile(goFile, w.file())

	if err != nil {
		return err
	}

	return nil
}

func (w *Writer) writeFile(name string, r io.Reader) error {
	f, err := os.OpenFile(name, os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0600)

	if err != nil {
		return err
	}
	defer f.Close()

	_, err = io.Copy(f, r)

	if err != nil {
		return err
	}

	return nil
}
func (w *Writer) folder() string {
	if w.majorVersion > 1 {
		return path.Join(w.basepath, w.packageIdent, fmt.Sprintf("v%d", w.majorVersion))
	}
	return path.Join(w.basepath, w.packageIdent)
}

var str = strings.NewReader
var empty = io.MultiReader() // empty always returns EOF

// file returns a reader that outputs the contents of the file.go file
func (w *Writer) file() io.Reader {
	if w.Exported.empty() {
		panic("unreachable")
	}

	return io.MultiReader(
		w.head(),
		w.goImports.formatted(),
		str("\n"),
		w.cPackagesFormatted(),
		w.cflagsFormatted(),
		w.cIncludes.Reader(),
		w.c(),
		str("import \"C\"\n"),
		str("\n"),
		&w.goContents,
	)
}

// exportFile returns a reader that outputs the contents of the file_export.go file
func (w *Writer) exportFile() io.Reader {
	if w.Exported.empty() {
		panic("unreachable")
	}

	return io.MultiReader(
		w.head(),
		w.Exported.goImports.formatted(),
		str("\n"),
		w.Exported.cIncludes.Reader(),
		w.Exported.c(),
		str("import \"C\"\n"),
		str("\n"),
		&w.Exported.goContents,
	)
}

func (w *Writer) head() io.Reader {
	return io.MultiReader(
		str("// Code generated by girgen. DO NOT EDIT.\n\npackage "),
		str(w.packageIdent),
		str("\n\n"),
	)
}

func (w *Writer) cPackagesFormatted() io.Reader {
	if len(w.packages) == 0 {
		return empty
	}

	return io.MultiReader(
		str("// #cgo pkg-config: "),
		str(strings.Join(maps.Keys(w.packages), " ")),
		str("\n"),
	)
}

func (w *Writer) cflagsFormatted() io.Reader {
	if len(w.cflags) == 0 {
		return empty
	}

	return io.MultiReader(
		str("// #cgo CFLAGS: "),
		str(strings.Join(maps.Keys(w.cflags), " ")),
		str("\n"),
	)
}
