// Code generated by girgen. DO NOT EDIT.

package glib

import (
	"github.com/diamondburned/gotk4/pkg/core/gbox"
)

// #include <glib.h>
import "C"

//export _gotk4_glib2_ClearHandleFunc
func _gotk4_glib2_ClearHandleFunc(carg1 C.guint) (cret C.void) {


	fn(handleId)



	return cret
}

//export _gotk4_glib2_CompareDataFunc
func _gotk4_glib2_CompareDataFunc(carg1 C.gpointer, carg2 C.gpointer, carg3 C.gpointer) (cret C.int) {


	ret := fn(a, b)



	return cret
}

//export _gotk4_glib2_CompareFunc
func _gotk4_glib2_CompareFunc(carg1 C.gpointer, carg2 C.gpointer) (cret C.int) {


	ret := fn(a, b)



	return cret
}

//export _gotk4_glib2_CopyFunc
func _gotk4_glib2_CopyFunc(carg1 C.gpointer, carg2 C.gpointer) (cret C.gpointer) {


	ret := fn(src, data)



	return cret
}

//export _gotk4_glib2_EqualFunc
func _gotk4_glib2_EqualFunc(carg1 C.gpointer, carg2 C.gpointer) (cret C.gboolean) {


	ret := fn(a, b)



	return cret
}

//export _gotk4_glib2_EqualFuncFull
func _gotk4_glib2_EqualFuncFull(carg1 C.gpointer, carg2 C.gpointer, carg3 C.gpointer) (cret C.gboolean) {


	ret := fn(a, b)



	return cret
}

//export _gotk4_glib2_FreeFunc
func _gotk4_glib2_FreeFunc(carg1 C.gpointer) (cret C.void) {


	fn(data)



	return cret
}

//export _gotk4_glib2_Func
func _gotk4_glib2_Func(carg1 C.gpointer, carg2 C.gpointer) (cret C.void) {


	fn(data)



	return cret
}

//export _gotk4_glib2_HFunc
func _gotk4_glib2_HFunc(carg1 C.gpointer, carg2 C.gpointer, carg3 C.gpointer) (cret C.void) {


	fn(key, value)



	return cret
}

//export _gotk4_glib2_HRFunc
func _gotk4_glib2_HRFunc(carg1 C.gpointer, carg2 C.gpointer, carg3 C.gpointer) (cret C.gboolean) {


	ret := fn(key, value)



	return cret
}

//export _gotk4_glib2_HashFunc
func _gotk4_glib2_HashFunc(carg1 C.gpointer) (cret C.guint) {


	ret := fn(key)



	return cret
}

//export _gotk4_glib2_OptionArgFunc
func _gotk4_glib2_OptionArgFunc(carg1 *C.gchar, carg2 *C.gchar, carg3 C.gpointer, _cerr *C.GError) (cret C.gboolean) {


	ret, _goerr := fn(optionName, value, data)



	return cret
}

//export _gotk4_glib2_PrintFunc
func _gotk4_glib2_PrintFunc(carg1 *C.gchar) (cret C.void) {


	fn(str)



	return cret
}

//export _gotk4_glib2_SourceDummyMarshal
func _gotk4_glib2_SourceDummyMarshal() (cret C.void) {


	fn()



	return cret
}

//export _gotk4_glib2_SourceFunc
func _gotk4_glib2_SourceFunc(carg1 C.gpointer) (cret C.gboolean) {


	ret := fn()



	return cret
}

//export _gotk4_glib2_SourceOnceFunc
func _gotk4_glib2_SourceOnceFunc(carg1 C.gpointer) (cret C.void) {


	fn()



	return cret
}

//export _gotk4_glib2_SpawnChildSetupFunc
func _gotk4_glib2_SpawnChildSetupFunc(carg1 C.gpointer) (cret C.void) {


	fn(data)



	return cret
}

//export _gotk4_glib2_TranslateFunc
func _gotk4_glib2_TranslateFunc(carg1 *C.gchar, carg2 C.gpointer) (cret *C.gchar) {


	ret := fn(str, data)



	return cret
}

//export _gotk4_glib2_TraverseFunc
func _gotk4_glib2_TraverseFunc(carg1 C.gpointer, carg2 C.gpointer, carg3 C.gpointer) (cret C.gboolean) {


	ret := fn(key, value, data)



	return cret
}

//export _gotk4_glib2_VoidFunc
func _gotk4_glib2_VoidFunc() (cret C.void) {


	fn()



	return cret
}

//export _gotk4_glib2_ChildWatchFunc
func _gotk4_glib2_ChildWatchFunc(carg1 C.GPid, carg2 C.int, carg3 C.gpointer) (cret C.void) {


	fn(pid, waitStatus)



	return cret
}

