// Code generated by girgen for GdkPixbuf-2. DO NOT EDIT.

package gdkpixbuf

import (
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/classdata"
	"github.com/diamondburned/gotk4/pkg/core/userdata"
	"github.com/diamondburned/gotk4/pkg/glib/v2"
)

// #include <gdk-pixbuf/gdk-pixbuf.h>
import "C"

//export _gotk4_gdkpixbuf2_PixbufModuleSizeFunc
func _gotk4_gdkpixbuf2_PixbufModuleSizeFunc(carg1 *C.gint, carg2 *C.gint, carg3 C.gpointer) {
	var fn PixbufModuleSizeFunc
	{
		v := userdata.Load(unsafe.Pointer(carg3))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(PixbufModuleSizeFunc)
	}

	var width  *int // in, transfer: none, C Pointers: 1, Name: gint
	var height *int // in, transfer: none, C Pointers: 1, Name: gint

	_ = width
	_ = carg1
	panic("unimplemented conversion of *int (gint*)")
	_ = height
	_ = carg2
	panic("unimplemented conversion of *int (gint*)")

	fn(width, height)
}

//export _gotk4_gdkpixbuf2_PixbufModuleUpdatedFunc
func _gotk4_gdkpixbuf2_PixbufModuleUpdatedFunc(carg1 *C.GdkPixbuf, carg2 C.int, carg3 C.int, carg4 C.int, carg5 C.int, carg6 C.gpointer) {
	var fn PixbufModuleUpdatedFunc
	{
		v := userdata.Load(unsafe.Pointer(carg6))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(PixbufModuleUpdatedFunc)
	}

	var pixbuf Pixbuf // in, none, converted
	var x      int    // in, none, casted, casted C.gint
	var y      int    // in, none, casted, casted C.gint
	var width  int    // in, none, casted, casted C.gint
	var height int    // in, none, casted, casted C.gint

	pixbuf = UnsafePixbufFromGlibNone(unsafe.Pointer(carg1))
	x = int(carg2)
	y = int(carg3)
	width = int(carg4)
	height = int(carg5)

	fn(pixbuf, x, y, width, height)
}

//export _gotk4_gdkpixbuf2_PixbufSaveFunc
func _gotk4_gdkpixbuf2_PixbufSaveFunc(carg1 *C.gchar, carg2 C.gsize, carg3 **C.GError, carg4 C.gpointer) (cret C.gboolean) {
	var fn PixbufSaveFunc
	{
		v := userdata.Load(unsafe.Pointer(carg4))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(PixbufSaveFunc)
	}

	var buf   string // in, transfer: none, C Pointers: 1, Name: array[unknown], array (inner: <nil>, length-by: carg2)
	var goret bool   // return
	var err   error  // out, full, converted

	_ = buf
	_ = carg1
	_ = carg2
	panic("unimplemented conversion of string (const gchar*)")

	goret, err = fn(buf)

	if goret {
		cret = C.TRUE
	}
	*carg3 = (*C.GError)(glib.UnsafeErrorToGlibFull(err))

	return cret
}

//export _gotk4_gdkpixbuf2_PixbufLoader_area_prepared
func _gotk4_gdkpixbuf2_PixbufLoader_area_prepared(carg0 *C.GdkPixbufLoader) {
	var fn func(carg0 *C.GdkPixbufLoader)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_gotk4_gdkpixbuf2_PixbufLoader_area_prepared").(func(carg0 *C.GdkPixbufLoader))
		if fn == nil {
			panic("_gotk4_gdkpixbuf2_PixbufLoader_area_prepared: no function pointer found")
		}
	}
	fn(carg0)
}

//export _gotk4_gdkpixbuf2_PixbufLoader_area_updated
func _gotk4_gdkpixbuf2_PixbufLoader_area_updated(carg0 *C.GdkPixbufLoader, carg1 C.int, carg2 C.int, carg3 C.int, carg4 C.int) {
	var fn func(carg0 *C.GdkPixbufLoader, carg1 C.int, carg2 C.int, carg3 C.int, carg4 C.int)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_gotk4_gdkpixbuf2_PixbufLoader_area_updated").(func(carg0 *C.GdkPixbufLoader, carg1 C.int, carg2 C.int, carg3 C.int, carg4 C.int))
		if fn == nil {
			panic("_gotk4_gdkpixbuf2_PixbufLoader_area_updated: no function pointer found")
		}
	}
	fn(carg0, carg1, carg2, carg3, carg4)
}

//export _gotk4_gdkpixbuf2_PixbufLoader_closed
func _gotk4_gdkpixbuf2_PixbufLoader_closed(carg0 *C.GdkPixbufLoader) {
	var fn func(carg0 *C.GdkPixbufLoader)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_gotk4_gdkpixbuf2_PixbufLoader_closed").(func(carg0 *C.GdkPixbufLoader))
		if fn == nil {
			panic("_gotk4_gdkpixbuf2_PixbufLoader_closed: no function pointer found")
		}
	}
	fn(carg0)
}

//export _gotk4_gdkpixbuf2_PixbufLoader_size_prepared
func _gotk4_gdkpixbuf2_PixbufLoader_size_prepared(carg0 *C.GdkPixbufLoader, carg1 C.int, carg2 C.int) {
	var fn func(carg0 *C.GdkPixbufLoader, carg1 C.int, carg2 C.int)
	{
		fn = classdata.LoadVirtualMethodFromInstance(unsafe.Pointer(carg0), "_gotk4_gdkpixbuf2_PixbufLoader_size_prepared").(func(carg0 *C.GdkPixbufLoader, carg1 C.int, carg2 C.int))
		if fn == nil {
			panic("_gotk4_gdkpixbuf2_PixbufLoader_size_prepared: no function pointer found")
		}
	}
	fn(carg0, carg1, carg2)
}

