// Code generated by girgen. DO NOT EDIT.

package gdkpixbuf

import (
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gbox"
	"github.com/diamondburned/gotk4/pkg/glib/v2"
)

// #include <gdk-pixbuf/gdk-pixbuf.h>
import "C"

//export _gotk4_gdkpixbuf2_PixbufModuleSizeFunc
func _gotk4_gdkpixbuf2_PixbufModuleSizeFunc(carg1 *C.gint, carg2 *C.gint, carg3 C.gpointer) {
	var fn PixbufModuleSizeFunc
	{
		v := gbox.Get(uintptr(carg3))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(PixbufModuleSizeFunc)
	}

	var width  *int // in, transfer: none, C Pointers: 1, Name: gint
	var height *int // in, transfer: none, C Pointers: 1, Name: gint

	_ = width
	_ = carg1
	panic("unimplemented conversion of *int (gint*)")
	_ = height
	_ = carg2
	panic("unimplemented conversion of *int (gint*)")

	fn(width, height)
}

//export _gotk4_gdkpixbuf2_PixbufModuleUpdatedFunc
func _gotk4_gdkpixbuf2_PixbufModuleUpdatedFunc(carg1 *C.GdkPixbuf, carg2 C.int, carg3 C.int, carg4 C.int, carg5 C.int, carg6 C.gpointer) {
	var fn PixbufModuleUpdatedFunc
	{
		v := gbox.Get(uintptr(carg6))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(PixbufModuleUpdatedFunc)
	}

	var pixbuf Pixbuf // in, none, converted
	var x      int    // in, none, casted, casted C.gint
	var y      int    // in, none, casted, casted C.gint
	var width  int    // in, none, casted, casted C.gint
	var height int    // in, none, casted, casted C.gint

	pixbuf = UnsafePixbufFromGlibNone(unsafe.Pointer(carg1))
	x = int(carg2)
	y = int(carg3)
	width = int(carg4)
	height = int(carg5)

	fn(pixbuf, x, y, width, height)
}

//export _gotk4_gdkpixbuf2_PixbufSaveFunc
func _gotk4_gdkpixbuf2_PixbufSaveFunc(carg1 *C.gchar, carg2 C.gsize, carg3 **C.GError, carg4 C.gpointer) (cret C.gboolean) {
	var fn PixbufSaveFunc
	{
		v := gbox.Get(uintptr(carg4))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(PixbufSaveFunc)
	}

	var buf   string // in, transfer: none, C Pointers: 1, Name: array[unknown], array (inner: <nil>, length-by: carg2)
	var goret bool   // return
	var err   error  // out, full, converted

	_ = buf
	_ = carg1
	_ = carg2
	panic("unimplemented conversion of string (const gchar*)")

	goret, err = fn(buf)

	if goret {
		cret = C.TRUE
	}
	*carg3 = (*C.GError)(glib.UnsafeErrorToGlibFull(err))

	return cret
}

