// Code generated by girgen. DO NOT EDIT.

package gstinsertbin

import (
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gbox"
	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
	"github.com/diamondburned/gotk4/pkg/gst"
)

// #include <stdlib.h>
// #include <gst/insertbin/gstinsertbin.h>
import "C"

//export _gotk4_gstinsertbin1_InsertBinCallback
func _gotk4_gstinsertbin1_InsertBinCallback(arg1 *C.GstInsertBin, arg2 *C.GstElement, arg3 C.gboolean, arg4 C.gpointer) {
	var fn InsertBinCallback
	{
		v := gbox.Get(uintptr(arg4))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(InsertBinCallback)
	}

	var _insertbin *InsertBin  // out
	var _element gst.Elementer // out
	var _success bool          // out

	_insertbin = wrapInsertBin(coreglib.Take(unsafe.Pointer(arg1)))
	{
		objptr := unsafe.Pointer(arg2)
		if objptr == nil {
			panic("object of type gst.Elementer is nil")
		}

		object := coreglib.Take(objptr)
		casted := object.WalkCast(func(obj coreglib.Objector) bool {
			_, ok := obj.(gst.Elementer)
			return ok
		})
		rv, ok := casted.(gst.Elementer)
		if !ok {
			panic("no marshaler for " + object.TypeFromInstance().String() + " matching gst.Elementer")
		}
		_element = rv
	}
	if arg3 != 0 {
		_success = true
	}

	fn(_insertbin, _element, _success)
}

//export _gotk4_gstinsertbin1_InsertBin_ConnectAppend
func _gotk4_gstinsertbin1_InsertBin_ConnectAppend(arg0 C.gpointer, arg1 *C.GstElement, arg2 C.gpointer, arg3 C.gpointer, arg4 C.guintptr) {
	var f func(callback gst.Elementer, userData, userData2 unsafe.Pointer)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg4))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(callback gst.Elementer, userData, userData2 unsafe.Pointer))
	}

	var _callback gst.Elementer   // out
	var _userData unsafe.Pointer  // out
	var _userData2 unsafe.Pointer // out

	{
		objptr := unsafe.Pointer(arg1)
		if objptr == nil {
			panic("object of type gst.Elementer is nil")
		}

		object := coreglib.Take(objptr)
		casted := object.WalkCast(func(obj coreglib.Objector) bool {
			_, ok := obj.(gst.Elementer)
			return ok
		})
		rv, ok := casted.(gst.Elementer)
		if !ok {
			panic("no marshaler for " + object.TypeFromInstance().String() + " matching gst.Elementer")
		}
		_callback = rv
	}
	_userData = (unsafe.Pointer)(unsafe.Pointer(arg2))
	_userData2 = (unsafe.Pointer)(unsafe.Pointer(arg3))

	f(_callback, _userData, _userData2)
}

//export _gotk4_gstinsertbin1_InsertBin_ConnectInsertAfter
func _gotk4_gstinsertbin1_InsertBin_ConnectInsertAfter(arg0 C.gpointer, arg1 *C.GstElement, arg2 *C.GstElement, arg3 C.gpointer, arg4 C.gpointer, arg5 C.guintptr) {
	var f func(sibling, callback gst.Elementer, userData, userData2 unsafe.Pointer)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg5))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(sibling, callback gst.Elementer, userData, userData2 unsafe.Pointer))
	}

	var _sibling gst.Elementer    // out
	var _callback gst.Elementer   // out
	var _userData unsafe.Pointer  // out
	var _userData2 unsafe.Pointer // out

	{
		objptr := unsafe.Pointer(arg1)
		if objptr == nil {
			panic("object of type gst.Elementer is nil")
		}

		object := coreglib.Take(objptr)
		casted := object.WalkCast(func(obj coreglib.Objector) bool {
			_, ok := obj.(gst.Elementer)
			return ok
		})
		rv, ok := casted.(gst.Elementer)
		if !ok {
			panic("no marshaler for " + object.TypeFromInstance().String() + " matching gst.Elementer")
		}
		_sibling = rv
	}
	{
		objptr := unsafe.Pointer(arg2)
		if objptr == nil {
			panic("object of type gst.Elementer is nil")
		}

		object := coreglib.Take(objptr)
		casted := object.WalkCast(func(obj coreglib.Objector) bool {
			_, ok := obj.(gst.Elementer)
			return ok
		})
		rv, ok := casted.(gst.Elementer)
		if !ok {
			panic("no marshaler for " + object.TypeFromInstance().String() + " matching gst.Elementer")
		}
		_callback = rv
	}
	_userData = (unsafe.Pointer)(unsafe.Pointer(arg3))
	_userData2 = (unsafe.Pointer)(unsafe.Pointer(arg4))

	f(_sibling, _callback, _userData, _userData2)
}

//export _gotk4_gstinsertbin1_InsertBin_ConnectInsertBefore
func _gotk4_gstinsertbin1_InsertBin_ConnectInsertBefore(arg0 C.gpointer, arg1 *C.GstElement, arg2 *C.GstElement, arg3 C.gpointer, arg4 C.gpointer, arg5 C.guintptr) {
	var f func(sibling, callback gst.Elementer, userData, userData2 unsafe.Pointer)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg5))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(sibling, callback gst.Elementer, userData, userData2 unsafe.Pointer))
	}

	var _sibling gst.Elementer    // out
	var _callback gst.Elementer   // out
	var _userData unsafe.Pointer  // out
	var _userData2 unsafe.Pointer // out

	{
		objptr := unsafe.Pointer(arg1)
		if objptr == nil {
			panic("object of type gst.Elementer is nil")
		}

		object := coreglib.Take(objptr)
		casted := object.WalkCast(func(obj coreglib.Objector) bool {
			_, ok := obj.(gst.Elementer)
			return ok
		})
		rv, ok := casted.(gst.Elementer)
		if !ok {
			panic("no marshaler for " + object.TypeFromInstance().String() + " matching gst.Elementer")
		}
		_sibling = rv
	}
	{
		objptr := unsafe.Pointer(arg2)
		if objptr == nil {
			panic("object of type gst.Elementer is nil")
		}

		object := coreglib.Take(objptr)
		casted := object.WalkCast(func(obj coreglib.Objector) bool {
			_, ok := obj.(gst.Elementer)
			return ok
		})
		rv, ok := casted.(gst.Elementer)
		if !ok {
			panic("no marshaler for " + object.TypeFromInstance().String() + " matching gst.Elementer")
		}
		_callback = rv
	}
	_userData = (unsafe.Pointer)(unsafe.Pointer(arg3))
	_userData2 = (unsafe.Pointer)(unsafe.Pointer(arg4))

	f(_sibling, _callback, _userData, _userData2)
}

//export _gotk4_gstinsertbin1_InsertBin_ConnectPrepend
func _gotk4_gstinsertbin1_InsertBin_ConnectPrepend(arg0 C.gpointer, arg1 *C.GstElement, arg2 C.gpointer, arg3 C.gpointer, arg4 C.guintptr) {
	var f func(callback gst.Elementer, userData, userData2 unsafe.Pointer)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg4))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(callback gst.Elementer, userData, userData2 unsafe.Pointer))
	}

	var _callback gst.Elementer   // out
	var _userData unsafe.Pointer  // out
	var _userData2 unsafe.Pointer // out

	{
		objptr := unsafe.Pointer(arg1)
		if objptr == nil {
			panic("object of type gst.Elementer is nil")
		}

		object := coreglib.Take(objptr)
		casted := object.WalkCast(func(obj coreglib.Objector) bool {
			_, ok := obj.(gst.Elementer)
			return ok
		})
		rv, ok := casted.(gst.Elementer)
		if !ok {
			panic("no marshaler for " + object.TypeFromInstance().String() + " matching gst.Elementer")
		}
		_callback = rv
	}
	_userData = (unsafe.Pointer)(unsafe.Pointer(arg2))
	_userData2 = (unsafe.Pointer)(unsafe.Pointer(arg3))

	f(_callback, _userData, _userData2)
}

//export _gotk4_gstinsertbin1_InsertBin_ConnectRemove
func _gotk4_gstinsertbin1_InsertBin_ConnectRemove(arg0 C.gpointer, arg1 *C.GstElement, arg2 C.gpointer, arg3 C.gpointer, arg4 C.guintptr) {
	var f func(callback gst.Elementer, userData, userData2 unsafe.Pointer)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg4))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(callback gst.Elementer, userData, userData2 unsafe.Pointer))
	}

	var _callback gst.Elementer   // out
	var _userData unsafe.Pointer  // out
	var _userData2 unsafe.Pointer // out

	{
		objptr := unsafe.Pointer(arg1)
		if objptr == nil {
			panic("object of type gst.Elementer is nil")
		}

		object := coreglib.Take(objptr)
		casted := object.WalkCast(func(obj coreglib.Objector) bool {
			_, ok := obj.(gst.Elementer)
			return ok
		})
		rv, ok := casted.(gst.Elementer)
		if !ok {
			panic("no marshaler for " + object.TypeFromInstance().String() + " matching gst.Elementer")
		}
		_callback = rv
	}
	_userData = (unsafe.Pointer)(unsafe.Pointer(arg2))
	_userData2 = (unsafe.Pointer)(unsafe.Pointer(arg3))

	f(_callback, _userData, _userData2)
}
