// Code generated by girgen. DO NOT EDIT.

package gstinsertbin

import (
	"runtime"
	_ "runtime/cgo"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gbox"
	"github.com/diamondburned/gotk4/pkg/core/gextras"
	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
	"github.com/diamondburned/gotk4/pkg/gst"
)

// #cgo pkg-config: gstreamer-insertbin-1.0 gstreamer-analytics-1.0
// #cgo CFLAGS: -Wno-deprecated-declarations
// #include <stdlib.h>
// #include <glib-object.h>
// #include <gst/insertbin/gstinsertbin.h>
// extern void _gotk4_gstinsertbin1_InsertBin_ConnectRemove(gpointer, GstElement*, gpointer, gpointer, guintptr);
// extern void _gotk4_gstinsertbin1_InsertBin_ConnectPrepend(gpointer, GstElement*, gpointer, gpointer, guintptr);
// extern void _gotk4_gstinsertbin1_InsertBin_ConnectInsertBefore(gpointer, GstElement*, GstElement*, gpointer, gpointer, guintptr);
// extern void _gotk4_gstinsertbin1_InsertBin_ConnectInsertAfter(gpointer, GstElement*, GstElement*, gpointer, gpointer, guintptr);
// extern void _gotk4_gstinsertbin1_InsertBin_ConnectAppend(gpointer, GstElement*, gpointer, gpointer, guintptr);
// extern void _gotk4_gstinsertbin1_InsertBinCallback(GstInsertBin*, GstElement*, gboolean, gpointer);
import "C"

// GType values.
var (
	GTypeInsertBin = coreglib.Type(C.gst_insert_bin_get_type())
)

func init() {
	coreglib.RegisterGValueMarshalers([]coreglib.TypeMarshaler{
		coreglib.TypeMarshaler{T: GTypeInsertBin, F: marshalInsertBin},
	})
}

// InsertBinCallback: this is the prototype of callbacks to be called when
// the operation completes. It could be called at any time, including as a
// re-entrant call while the operation is requested.
type InsertBinCallback func(insertbin *InsertBin, element gst.Elementer, success bool)

// InsertBinOverrides contains methods that are overridable.
type InsertBinOverrides struct {
}

func defaultInsertBinOverrides(v *InsertBin) InsertBinOverrides {
	return InsertBinOverrides{}
}

// InsertBin: this element is a Bin that has a single source and sink pad.
// It allows the user (the application) to easily add and remove filter-like
// element (that has a single source and sink pad), to the pipeline while it is
// running. It features a fully asynchronous API inspired by GLib's GAsyncResult
// based APIs.
//
// Each operation (addition or removal) can take a callback, this callback is
// guaranteed to be called. Unlike GIO, there is no guarantee about where this
// callback will be called from, it could be called before the action returns or
// it could be called later from another thread. The signature of this callback
// GstInsertBinCallback().
//
// Apart from the library API, since 1.24 insertbin can also be found in the
// registry:
//
// ` C GstElement *pipeline, *insertbin, *videoflip;
//
//	gst_init (NULL, NULL);
//	pipeline =
//	    gst_parse_launch ("videotestsrc ! insertbin name=i ! autovideosink",
//	    NULL);
//
//	...
//
//	insertbin = gst_bin_get_by_name (GST_BIN (pipeline), "i");
//	videoflip = gst_element_factory_make ("videoflip", NULL);
//
//	...
//
//	g_object_set (videoflip, "method", 1, NULL);
//	g_signal_emit_by_name (insertbin, "append", videoflip, NULL, NULL);
//
//	...
//
// `
type InsertBin struct {
	_ [0]func() // equal guard
	gst.Bin
}

var (
	_ gst.Elementer = (*InsertBin)(nil)
)

func init() {
	coreglib.RegisterClassInfo[*InsertBin, *InsertBinClass, InsertBinOverrides](
		GTypeInsertBin,
		initInsertBinClass,
		wrapInsertBin,
		defaultInsertBinOverrides,
	)
}

func initInsertBinClass(gclass unsafe.Pointer, overrides InsertBinOverrides, classInitFunc func(*InsertBinClass)) {
	if classInitFunc != nil {
		class := (*InsertBinClass)(gextras.NewStructNative(gclass))
		classInitFunc(class)
	}
}

func wrapInsertBin(obj *coreglib.Object) *InsertBin {
	return &InsertBin{
		Bin: gst.Bin{
			Element: gst.Element{
				GstObject: gst.GstObject{
					InitiallyUnowned: coreglib.InitiallyUnowned{
						Object: obj,
					},
				},
			},
			ChildProxy: gst.ChildProxy{
				Object: obj,
			},
		},
	}
}

func marshalInsertBin(p uintptr) (interface{}, error) {
	return wrapInsertBin(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// ConnectAppend: this action signal adds the filter like element after any
// other element in the bin.
//
// Same as gst_insert_bin_append().
func (self *InsertBin) ConnectAppend(f func(callback gst.Elementer, userData, userData2 unsafe.Pointer)) coreglib.SignalHandle {
	return coreglib.ConnectGeneratedClosure(self, "append", false, unsafe.Pointer(C._gotk4_gstinsertbin1_InsertBin_ConnectAppend), f)
}

// ConnectInsertAfter: this action signal adds the filter like element after the
// sibling element in the bin. element in the bin.
//
// Same as gst_insert_bin_insert_after().
func (self *InsertBin) ConnectInsertAfter(f func(sibling, callback gst.Elementer, userData, userData2 unsafe.Pointer)) coreglib.SignalHandle {
	return coreglib.ConnectGeneratedClosure(self, "insert-after", false, unsafe.Pointer(C._gotk4_gstinsertbin1_InsertBin_ConnectInsertAfter), f)
}

// ConnectInsertBefore: this action signal adds the filter like element before
// the sibling element in the bin.
//
// Same as gst_insert_bin_insert_before().
func (self *InsertBin) ConnectInsertBefore(f func(sibling, callback gst.Elementer, userData, userData2 unsafe.Pointer)) coreglib.SignalHandle {
	return coreglib.ConnectGeneratedClosure(self, "insert-before", false, unsafe.Pointer(C._gotk4_gstinsertbin1_InsertBin_ConnectInsertBefore), f)
}

// ConnectPrepend: this action signal adds the filter like element before any
// other element in the bin.
//
// Same as gst_insert_bin_prepend().
func (self *InsertBin) ConnectPrepend(f func(callback gst.Elementer, userData, userData2 unsafe.Pointer)) coreglib.SignalHandle {
	return coreglib.ConnectGeneratedClosure(self, "prepend", false, unsafe.Pointer(C._gotk4_gstinsertbin1_InsertBin_ConnectPrepend), f)
}

// ConnectRemove: this action signal removed the filter like element from the
// bin.
//
// Same as gst_insert_bin_remove().
func (self *InsertBin) ConnectRemove(f func(callback gst.Elementer, userData, userData2 unsafe.Pointer)) coreglib.SignalHandle {
	return coreglib.ConnectGeneratedClosure(self, "remove", false, unsafe.Pointer(C._gotk4_gstinsertbin1_InsertBin_ConnectRemove), f)
}

// NewInsertBin creates a new InsertBin.
//
// The function takes the following parameters:
//
//   - name (optional) of the new InsertBin element (or NULL).
//
// The function returns the following values:
//
//   - insertBin: new InsertBin.
func NewInsertBin(name string) *InsertBin {
	var _arg1 *C.gchar      // out
	var _cret *C.GstElement // in

	if name != "" {
		_arg1 = (*C.gchar)(unsafe.Pointer(C.CString(name)))
		defer C.free(unsafe.Pointer(_arg1))
	}

	_cret = C.gst_insert_bin_new(_arg1)
	runtime.KeepAlive(name)

	var _insertBin *InsertBin // out

	_insertBin = wrapInsertBin(coreglib.Take(unsafe.Pointer(_cret)))

	return _insertBin
}

// Append: this action signal adds the filter like element after any other
// element in the bin.
//
// Same as the InsertBin::append signal.
//
// The function takes the following parameters:
//
//   - element to add.
//   - callback to call when the element has been added or not, or NULL.
func (self *InsertBin) Append(element gst.Elementer, callback InsertBinCallback) {
	var _arg0 *C.GstInsertBin        // out
	var _arg1 *C.GstElement          // out
	var _arg2 C.GstInsertBinCallback // out
	var _arg3 C.gpointer

	_arg0 = (*C.GstInsertBin)(unsafe.Pointer(coreglib.InternObject(self).Native()))
	_arg1 = (*C.GstElement)(unsafe.Pointer(coreglib.InternObject(element).Native()))
	_arg2 = (*[0]byte)(C._gotk4_gstinsertbin1_InsertBinCallback)
	_arg3 = C.gpointer(gbox.AssignOnce(callback))

	C.gst_insert_bin_append(_arg0, _arg1, _arg2, _arg3)
	runtime.KeepAlive(self)
	runtime.KeepAlive(element)
	runtime.KeepAlive(callback)
}

// InsertAfter: this action signal adds the filter like element after the
// sibling element in the bin.
//
// Same as the InsertBin::insert-after signal.
//
// The function takes the following parameters:
//
//   - element to add.
//   - sibling to add element after.
//   - callback to call when the element has been added or not, or NULL.
func (self *InsertBin) InsertAfter(element, sibling gst.Elementer, callback InsertBinCallback) {
	var _arg0 *C.GstInsertBin        // out
	var _arg1 *C.GstElement          // out
	var _arg2 *C.GstElement          // out
	var _arg3 C.GstInsertBinCallback // out
	var _arg4 C.gpointer

	_arg0 = (*C.GstInsertBin)(unsafe.Pointer(coreglib.InternObject(self).Native()))
	_arg1 = (*C.GstElement)(unsafe.Pointer(coreglib.InternObject(element).Native()))
	_arg2 = (*C.GstElement)(unsafe.Pointer(coreglib.InternObject(sibling).Native()))
	_arg3 = (*[0]byte)(C._gotk4_gstinsertbin1_InsertBinCallback)
	_arg4 = C.gpointer(gbox.AssignOnce(callback))

	C.gst_insert_bin_insert_after(_arg0, _arg1, _arg2, _arg3, _arg4)
	runtime.KeepAlive(self)
	runtime.KeepAlive(element)
	runtime.KeepAlive(sibling)
	runtime.KeepAlive(callback)
}

// InsertBefore: this action signal adds the filter like element before the
// sibling element in the bin.
//
// Same as the InsertBin::insert-before signal.
//
// The function takes the following parameters:
//
//   - element to add.
//   - sibling to add element before.
//   - callback to call when the element has been added or not, or NULL.
func (self *InsertBin) InsertBefore(element, sibling gst.Elementer, callback InsertBinCallback) {
	var _arg0 *C.GstInsertBin        // out
	var _arg1 *C.GstElement          // out
	var _arg2 *C.GstElement          // out
	var _arg3 C.GstInsertBinCallback // out
	var _arg4 C.gpointer

	_arg0 = (*C.GstInsertBin)(unsafe.Pointer(coreglib.InternObject(self).Native()))
	_arg1 = (*C.GstElement)(unsafe.Pointer(coreglib.InternObject(element).Native()))
	_arg2 = (*C.GstElement)(unsafe.Pointer(coreglib.InternObject(sibling).Native()))
	_arg3 = (*[0]byte)(C._gotk4_gstinsertbin1_InsertBinCallback)
	_arg4 = C.gpointer(gbox.AssignOnce(callback))

	C.gst_insert_bin_insert_before(_arg0, _arg1, _arg2, _arg3, _arg4)
	runtime.KeepAlive(self)
	runtime.KeepAlive(element)
	runtime.KeepAlive(sibling)
	runtime.KeepAlive(callback)
}

// Prepend: this action signal adds the filter like element before any other
// element in the bin.
//
// Same as the InsertBin::prepend signal.
//
// The function takes the following parameters:
//
//   - element to add.
//   - callback to call when the element has been added or not, or NULL.
func (self *InsertBin) Prepend(element gst.Elementer, callback InsertBinCallback) {
	var _arg0 *C.GstInsertBin        // out
	var _arg1 *C.GstElement          // out
	var _arg2 C.GstInsertBinCallback // out
	var _arg3 C.gpointer

	_arg0 = (*C.GstInsertBin)(unsafe.Pointer(coreglib.InternObject(self).Native()))
	_arg1 = (*C.GstElement)(unsafe.Pointer(coreglib.InternObject(element).Native()))
	_arg2 = (*[0]byte)(C._gotk4_gstinsertbin1_InsertBinCallback)
	_arg3 = C.gpointer(gbox.AssignOnce(callback))

	C.gst_insert_bin_prepend(_arg0, _arg1, _arg2, _arg3)
	runtime.KeepAlive(self)
	runtime.KeepAlive(element)
	runtime.KeepAlive(callback)
}

// Remove: this action signal removed the filter like element from the bin.
//
// Same as the InsertBin::remove signal.
//
// The function takes the following parameters:
//
//   - element to remove.
//   - callback to call when the element has been removed or not, or NULL.
func (self *InsertBin) Remove(element gst.Elementer, callback InsertBinCallback) {
	var _arg0 *C.GstInsertBin        // out
	var _arg1 *C.GstElement          // out
	var _arg2 C.GstInsertBinCallback // out
	var _arg3 C.gpointer

	_arg0 = (*C.GstInsertBin)(unsafe.Pointer(coreglib.InternObject(self).Native()))
	_arg1 = (*C.GstElement)(unsafe.Pointer(coreglib.InternObject(element).Native()))
	_arg2 = (*[0]byte)(C._gotk4_gstinsertbin1_InsertBinCallback)
	_arg3 = C.gpointer(gbox.AssignOnce(callback))

	C.gst_insert_bin_remove(_arg0, _arg1, _arg2, _arg3)
	runtime.KeepAlive(self)
	runtime.KeepAlive(element)
	runtime.KeepAlive(callback)
}

// InsertBinClass: object class structure.
//
// An instance of this type is always passed by reference.
type InsertBinClass struct {
	*insertBinClass
}

// insertBinClass is the struct that's finalized.
type insertBinClass struct {
	native *C.GstInsertBinClass
}

func (i *InsertBinClass) ParentClass() *gst.BinClass {
	valptr := &i.native.parent_class
	var _v *gst.BinClass // out
	_v = (*gst.BinClass)(gextras.NewStructNative(unsafe.Pointer(valptr)))
	return _v
}
