// Code generated by girgen. DO NOT EDIT.

package gstbadaudio

import (
	"runtime"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gextras"
	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
	"github.com/diamondburned/gotk4/pkg/gst"
)

// #include <stdlib.h>
import "C"

//export _gotk4_gstbadaudio1_NonstreamAudioDecoderClass_decide_allocation
func _gotk4_gstbadaudio1_NonstreamAudioDecoderClass_decide_allocation(arg0 *C.GstNonstreamAudioDecoder, arg1 *C.GstQuery) (cret C.gboolean) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[NonstreamAudioDecoderOverrides](instance0)
	if overrides.DecideAllocation == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected NonstreamAudioDecoderOverrides.DecideAllocation, got none")
	}

	var _query *gst.Query // out

	_query = (*gst.Query)(gextras.NewStructNative(unsafe.Pointer(arg1)))

	ok := overrides.DecideAllocation(_query)

	var _ bool

	if ok {
		cret = C.TRUE
	}

	return cret
}

//export _gotk4_gstbadaudio1_NonstreamAudioDecoderClass_get_current_subsong
func _gotk4_gstbadaudio1_NonstreamAudioDecoderClass_get_current_subsong(arg0 *C.GstNonstreamAudioDecoder) (cret C.guint) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[NonstreamAudioDecoderOverrides](instance0)
	if overrides.CurrentSubsong == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected NonstreamAudioDecoderOverrides.CurrentSubsong, got none")
	}

	guint := overrides.CurrentSubsong()

	var _ uint

	cret = C.guint(guint)

	return cret
}

//export _gotk4_gstbadaudio1_NonstreamAudioDecoderClass_get_main_tags
func _gotk4_gstbadaudio1_NonstreamAudioDecoderClass_get_main_tags(arg0 *C.GstNonstreamAudioDecoder) (cret *C.GstTagList) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[NonstreamAudioDecoderOverrides](instance0)
	if overrides.MainTags == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected NonstreamAudioDecoderOverrides.MainTags, got none")
	}

	tagList := overrides.MainTags()

	var _ *gst.TagList

	cret = (*C.GstTagList)(gextras.StructNative(unsafe.Pointer(tagList)))
	runtime.SetFinalizer(gextras.StructIntern(unsafe.Pointer(tagList)), nil)

	return cret
}

//export _gotk4_gstbadaudio1_NonstreamAudioDecoderClass_get_num_loops
func _gotk4_gstbadaudio1_NonstreamAudioDecoderClass_get_num_loops(arg0 *C.GstNonstreamAudioDecoder) (cret C.gint) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[NonstreamAudioDecoderOverrides](instance0)
	if overrides.NumLoops == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected NonstreamAudioDecoderOverrides.NumLoops, got none")
	}

	gint := overrides.NumLoops()

	var _ int

	cret = C.gint(gint)

	return cret
}

//export _gotk4_gstbadaudio1_NonstreamAudioDecoderClass_get_num_subsongs
func _gotk4_gstbadaudio1_NonstreamAudioDecoderClass_get_num_subsongs(arg0 *C.GstNonstreamAudioDecoder) (cret C.guint) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[NonstreamAudioDecoderOverrides](instance0)
	if overrides.NumSubsongs == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected NonstreamAudioDecoderOverrides.NumSubsongs, got none")
	}

	guint := overrides.NumSubsongs()

	var _ uint

	cret = C.guint(guint)

	return cret
}

//export _gotk4_gstbadaudio1_NonstreamAudioDecoderClass_get_subsong_duration
func _gotk4_gstbadaudio1_NonstreamAudioDecoderClass_get_subsong_duration(arg0 *C.GstNonstreamAudioDecoder, arg1 C.guint) (cret C.GstClockTime) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[NonstreamAudioDecoderOverrides](instance0)
	if overrides.SubsongDuration == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected NonstreamAudioDecoderOverrides.SubsongDuration, got none")
	}

	var _subsong uint // out

	_subsong = uint(arg1)

	clockTime := overrides.SubsongDuration(_subsong)

	var _ gst.ClockTime

	cret = C.GstClockTime(clockTime)

	return cret
}

//export _gotk4_gstbadaudio1_NonstreamAudioDecoderClass_get_subsong_tags
func _gotk4_gstbadaudio1_NonstreamAudioDecoderClass_get_subsong_tags(arg0 *C.GstNonstreamAudioDecoder, arg1 C.guint) (cret *C.GstTagList) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[NonstreamAudioDecoderOverrides](instance0)
	if overrides.SubsongTags == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected NonstreamAudioDecoderOverrides.SubsongTags, got none")
	}

	var _subsong uint // out

	_subsong = uint(arg1)

	tagList := overrides.SubsongTags(_subsong)

	var _ *gst.TagList

	cret = (*C.GstTagList)(gextras.StructNative(unsafe.Pointer(tagList)))
	runtime.SetFinalizer(gextras.StructIntern(unsafe.Pointer(tagList)), nil)

	return cret
}

//export _gotk4_gstbadaudio1_NonstreamAudioDecoderClass_get_supported_output_modes
func _gotk4_gstbadaudio1_NonstreamAudioDecoderClass_get_supported_output_modes(arg0 *C.GstNonstreamAudioDecoder) (cret C.guint) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[NonstreamAudioDecoderOverrides](instance0)
	if overrides.SupportedOutputModes == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected NonstreamAudioDecoderOverrides.SupportedOutputModes, got none")
	}

	guint := overrides.SupportedOutputModes()

	var _ uint

	cret = C.guint(guint)

	return cret
}

//export _gotk4_gstbadaudio1_NonstreamAudioDecoderClass_load_from_buffer
func _gotk4_gstbadaudio1_NonstreamAudioDecoderClass_load_from_buffer(arg0 *C.GstNonstreamAudioDecoder, arg1 *C.GstBuffer, arg2 C.guint, arg3 C.GstNonstreamAudioSubsongMode, arg4 *C.GstClockTime, arg5 *C.GstNonstreamAudioOutputMode, arg6 *C.gint) (cret C.gboolean) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[NonstreamAudioDecoderOverrides](instance0)
	if overrides.LoadFromBuffer == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected NonstreamAudioDecoderOverrides.LoadFromBuffer, got none")
	}

	var _sourceData *gst.Buffer                       // out
	var _initialSubsong uint                          // out
	var _initialSubsongMode NonstreamAudioSubsongMode // out
	var _initialPosition *gst.ClockTime               // out
	var _initialOutputMode *NonstreamAudioOutputMode  // out
	var _initialNumLoops *int                         // out

	_sourceData = (*gst.Buffer)(gextras.NewStructNative(unsafe.Pointer(arg1)))
	_initialSubsong = uint(arg2)
	_initialSubsongMode = NonstreamAudioSubsongMode(arg3)
	_initialPosition = (*gst.ClockTime)(unsafe.Pointer(arg4))
	_initialOutputMode = (*NonstreamAudioOutputMode)(unsafe.Pointer(arg5))
	_initialNumLoops = (*int)(unsafe.Pointer(arg6))

	ok := overrides.LoadFromBuffer(_sourceData, _initialSubsong, _initialSubsongMode, _initialPosition, _initialOutputMode, _initialNumLoops)

	var _ bool

	if ok {
		cret = C.TRUE
	}

	return cret
}

//export _gotk4_gstbadaudio1_NonstreamAudioDecoderClass_load_from_custom
func _gotk4_gstbadaudio1_NonstreamAudioDecoderClass_load_from_custom(arg0 *C.GstNonstreamAudioDecoder, arg1 C.guint, arg2 C.GstNonstreamAudioSubsongMode, arg3 *C.GstClockTime, arg4 *C.GstNonstreamAudioOutputMode, arg5 *C.gint) (cret C.gboolean) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[NonstreamAudioDecoderOverrides](instance0)
	if overrides.LoadFromCustom == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected NonstreamAudioDecoderOverrides.LoadFromCustom, got none")
	}

	var _initialSubsong uint                          // out
	var _initialSubsongMode NonstreamAudioSubsongMode // out
	var _initialPosition *gst.ClockTime               // out
	var _initialOutputMode *NonstreamAudioOutputMode  // out
	var _initialNumLoops *int                         // out

	_initialSubsong = uint(arg1)
	_initialSubsongMode = NonstreamAudioSubsongMode(arg2)
	_initialPosition = (*gst.ClockTime)(unsafe.Pointer(arg3))
	_initialOutputMode = (*NonstreamAudioOutputMode)(unsafe.Pointer(arg4))
	_initialNumLoops = (*int)(unsafe.Pointer(arg5))

	ok := overrides.LoadFromCustom(_initialSubsong, _initialSubsongMode, _initialPosition, _initialOutputMode, _initialNumLoops)

	var _ bool

	if ok {
		cret = C.TRUE
	}

	return cret
}

//export _gotk4_gstbadaudio1_NonstreamAudioDecoderClass_negotiate
func _gotk4_gstbadaudio1_NonstreamAudioDecoderClass_negotiate(arg0 *C.GstNonstreamAudioDecoder) (cret C.gboolean) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[NonstreamAudioDecoderOverrides](instance0)
	if overrides.Negotiate == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected NonstreamAudioDecoderOverrides.Negotiate, got none")
	}

	ok := overrides.Negotiate()

	var _ bool

	if ok {
		cret = C.TRUE
	}

	return cret
}

//export _gotk4_gstbadaudio1_NonstreamAudioDecoderClass_propose_allocation
func _gotk4_gstbadaudio1_NonstreamAudioDecoderClass_propose_allocation(arg0 *C.GstNonstreamAudioDecoder, arg1 *C.GstQuery) (cret C.gboolean) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[NonstreamAudioDecoderOverrides](instance0)
	if overrides.ProposeAllocation == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected NonstreamAudioDecoderOverrides.ProposeAllocation, got none")
	}

	var _query *gst.Query // out

	_query = (*gst.Query)(gextras.NewStructNative(unsafe.Pointer(arg1)))

	ok := overrides.ProposeAllocation(_query)

	var _ bool

	if ok {
		cret = C.TRUE
	}

	return cret
}

//export _gotk4_gstbadaudio1_NonstreamAudioDecoderClass_seek
func _gotk4_gstbadaudio1_NonstreamAudioDecoderClass_seek(arg0 *C.GstNonstreamAudioDecoder, arg1 *C.GstClockTime) (cret C.gboolean) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[NonstreamAudioDecoderOverrides](instance0)
	if overrides.Seek == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected NonstreamAudioDecoderOverrides.Seek, got none")
	}

	var _newPosition *gst.ClockTime // out

	_newPosition = (*gst.ClockTime)(unsafe.Pointer(arg1))

	ok := overrides.Seek(_newPosition)

	var _ bool

	if ok {
		cret = C.TRUE
	}

	return cret
}

//export _gotk4_gstbadaudio1_NonstreamAudioDecoderClass_set_current_subsong
func _gotk4_gstbadaudio1_NonstreamAudioDecoderClass_set_current_subsong(arg0 *C.GstNonstreamAudioDecoder, arg1 C.guint, arg2 *C.GstClockTime) (cret C.gboolean) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[NonstreamAudioDecoderOverrides](instance0)
	if overrides.SetCurrentSubsong == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected NonstreamAudioDecoderOverrides.SetCurrentSubsong, got none")
	}

	var _subsong uint                   // out
	var _initialPosition *gst.ClockTime // out

	_subsong = uint(arg1)
	_initialPosition = (*gst.ClockTime)(unsafe.Pointer(arg2))

	ok := overrides.SetCurrentSubsong(_subsong, _initialPosition)

	var _ bool

	if ok {
		cret = C.TRUE
	}

	return cret
}

//export _gotk4_gstbadaudio1_NonstreamAudioDecoderClass_set_num_loops
func _gotk4_gstbadaudio1_NonstreamAudioDecoderClass_set_num_loops(arg0 *C.GstNonstreamAudioDecoder, arg1 C.gint) (cret C.gboolean) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[NonstreamAudioDecoderOverrides](instance0)
	if overrides.SetNumLoops == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected NonstreamAudioDecoderOverrides.SetNumLoops, got none")
	}

	var _numLoops int // out

	_numLoops = int(arg1)

	ok := overrides.SetNumLoops(_numLoops)

	var _ bool

	if ok {
		cret = C.TRUE
	}

	return cret
}

//export _gotk4_gstbadaudio1_NonstreamAudioDecoderClass_set_output_mode
func _gotk4_gstbadaudio1_NonstreamAudioDecoderClass_set_output_mode(arg0 *C.GstNonstreamAudioDecoder, arg1 C.GstNonstreamAudioOutputMode, arg2 *C.GstClockTime) (cret C.gboolean) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[NonstreamAudioDecoderOverrides](instance0)
	if overrides.SetOutputMode == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected NonstreamAudioDecoderOverrides.SetOutputMode, got none")
	}

	var _mode NonstreamAudioOutputMode  // out
	var _currentPosition *gst.ClockTime // out

	_mode = NonstreamAudioOutputMode(arg1)
	_currentPosition = (*gst.ClockTime)(unsafe.Pointer(arg2))

	ok := overrides.SetOutputMode(_mode, _currentPosition)

	var _ bool

	if ok {
		cret = C.TRUE
	}

	return cret
}

//export _gotk4_gstbadaudio1_NonstreamAudioDecoderClass_set_subsong_mode
func _gotk4_gstbadaudio1_NonstreamAudioDecoderClass_set_subsong_mode(arg0 *C.GstNonstreamAudioDecoder, arg1 C.GstNonstreamAudioSubsongMode, arg2 *C.GstClockTime) (cret C.gboolean) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[NonstreamAudioDecoderOverrides](instance0)
	if overrides.SetSubsongMode == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected NonstreamAudioDecoderOverrides.SetSubsongMode, got none")
	}

	var _mode NonstreamAudioSubsongMode // out
	var _initialPosition *gst.ClockTime // out

	_mode = NonstreamAudioSubsongMode(arg1)
	_initialPosition = (*gst.ClockTime)(unsafe.Pointer(arg2))

	ok := overrides.SetSubsongMode(_mode, _initialPosition)

	var _ bool

	if ok {
		cret = C.TRUE
	}

	return cret
}

//export _gotk4_gstbadaudio1_NonstreamAudioDecoderClass_tell
func _gotk4_gstbadaudio1_NonstreamAudioDecoderClass_tell(arg0 *C.GstNonstreamAudioDecoder) (cret C.GstClockTime) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[NonstreamAudioDecoderOverrides](instance0)
	if overrides.Tell == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected NonstreamAudioDecoderOverrides.Tell, got none")
	}

	clockTime := overrides.Tell()

	var _ gst.ClockTime

	cret = C.GstClockTime(clockTime)

	return cret
}
