// Code generated by girgen. DO NOT EDIT.

package gobject

import (
	"github.com/diamondburned/gotk4/pkg/core/gbox"
)

// #include <glib-object.h>
import "C"

//export _gotk4_gobject2_BindingTransformFunc
func _gotk4_gobject2_BindingTransformFunc(carg1 *C.GBinding, carg2 *C.GValue, carg3 *C.GValue, carg4 C.gpointer) (cret C.gboolean) {


	ret := fn(binding, fromValue, toValue)



	return cret
}

//export _gotk4_gobject2_BoxedCopyFunc
func _gotk4_gobject2_BoxedCopyFunc(carg1 C.gpointer) (cret C.gpointer) {


	ret := fn(boxed)



	return cret
}

//export _gotk4_gobject2_BoxedFreeFunc
func _gotk4_gobject2_BoxedFreeFunc(carg1 C.gpointer) (cret C.void) {


	fn(boxed)



	return cret
}

//export _gotk4_gobject2_Callback
func _gotk4_gobject2_Callback() (cret C.void) {


	fn()



	return cret
}

//export _gotk4_gobject2_ClosureMarshal
func _gotk4_gobject2_ClosureMarshal(carg1 *C.GClosure, carg2 *C.GValue, carg3 C.guint, carg4 array, carg5 C.gpointer, carg6 C.gpointer) (cret C.void) {


	fn(closure, returnValue, paramValues, invocationHint, marshalData)



	return cret
}

//export _gotk4_gobject2_ClosureNotify
func _gotk4_gobject2_ClosureNotify(carg1 C.gpointer, carg2 *C.GClosure) (cret C.void) {


	fn(data, closure)



	return cret
}

//export _gotk4_gobject2_ObjectFinalizeFunc
func _gotk4_gobject2_ObjectFinalizeFunc(carg1 *C.GObject) (cret C.void) {


	fn(object)



	return cret
}

//export _gotk4_gobject2_SignalAccumulator
func _gotk4_gobject2_SignalAccumulator(carg1 *C.GSignalInvocationHint, carg2 *C.GValue, carg3 *C.GValue, carg4 C.gpointer) (cret C.gboolean) {


	ret := fn(ihint, returnAccu, handlerReturn, data)



	return cret
}

//export _gotk4_gobject2_SignalEmissionHook
func _gotk4_gobject2_SignalEmissionHook(carg1 *C.GSignalInvocationHint, carg2 C.guint, carg3 array, carg4 C.gpointer) (cret C.gboolean) {


	ret := fn(ihint, paramValues, data)



	return cret
}

//export _gotk4_gobject2_ToggleNotify
func _gotk4_gobject2_ToggleNotify(carg1 C.gpointer, carg2 *C.GObject, carg3 C.gboolean) (cret C.void) {


	fn(data, object, isLastRef)



	return cret
}

//export _gotk4_gobject2_TypeClassCacheFunc
func _gotk4_gobject2_TypeClassCacheFunc(carg1 C.gpointer, carg2 *C.GTypeClass) (cret C.gboolean) {


	ret := fn(cacheData, gClass)



	return cret
}

//export _gotk4_gobject2_TypePluginCompleteInterfaceInfo
func _gotk4_gobject2_TypePluginCompleteInterfaceInfo(carg1 *C.GTypePlugin, carg2 C.GType, carg3 C.GType, carg4 *C.GInterfaceInfo) (cret C.void) {


	fn(plugin, instanceType, interfaceType, info)



	return cret
}

//export _gotk4_gobject2_TypePluginCompleteTypeInfo
func _gotk4_gobject2_TypePluginCompleteTypeInfo(carg1 *C.GTypePlugin, carg2 C.GType, carg3 *C.GTypeInfo, carg4 *C.GTypeValueTable) (cret C.void) {


	fn(plugin, gType, info, valueTable)



	return cret
}

//export _gotk4_gobject2_TypePluginUnuse
func _gotk4_gobject2_TypePluginUnuse(carg1 *C.GTypePlugin) (cret C.void) {


	fn(plugin)



	return cret
}

//export _gotk4_gobject2_TypePluginUse
func _gotk4_gobject2_TypePluginUse(carg1 *C.GTypePlugin) (cret C.void) {


	fn(plugin)



	return cret
}

//export _gotk4_gobject2_TypeValueCollectFunc
func _gotk4_gobject2_TypeValueCollectFunc(carg1 *C.GValue, carg2 C.guint, carg3 array, carg4 C.guint) (cret *C.gchar) {


	ret := fn(value, collectValues, collectFlags)



	return cret
}

//export _gotk4_gobject2_TypeValueFreeFunc
func _gotk4_gobject2_TypeValueFreeFunc(carg1 *C.GValue) (cret C.void) {


	fn(value)



	return cret
}

//export _gotk4_gobject2_TypeValueInitFunc
func _gotk4_gobject2_TypeValueInitFunc(carg1 *C.GValue) (cret C.void) {


	fn(value)



	return cret
}

//export _gotk4_gobject2_TypeValueLCopyFunc
func _gotk4_gobject2_TypeValueLCopyFunc(carg1 *C.GValue, carg2 C.guint, carg3 array, carg4 C.guint) (cret *C.gchar) {


	ret := fn(value, collectValues, collectFlags)



	return cret
}

//export _gotk4_gobject2_TypeValuePeekPointerFunc
func _gotk4_gobject2_TypeValuePeekPointerFunc(carg1 *C.GValue) (cret C.gpointer) {


	ret := fn(value)



	return cret
}

//export _gotk4_gobject2_ValueTransform
func _gotk4_gobject2_ValueTransform(carg1 *C.GValue, carg2 *C.GValue) (cret C.void) {


	fn(srcValue, destValue)



	return cret
}

//export _gotk4_gobject2_WeakNotify
func _gotk4_gobject2_WeakNotify(carg1 C.gpointer, carg2 *C.GObject) (cret C.void) {


	fn(data, whereTheObjectWas)



	return cret
}

