// Code generated by girgen. DO NOT EDIT.

package atk

import (
	"github.com/diamondburned/gotk4/pkg/core/gbox"
)

// #include <atk/atk.h>
import "C"

//export _gotk4_atk1_EventListener
func _gotk4_atk1_EventListener(carg1 *C.AtkObject) (cret C.void) {


	fn(obj)



	return cret
}

//export _gotk4_atk1_EventListenerInit
func _gotk4_atk1_EventListenerInit() (cret C.void) {


	fn()



	return cret
}

//export _gotk4_atk1_FocusHandler
func _gotk4_atk1_FocusHandler(carg1 *C.AtkObject, carg2 C.gboolean) (cret C.void) {


	fn(object, focusIn)



	return cret
}

//export _gotk4_atk1_Function
func _gotk4_atk1_Function(carg1 C.gpointer) (cret C.gboolean) {


	ret := fn()



	return cret
}

//export _gotk4_atk1_KeySnoopFunc
func _gotk4_atk1_KeySnoopFunc(carg1 *C.AtkKeyEventStruct, carg2 C.gpointer) (cret C.int) {


	ret := fn(event)



	return cret
}

//export _gotk4_atk1_PropertyChangeHandler
func _gotk4_atk1_PropertyChangeHandler(carg1 *C.AtkObject, carg2 *C.AtkPropertyValues) (cret C.void) {


	fn(obj, vals)



	return cret
}

