// Code generated by girgen for Atk-1. DO NOT EDIT.

package atk

import (
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/userdata"
)

// #include <atk/atk.h>
import "C"

//export _gotk4_atk1_Function
func _gotk4_atk1_Function(carg1 C.gpointer) (cret C.gboolean) {
	var fn Function
	{
		v := userdata.Load(unsafe.Pointer(carg1))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(Function)
	}

	var goret bool // return

	goret = fn()

	if goret {
		cret = C.TRUE
	}

	return cret
}

//export _gotk4_atk1_KeySnoopFunc
func _gotk4_atk1_KeySnoopFunc(carg1 *C.AtkKeyEventStruct, carg2 C.gpointer) (cret C.gint) {
	var fn KeySnoopFunc
	{
		v := userdata.Load(unsafe.Pointer(carg2))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(KeySnoopFunc)
	}

	var event *KeyEventStruct // in, none, converted
	var goret int32           // return, none, casted

	event = UnsafeKeyEventStructFromGlibNone(unsafe.Pointer(carg1))

	goret = fn(event)

	cret = C.gint(goret)

	return cret
}

