// Code generated by girgen. DO NOT EDIT.

package ges

import (
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gbox"
	"github.com/diamondburned/gotk4/pkg/core/gerror"
	"github.com/diamondburned/gotk4/pkg/core/gextras"
	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
	"github.com/diamondburned/gotk4/pkg/gst"
	"github.com/diamondburned/gotk4/pkg/gstpbutils"
)

// #include <stdlib.h>
// #include <ges/ges.h>
// #include <glib-object.h>
import "C"

//export _gotk4_ges1_BaseEffectTimeTranslationFunc
func _gotk4_ges1_BaseEffectTimeTranslationFunc(arg1 *C.GESBaseEffect, arg2 C.GstClockTime, arg3 *C.GHashTable, arg4 C.gpointer) (cret C.GstClockTime) {
	var fn BaseEffectTimeTranslationFunc
	{
		v := gbox.Get(uintptr(arg4))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(BaseEffectTimeTranslationFunc)
	}

	var _effect BaseEffector                           // out
	var _time gst.ClockTime                            // out
	var _timePropertyValues map[string]*coreglib.Value // out

	{
		objptr := unsafe.Pointer(arg1)
		if objptr == nil {
			panic("object of type ges.BaseEffector is nil")
		}

		object := coreglib.Take(objptr)
		casted := object.WalkCast(func(obj coreglib.Objector) bool {
			_, ok := obj.(BaseEffector)
			return ok
		})
		rv, ok := casted.(BaseEffector)
		if !ok {
			panic("no marshaler for " + object.TypeFromInstance().String() + " matching ges.BaseEffector")
		}
		_effect = rv
	}
	_time = gst.ClockTime(arg2)
	_timePropertyValues = make(map[string]*coreglib.Value, gextras.HashTableSize(unsafe.Pointer(arg3)))
	gextras.MoveHashTable(unsafe.Pointer(arg3), false, func(k, v unsafe.Pointer) {
		ksrc := *(**C.gchar)(k)
		vsrc := *(**C.GValue)(v)
		var kdst string          // out
		var vdst *coreglib.Value // out
		kdst = C.GoString((*C.gchar)(unsafe.Pointer(ksrc)))
		vdst = coreglib.ValueFromNative(unsafe.Pointer(vsrc))
		_timePropertyValues[kdst] = vdst
	})

	clockTime := fn(_effect, _time, _timePropertyValues)

	var _ gst.ClockTime

	cret = C.GstClockTime(clockTime)

	return cret
}

//export _gotk4_ges1_MetaForEachFunc
func _gotk4_ges1_MetaForEachFunc(arg1 *C.GESMetaContainer, arg2 *C.gchar, arg3 *C.GValue, arg4 C.gpointer) {
	var fn MetaForEachFunc
	{
		v := gbox.Get(uintptr(arg4))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(MetaForEachFunc)
	}

	var _container MetaContainerer // out
	var _key string                // out
	var _value *coreglib.Value     // out

	{
		objptr := unsafe.Pointer(arg1)
		if objptr == nil {
			panic("object of type ges.MetaContainerer is nil")
		}

		object := coreglib.Take(objptr)
		casted := object.WalkCast(func(obj coreglib.Objector) bool {
			_, ok := obj.(MetaContainerer)
			return ok
		})
		rv, ok := casted.(MetaContainerer)
		if !ok {
			panic("no marshaler for " + object.TypeFromInstance().String() + " matching ges.MetaContainerer")
		}
		_container = rv
	}
	_key = C.GoString((*C.gchar)(unsafe.Pointer(arg2)))
	_value = coreglib.ValueFromNative(unsafe.Pointer(arg3))

	fn(_container, _key, _value)
}

//export _gotk4_ges1_MetaContainer_ConnectNotifyMeta
func _gotk4_ges1_MetaContainer_ConnectNotifyMeta(arg0 C.gpointer, arg1 *C.gchar, arg2 *C.GValue, arg3 C.guintptr) {
	var f func(key string, value *coreglib.Value)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg3))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(key string, value *coreglib.Value))
	}

	var _key string            // out
	var _value *coreglib.Value // out

	_key = C.GoString((*C.gchar)(unsafe.Pointer(arg1)))
	if arg2 != nil {
		_value = coreglib.ValueFromNative(unsafe.Pointer(arg2))
	}

	f(_key, _value)
}

//export _gotk4_ges1_AssetClass_extract
func _gotk4_ges1_AssetClass_extract(arg0 *C.GESAsset, _cerr **C.GError) (cret *C.GESExtractable) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[AssetOverrides](instance0)
	if overrides.Extract == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected AssetOverrides.Extract, got none")
	}

	extractable, _goerr := overrides.Extract()

	var _ *Extractable
	var _ error

	cret = (*C.GESExtractable)(unsafe.Pointer(coreglib.InternObject(extractable).Native()))
	if _goerr != nil && _cerr != nil {
		*_cerr = (*C.GError)(gerror.New(_goerr))
	}

	return cret
}

//export _gotk4_ges1_AssetClass_inform_proxy
func _gotk4_ges1_AssetClass_inform_proxy(arg0 *C.GESAsset, arg1 *C.gchar) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[AssetOverrides](instance0)
	if overrides.InformProxy == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected AssetOverrides.InformProxy, got none")
	}

	var _proxyId string // out

	_proxyId = C.GoString((*C.gchar)(unsafe.Pointer(arg1)))

	overrides.InformProxy(_proxyId)
}

//export _gotk4_ges1_AssetClass_proxied
func _gotk4_ges1_AssetClass_proxied(arg0 *C.GESAsset, arg1 *C.GESAsset) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[AssetOverrides](instance0)
	if overrides.Proxied == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected AssetOverrides.Proxied, got none")
	}

	var _proxy *Asset // out

	_proxy = wrapAsset(coreglib.Take(unsafe.Pointer(arg1)))

	overrides.Proxied(_proxy)
}

//export _gotk4_ges1_AssetClass_start_loading
func _gotk4_ges1_AssetClass_start_loading(arg0 *C.GESAsset, _cerr **C.GError) (cret C.GESAssetLoadingReturn) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[AssetOverrides](instance0)
	if overrides.StartLoading == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected AssetOverrides.StartLoading, got none")
	}

	assetLoadingReturn, _goerr := overrides.StartLoading()

	var _ AssetLoadingReturn
	var _ error

	cret = C.GESAssetLoadingReturn(assetLoadingReturn)
	if _goerr != nil && _cerr != nil {
		*_cerr = (*C.GError)(gerror.New(_goerr))
	}

	return cret
}

//export _gotk4_ges1_ClipClass_create_track_element
func _gotk4_ges1_ClipClass_create_track_element(arg0 *C.GESClip, arg1 C.GESTrackType) (cret *C.GESTrackElement) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[ClipOverrides](instance0)
	if overrides.CreateTrackElement == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected ClipOverrides.CreateTrackElement, got none")
	}

	var _typ TrackType // out

	_typ = TrackType(arg1)

	trackElement := overrides.CreateTrackElement(_typ)

	var _ TrackElementer

	if trackElement != nil {
		cret = (*C.GESTrackElement)(unsafe.Pointer(coreglib.InternObject(trackElement).Native()))
	}

	return cret
}

//export _gotk4_ges1_ClipClass_create_track_elements
func _gotk4_ges1_ClipClass_create_track_elements(arg0 *C.GESClip, arg1 C.GESTrackType) (cret *C.GList) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[ClipOverrides](instance0)
	if overrides.CreateTrackElements == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected ClipOverrides.CreateTrackElements, got none")
	}

	var _typ TrackType // out

	_typ = TrackType(arg1)

	list := overrides.CreateTrackElements(_typ)

	var _ []TrackElementer

	for i := len(list) - 1; i >= 0; i-- {
		src := list[i]
		var dst *C.GESTrackElement // out
		dst = (*C.GESTrackElement)(unsafe.Pointer(coreglib.InternObject(src).Native()))
		cret = C.g_list_prepend(cret, C.gpointer(unsafe.Pointer(dst)))
	}

	return cret
}

//export _gotk4_ges1_ClipAssetClass_get_natural_framerate
func _gotk4_ges1_ClipAssetClass_get_natural_framerate(arg0 *C.GESClipAsset, arg1 *C.gint, arg2 *C.gint) (cret C.gboolean) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[ClipAssetOverrides](instance0)
	if overrides.NaturalFramerate == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected ClipAssetOverrides.NaturalFramerate, got none")
	}

	framerateN, framerateD, ok := overrides.NaturalFramerate()

	var _ int
	var _ int
	var _ bool

	*arg1 = C.gint(framerateN)
	*arg2 = C.gint(framerateD)
	if ok {
		cret = C.TRUE
	}

	return cret
}

//export _gotk4_ges1_ContainerClass_add_child
func _gotk4_ges1_ContainerClass_add_child(arg0 *C.GESContainer, arg1 *C.GESTimelineElement) (cret C.gboolean) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[ContainerOverrides](instance0)
	if overrides.AddChild == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected ContainerOverrides.AddChild, got none")
	}

	var _element TimelineElementer // out

	{
		objptr := unsafe.Pointer(arg1)
		if objptr == nil {
			panic("object of type ges.TimelineElementer is nil")
		}

		object := coreglib.Take(objptr)
		casted := object.WalkCast(func(obj coreglib.Objector) bool {
			_, ok := obj.(TimelineElementer)
			return ok
		})
		rv, ok := casted.(TimelineElementer)
		if !ok {
			panic("no marshaler for " + object.TypeFromInstance().String() + " matching ges.TimelineElementer")
		}
		_element = rv
	}

	ok := overrides.AddChild(_element)

	var _ bool

	if ok {
		cret = C.TRUE
	}

	return cret
}

//export _gotk4_ges1_ContainerClass_child_added
func _gotk4_ges1_ContainerClass_child_added(arg0 *C.GESContainer, arg1 *C.GESTimelineElement) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[ContainerOverrides](instance0)
	if overrides.ChildAdded == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected ContainerOverrides.ChildAdded, got none")
	}

	var _element TimelineElementer // out

	{
		objptr := unsafe.Pointer(arg1)
		if objptr == nil {
			panic("object of type ges.TimelineElementer is nil")
		}

		object := coreglib.Take(objptr)
		casted := object.WalkCast(func(obj coreglib.Objector) bool {
			_, ok := obj.(TimelineElementer)
			return ok
		})
		rv, ok := casted.(TimelineElementer)
		if !ok {
			panic("no marshaler for " + object.TypeFromInstance().String() + " matching ges.TimelineElementer")
		}
		_element = rv
	}

	overrides.ChildAdded(_element)
}

//export _gotk4_ges1_ContainerClass_child_removed
func _gotk4_ges1_ContainerClass_child_removed(arg0 *C.GESContainer, arg1 *C.GESTimelineElement) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[ContainerOverrides](instance0)
	if overrides.ChildRemoved == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected ContainerOverrides.ChildRemoved, got none")
	}

	var _element TimelineElementer // out

	{
		objptr := unsafe.Pointer(arg1)
		if objptr == nil {
			panic("object of type ges.TimelineElementer is nil")
		}

		object := coreglib.Take(objptr)
		casted := object.WalkCast(func(obj coreglib.Objector) bool {
			_, ok := obj.(TimelineElementer)
			return ok
		})
		rv, ok := casted.(TimelineElementer)
		if !ok {
			panic("no marshaler for " + object.TypeFromInstance().String() + " matching ges.TimelineElementer")
		}
		_element = rv
	}

	overrides.ChildRemoved(_element)
}

//export _gotk4_ges1_ContainerClass_edit
func _gotk4_ges1_ContainerClass_edit(arg0 *C.GESContainer, arg1 *C.GList, arg2 C.gint, arg3 C.GESEditMode, arg4 C.GESEdge, arg5 C.guint64) (cret C.gboolean) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[ContainerOverrides](instance0)
	if overrides.Edit == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected ContainerOverrides.Edit, got none")
	}

	var _layers []*Layer      // out
	var _newLayerPriority int // out
	var _mode EditMode        // out
	var _edge Edge            // out
	var _position uint64      // out

	if arg1 != nil {
		_layers = make([]*Layer, 0, gextras.ListSize(unsafe.Pointer(arg1)))
		gextras.MoveList(unsafe.Pointer(arg1), false, func(v unsafe.Pointer) {
			src := (*C.GESLayer)(v)
			var dst *Layer // out
			dst = wrapLayer(coreglib.Take(unsafe.Pointer(src)))
			_layers = append(_layers, dst)
		})
	}
	_newLayerPriority = int(arg2)
	_mode = EditMode(arg3)
	_edge = Edge(arg4)
	_position = uint64(arg5)

	ok := overrides.Edit(_layers, _newLayerPriority, _mode, _edge, _position)

	var _ bool

	if ok {
		cret = C.TRUE
	}

	return cret
}

//export _gotk4_ges1_ContainerClass_remove_child
func _gotk4_ges1_ContainerClass_remove_child(arg0 *C.GESContainer, arg1 *C.GESTimelineElement) (cret C.gboolean) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[ContainerOverrides](instance0)
	if overrides.RemoveChild == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected ContainerOverrides.RemoveChild, got none")
	}

	var _element TimelineElementer // out

	{
		objptr := unsafe.Pointer(arg1)
		if objptr == nil {
			panic("object of type ges.TimelineElementer is nil")
		}

		object := coreglib.Take(objptr)
		casted := object.WalkCast(func(obj coreglib.Objector) bool {
			_, ok := obj.(TimelineElementer)
			return ok
		})
		rv, ok := casted.(TimelineElementer)
		if !ok {
			panic("no marshaler for " + object.TypeFromInstance().String() + " matching ges.TimelineElementer")
		}
		_element = rv
	}

	ok := overrides.RemoveChild(_element)

	var _ bool

	if ok {
		cret = C.TRUE
	}

	return cret
}

//export _gotk4_ges1_ContainerClass_ungroup
func _gotk4_ges1_ContainerClass_ungroup(arg0 *C.GESContainer, arg1 C.gboolean) (cret *C.GList) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[ContainerOverrides](instance0)
	if overrides.Ungroup == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected ContainerOverrides.Ungroup, got none")
	}

	var _recursive bool // out

	if arg1 != 0 {
		_recursive = true
	}

	list := overrides.Ungroup(_recursive)

	var _ []Containerer

	for i := len(list) - 1; i >= 0; i-- {
		src := list[i]
		var dst *C.GESContainer // out
		dst = (*C.GESContainer)(unsafe.Pointer(coreglib.InternObject(src).Native()))
		C.g_object_ref(C.gpointer(coreglib.InternObject(src).Native()))
		cret = C.g_list_prepend(cret, C.gpointer(unsafe.Pointer(dst)))
	}

	return cret
}

//export _gotk4_ges1_Container_ConnectChildAdded
func _gotk4_ges1_Container_ConnectChildAdded(arg0 C.gpointer, arg1 *C.GESTimelineElement, arg2 C.guintptr) {
	var f func(element TimelineElementer)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg2))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(element TimelineElementer))
	}

	var _element TimelineElementer // out

	{
		objptr := unsafe.Pointer(arg1)
		if objptr == nil {
			panic("object of type ges.TimelineElementer is nil")
		}

		object := coreglib.Take(objptr)
		casted := object.WalkCast(func(obj coreglib.Objector) bool {
			_, ok := obj.(TimelineElementer)
			return ok
		})
		rv, ok := casted.(TimelineElementer)
		if !ok {
			panic("no marshaler for " + object.TypeFromInstance().String() + " matching ges.TimelineElementer")
		}
		_element = rv
	}

	f(_element)
}

//export _gotk4_ges1_Container_ConnectChildRemoved
func _gotk4_ges1_Container_ConnectChildRemoved(arg0 C.gpointer, arg1 *C.GESTimelineElement, arg2 C.guintptr) {
	var f func(element TimelineElementer)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg2))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(element TimelineElementer))
	}

	var _element TimelineElementer // out

	{
		objptr := unsafe.Pointer(arg1)
		if objptr == nil {
			panic("object of type ges.TimelineElementer is nil")
		}

		object := coreglib.Take(objptr)
		casted := object.WalkCast(func(obj coreglib.Objector) bool {
			_, ok := obj.(TimelineElementer)
			return ok
		})
		rv, ok := casted.(TimelineElementer)
		if !ok {
			panic("no marshaler for " + object.TypeFromInstance().String() + " matching ges.TimelineElementer")
		}
		_element = rv
	}

	f(_element)
}

//export _gotk4_ges1_DiscovererManager_ConnectDiscovered
func _gotk4_ges1_DiscovererManager_ConnectDiscovered(arg0 C.gpointer, arg1 *C.GstDiscovererInfo, arg2 *C.GError, arg3 C.guintptr) {
	var f func(info *gstpbutils.DiscovererInfo, err error)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg3))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(info *gstpbutils.DiscovererInfo, err error))
	}

	var _info *gstpbutils.DiscovererInfo // out
	var _err error                       // out

	{
		obj := coreglib.Take(unsafe.Pointer(arg1))
		_info = &gstpbutils.DiscovererInfo{
			Object: obj,
		}
	}
	if arg2 != nil {
		_err = gerror.Take(unsafe.Pointer(arg2))
	}

	f(_info, _err)
}

//export _gotk4_ges1_DiscovererManager_ConnectLoadSerializedInfo
func _gotk4_ges1_DiscovererManager_ConnectLoadSerializedInfo(arg0 C.gpointer, arg1 *C.gchar, arg2 C.guintptr) (cret *C.GstDiscovererInfo) {
	var f func(uri string) (discovererInfo *gstpbutils.DiscovererInfo)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg2))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(uri string) (discovererInfo *gstpbutils.DiscovererInfo))
	}

	var _uri string // out

	_uri = C.GoString((*C.gchar)(unsafe.Pointer(arg1)))

	discovererInfo := f(_uri)

	var _ *gstpbutils.DiscovererInfo

	if discovererInfo != nil {
		cret = (*C.GstDiscovererInfo)(unsafe.Pointer(coreglib.InternObject(discovererInfo).Native()))
		C.g_object_ref(C.gpointer(coreglib.InternObject(discovererInfo).Native()))
	}

	return cret
}

//export _gotk4_ges1_DiscovererManager_ConnectSourceSetup
func _gotk4_ges1_DiscovererManager_ConnectSourceSetup(arg0 C.gpointer, arg1 *C.GstElement, arg2 C.guintptr) {
	var f func(source gst.Elementer)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg2))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(source gst.Elementer))
	}

	var _source gst.Elementer // out

	{
		objptr := unsafe.Pointer(arg1)
		if objptr == nil {
			panic("object of type gst.Elementer is nil")
		}

		object := coreglib.Take(objptr)
		casted := object.WalkCast(func(obj coreglib.Objector) bool {
			_, ok := obj.(gst.Elementer)
			return ok
		})
		rv, ok := casted.(gst.Elementer)
		if !ok {
			panic("no marshaler for " + object.TypeFromInstance().String() + " matching gst.Elementer")
		}
		_source = rv
	}

	f(_source)
}

//export _gotk4_ges1_FormatterClass_can_load_uri
func _gotk4_ges1_FormatterClass_can_load_uri(arg0 *C.GESFormatter, arg1 *C.gchar, _cerr **C.GError) (cret C.gboolean) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[FormatterOverrides](instance0)
	if overrides.CanLoadURI == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected FormatterOverrides.CanLoadURI, got none")
	}

	var _uri string // out

	_uri = C.GoString((*C.gchar)(unsafe.Pointer(arg1)))

	_goerr := overrides.CanLoadURI(_uri)

	var _ error

	if _goerr != nil && _cerr != nil {
		*_cerr = (*C.GError)(gerror.New(_goerr))
	}

	return cret
}

//export _gotk4_ges1_FormatterClass_load_from_uri
func _gotk4_ges1_FormatterClass_load_from_uri(arg0 *C.GESFormatter, arg1 *C.GESTimeline, arg2 *C.gchar, _cerr **C.GError) (cret C.gboolean) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[FormatterOverrides](instance0)
	if overrides.LoadFromURI == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected FormatterOverrides.LoadFromURI, got none")
	}

	var _timeline *Timeline // out
	var _uri string         // out

	_timeline = wrapTimeline(coreglib.Take(unsafe.Pointer(arg1)))
	_uri = C.GoString((*C.gchar)(unsafe.Pointer(arg2)))

	_goerr := overrides.LoadFromURI(_timeline, _uri)

	var _ error

	if _goerr != nil && _cerr != nil {
		*_cerr = (*C.GError)(gerror.New(_goerr))
	}

	return cret
}

//export _gotk4_ges1_FormatterClass_save_to_uri
func _gotk4_ges1_FormatterClass_save_to_uri(arg0 *C.GESFormatter, arg1 *C.GESTimeline, arg2 *C.gchar, arg3 C.gboolean, _cerr **C.GError) (cret C.gboolean) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[FormatterOverrides](instance0)
	if overrides.SaveToURI == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected FormatterOverrides.SaveToURI, got none")
	}

	var _timeline *Timeline // out
	var _uri string         // out
	var _overwrite bool     // out

	_timeline = wrapTimeline(coreglib.Take(unsafe.Pointer(arg1)))
	_uri = C.GoString((*C.gchar)(unsafe.Pointer(arg2)))
	if arg3 != 0 {
		_overwrite = true
	}

	_goerr := overrides.SaveToURI(_timeline, _uri, _overwrite)

	var _ error

	if _goerr != nil && _cerr != nil {
		*_cerr = (*C.GError)(gerror.New(_goerr))
	}

	return cret
}

//export _gotk4_ges1_LayerClass_object_added
func _gotk4_ges1_LayerClass_object_added(arg0 *C.GESLayer, arg1 *C.GESClip) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[LayerOverrides](instance0)
	if overrides.ObjectAdded == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected LayerOverrides.ObjectAdded, got none")
	}

	var _object Clipper // out

	{
		objptr := unsafe.Pointer(arg1)
		if objptr == nil {
			panic("object of type ges.Clipper is nil")
		}

		object := coreglib.Take(objptr)
		casted := object.WalkCast(func(obj coreglib.Objector) bool {
			_, ok := obj.(Clipper)
			return ok
		})
		rv, ok := casted.(Clipper)
		if !ok {
			panic("no marshaler for " + object.TypeFromInstance().String() + " matching ges.Clipper")
		}
		_object = rv
	}

	overrides.ObjectAdded(_object)
}

//export _gotk4_ges1_LayerClass_object_removed
func _gotk4_ges1_LayerClass_object_removed(arg0 *C.GESLayer, arg1 *C.GESClip) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[LayerOverrides](instance0)
	if overrides.ObjectRemoved == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected LayerOverrides.ObjectRemoved, got none")
	}

	var _object Clipper // out

	{
		objptr := unsafe.Pointer(arg1)
		if objptr == nil {
			panic("object of type ges.Clipper is nil")
		}

		object := coreglib.Take(objptr)
		casted := object.WalkCast(func(obj coreglib.Objector) bool {
			_, ok := obj.(Clipper)
			return ok
		})
		rv, ok := casted.(Clipper)
		if !ok {
			panic("no marshaler for " + object.TypeFromInstance().String() + " matching ges.Clipper")
		}
		_object = rv
	}

	overrides.ObjectRemoved(_object)
}

//export _gotk4_ges1_Layer_ConnectClipAdded
func _gotk4_ges1_Layer_ConnectClipAdded(arg0 C.gpointer, arg1 *C.GESClip, arg2 C.guintptr) {
	var f func(clip Clipper)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg2))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(clip Clipper))
	}

	var _clip Clipper // out

	{
		objptr := unsafe.Pointer(arg1)
		if objptr == nil {
			panic("object of type ges.Clipper is nil")
		}

		object := coreglib.Take(objptr)
		casted := object.WalkCast(func(obj coreglib.Objector) bool {
			_, ok := obj.(Clipper)
			return ok
		})
		rv, ok := casted.(Clipper)
		if !ok {
			panic("no marshaler for " + object.TypeFromInstance().String() + " matching ges.Clipper")
		}
		_clip = rv
	}

	f(_clip)
}

//export _gotk4_ges1_Layer_ConnectClipRemoved
func _gotk4_ges1_Layer_ConnectClipRemoved(arg0 C.gpointer, arg1 *C.GESClip, arg2 C.guintptr) {
	var f func(clip Clipper)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg2))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(clip Clipper))
	}

	var _clip Clipper // out

	{
		objptr := unsafe.Pointer(arg1)
		if objptr == nil {
			panic("object of type ges.Clipper is nil")
		}

		object := coreglib.Take(objptr)
		casted := object.WalkCast(func(obj coreglib.Objector) bool {
			_, ok := obj.(Clipper)
			return ok
		})
		rv, ok := casted.(Clipper)
		if !ok {
			panic("no marshaler for " + object.TypeFromInstance().String() + " matching ges.Clipper")
		}
		_clip = rv
	}

	f(_clip)
}

//export _gotk4_ges1_MarkerList_ConnectMarkerAdded
func _gotk4_ges1_MarkerList_ConnectMarkerAdded(arg0 C.gpointer, arg1 C.guint64, arg2 *C.GESMarker, arg3 C.guintptr) {
	var f func(position uint64, marker *Marker)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg3))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(position uint64, marker *Marker))
	}

	var _position uint64 // out
	var _marker *Marker  // out

	_position = uint64(arg1)
	_marker = wrapMarker(coreglib.Take(unsafe.Pointer(arg2)))

	f(_position, _marker)
}

//export _gotk4_ges1_MarkerList_ConnectMarkerMoved
func _gotk4_ges1_MarkerList_ConnectMarkerMoved(arg0 C.gpointer, arg1 C.guint64, arg2 C.guint64, arg3 *C.GESMarker, arg4 C.guintptr) {
	var f func(previousPosition, newPosition uint64, marker *Marker)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg4))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(previousPosition, newPosition uint64, marker *Marker))
	}

	var _previousPosition uint64 // out
	var _newPosition uint64      // out
	var _marker *Marker          // out

	_previousPosition = uint64(arg1)
	_newPosition = uint64(arg2)
	_marker = wrapMarker(coreglib.Take(unsafe.Pointer(arg3)))

	f(_previousPosition, _newPosition, _marker)
}

//export _gotk4_ges1_MarkerList_ConnectMarkerRemoved
func _gotk4_ges1_MarkerList_ConnectMarkerRemoved(arg0 C.gpointer, arg1 *C.GESMarker, arg2 C.guintptr) {
	var f func(marker *Marker)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg2))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(marker *Marker))
	}

	var _marker *Marker // out

	_marker = wrapMarker(coreglib.Take(unsafe.Pointer(arg1)))

	f(_marker)
}

//export _gotk4_ges1_ProjectClass_asset_added
func _gotk4_ges1_ProjectClass_asset_added(arg0 *C.GESProject, arg1 *C.GESAsset) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[ProjectOverrides](instance0)
	if overrides.AssetAdded == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected ProjectOverrides.AssetAdded, got none")
	}

	var _asset *Asset // out

	_asset = wrapAsset(coreglib.Take(unsafe.Pointer(arg1)))

	overrides.AssetAdded(_asset)
}

//export _gotk4_ges1_ProjectClass_asset_loading
func _gotk4_ges1_ProjectClass_asset_loading(arg0 *C.GESProject, arg1 *C.GESAsset) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[ProjectOverrides](instance0)
	if overrides.AssetLoading == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected ProjectOverrides.AssetLoading, got none")
	}

	var _asset *Asset // out

	_asset = wrapAsset(coreglib.Take(unsafe.Pointer(arg1)))

	overrides.AssetLoading(_asset)
}

//export _gotk4_ges1_ProjectClass_asset_removed
func _gotk4_ges1_ProjectClass_asset_removed(arg0 *C.GESProject, arg1 *C.GESAsset) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[ProjectOverrides](instance0)
	if overrides.AssetRemoved == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected ProjectOverrides.AssetRemoved, got none")
	}

	var _asset *Asset // out

	_asset = wrapAsset(coreglib.Take(unsafe.Pointer(arg1)))

	overrides.AssetRemoved(_asset)
}

//export _gotk4_ges1_ProjectClass_loaded
func _gotk4_ges1_ProjectClass_loaded(arg0 *C.GESProject, arg1 *C.GESTimeline) (cret C.gboolean) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[ProjectOverrides](instance0)
	if overrides.Loaded == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected ProjectOverrides.Loaded, got none")
	}

	var _timeline *Timeline // out

	_timeline = wrapTimeline(coreglib.Take(unsafe.Pointer(arg1)))

	ok := overrides.Loaded(_timeline)

	var _ bool

	if ok {
		cret = C.TRUE
	}

	return cret
}

//export _gotk4_ges1_ProjectClass_loading
func _gotk4_ges1_ProjectClass_loading(arg0 *C.GESProject, arg1 *C.GESTimeline) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[ProjectOverrides](instance0)
	if overrides.Loading == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected ProjectOverrides.Loading, got none")
	}

	var _timeline *Timeline // out

	_timeline = wrapTimeline(coreglib.Take(unsafe.Pointer(arg1)))

	overrides.Loading(_timeline)
}

//export _gotk4_ges1_ProjectClass_loading_error
func _gotk4_ges1_ProjectClass_loading_error(arg0 *C.GESProject, arg1 *C.GError, arg2 *C.gchar, arg3 C.GType) (cret C.gboolean) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[ProjectOverrides](instance0)
	if overrides.LoadingError == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected ProjectOverrides.LoadingError, got none")
	}

	var _err error                     // out
	var _id string                     // out
	var _extractableType coreglib.Type // out

	_err = gerror.Take(unsafe.Pointer(arg1))
	_id = C.GoString((*C.gchar)(unsafe.Pointer(arg2)))
	_extractableType = coreglib.Type(arg3)

	ok := overrides.LoadingError(_err, _id, _extractableType)

	var _ bool

	if ok {
		cret = C.TRUE
	}

	return cret
}

//export _gotk4_ges1_ProjectClass_missing_uri
func _gotk4_ges1_ProjectClass_missing_uri(arg0 *C.GESProject, arg1 *C.GError, arg2 *C.GESAsset) (cret *C.gchar) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[ProjectOverrides](instance0)
	if overrides.MissingURI == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected ProjectOverrides.MissingURI, got none")
	}

	var _err error         // out
	var _wrongAsset *Asset // out

	_err = gerror.Take(unsafe.Pointer(arg1))
	_wrongAsset = wrapAsset(coreglib.Take(unsafe.Pointer(arg2)))

	utf8 := overrides.MissingURI(_err, _wrongAsset)

	var _ string

	cret = (*C.gchar)(unsafe.Pointer(C.CString(utf8)))

	return cret
}

//export _gotk4_ges1_Project_ConnectAssetAdded
func _gotk4_ges1_Project_ConnectAssetAdded(arg0 C.gpointer, arg1 *C.GESAsset, arg2 C.guintptr) {
	var f func(asset *Asset)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg2))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(asset *Asset))
	}

	var _asset *Asset // out

	_asset = wrapAsset(coreglib.Take(unsafe.Pointer(arg1)))

	f(_asset)
}

//export _gotk4_ges1_Project_ConnectAssetLoading
func _gotk4_ges1_Project_ConnectAssetLoading(arg0 C.gpointer, arg1 *C.GESAsset, arg2 C.guintptr) {
	var f func(asset *Asset)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg2))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(asset *Asset))
	}

	var _asset *Asset // out

	_asset = wrapAsset(coreglib.Take(unsafe.Pointer(arg1)))

	f(_asset)
}

//export _gotk4_ges1_Project_ConnectAssetRemoved
func _gotk4_ges1_Project_ConnectAssetRemoved(arg0 C.gpointer, arg1 *C.GESAsset, arg2 C.guintptr) {
	var f func(asset *Asset)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg2))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(asset *Asset))
	}

	var _asset *Asset // out

	_asset = wrapAsset(coreglib.Take(unsafe.Pointer(arg1)))

	f(_asset)
}

//export _gotk4_ges1_Project_ConnectErrorLoading
func _gotk4_ges1_Project_ConnectErrorLoading(arg0 C.gpointer, arg1 *C.GESTimeline, arg2 *C.GError, arg3 C.guintptr) {
	var f func(timeline *Timeline, err error)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg3))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(timeline *Timeline, err error))
	}

	var _timeline *Timeline // out
	var _err error          // out

	_timeline = wrapTimeline(coreglib.Take(unsafe.Pointer(arg1)))
	_err = gerror.Take(unsafe.Pointer(arg2))

	f(_timeline, _err)
}

//export _gotk4_ges1_Project_ConnectErrorLoadingAsset
func _gotk4_ges1_Project_ConnectErrorLoadingAsset(arg0 C.gpointer, arg1 *C.GError, arg2 *C.gchar, arg3 C.GType, arg4 C.guintptr) {
	var f func(err error, id string, extractableType coreglib.Type)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg4))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(err error, id string, extractableType coreglib.Type))
	}

	var _err error                     // out
	var _id string                     // out
	var _extractableType coreglib.Type // out

	_err = gerror.Take(unsafe.Pointer(arg1))
	_id = C.GoString((*C.gchar)(unsafe.Pointer(arg2)))
	_extractableType = coreglib.Type(arg3)

	f(_err, _id, _extractableType)
}

//export _gotk4_ges1_Project_ConnectLoaded
func _gotk4_ges1_Project_ConnectLoaded(arg0 C.gpointer, arg1 *C.GESTimeline, arg2 C.guintptr) {
	var f func(timeline *Timeline)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg2))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(timeline *Timeline))
	}

	var _timeline *Timeline // out

	_timeline = wrapTimeline(coreglib.Take(unsafe.Pointer(arg1)))

	f(_timeline)
}

//export _gotk4_ges1_Project_ConnectLoading
func _gotk4_ges1_Project_ConnectLoading(arg0 C.gpointer, arg1 *C.GESTimeline, arg2 C.guintptr) {
	var f func(timeline *Timeline)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg2))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(timeline *Timeline))
	}

	var _timeline *Timeline // out

	_timeline = wrapTimeline(coreglib.Take(unsafe.Pointer(arg1)))

	f(_timeline)
}

//export _gotk4_ges1_Project_ConnectMissingURI
func _gotk4_ges1_Project_ConnectMissingURI(arg0 C.gpointer, arg1 *C.GError, arg2 *C.GESAsset, arg3 C.guintptr) (cret *C.gchar) {
	var f func(err error, wrongAsset *Asset) (utf8 string)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg3))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(err error, wrongAsset *Asset) (utf8 string))
	}

	var _err error         // out
	var _wrongAsset *Asset // out

	_err = gerror.Take(unsafe.Pointer(arg1))
	_wrongAsset = wrapAsset(coreglib.Take(unsafe.Pointer(arg2)))

	utf8 := f(_err, _wrongAsset)

	var _ string

	if utf8 != "" {
		cret = (*C.gchar)(unsafe.Pointer(C.CString(utf8)))
	}

	return cret
}

//export _gotk4_ges1_SourceClass_create_source
func _gotk4_ges1_SourceClass_create_source(arg0 *C.GESSource) (cret *C.GstElement) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[SourceOverrides](instance0)
	if overrides.CreateSource == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected SourceOverrides.CreateSource, got none")
	}

	element := overrides.CreateSource()

	var _ gst.Elementer

	cret = (*C.GstElement)(unsafe.Pointer(coreglib.InternObject(element).Native()))

	return cret
}

//export _gotk4_ges1_SourceClass_select_pad
func _gotk4_ges1_SourceClass_select_pad(arg0 *C.GESSource, arg1 *C.GstPad) (cret C.gboolean) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[SourceOverrides](instance0)
	if overrides.SelectPad == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected SourceOverrides.SelectPad, got none")
	}

	var _pad *gst.Pad // out

	{
		obj := coreglib.Take(unsafe.Pointer(arg1))
		_pad = &gst.Pad{
			GstObject: gst.GstObject{
				InitiallyUnowned: coreglib.InitiallyUnowned{
					Object: obj,
				},
			},
		}
	}

	ok := overrides.SelectPad(_pad)

	var _ bool

	if ok {
		cret = C.TRUE
	}

	return cret
}

//export _gotk4_ges1_TimelineClass_group_added
func _gotk4_ges1_TimelineClass_group_added(arg0 *C.GESTimeline, arg1 *C.GESGroup) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[TimelineOverrides](instance0)
	if overrides.GroupAdded == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected TimelineOverrides.GroupAdded, got none")
	}

	var _group *Group // out

	_group = wrapGroup(coreglib.Take(unsafe.Pointer(arg1)))

	overrides.GroupAdded(_group)
}

//export _gotk4_ges1_TimelineClass_layer_added
func _gotk4_ges1_TimelineClass_layer_added(arg0 *C.GESTimeline, arg1 *C.GESLayer) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[TimelineOverrides](instance0)
	if overrides.LayerAdded == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected TimelineOverrides.LayerAdded, got none")
	}

	var _layer *Layer // out

	_layer = wrapLayer(coreglib.Take(unsafe.Pointer(arg1)))

	overrides.LayerAdded(_layer)
}

//export _gotk4_ges1_TimelineClass_layer_removed
func _gotk4_ges1_TimelineClass_layer_removed(arg0 *C.GESTimeline, arg1 *C.GESLayer) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[TimelineOverrides](instance0)
	if overrides.LayerRemoved == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected TimelineOverrides.LayerRemoved, got none")
	}

	var _layer *Layer // out

	_layer = wrapLayer(coreglib.Take(unsafe.Pointer(arg1)))

	overrides.LayerRemoved(_layer)
}

//export _gotk4_ges1_TimelineClass_track_added
func _gotk4_ges1_TimelineClass_track_added(arg0 *C.GESTimeline, arg1 *C.GESTrack) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[TimelineOverrides](instance0)
	if overrides.TrackAdded == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected TimelineOverrides.TrackAdded, got none")
	}

	var _track *Track // out

	_track = wrapTrack(coreglib.Take(unsafe.Pointer(arg1)))

	overrides.TrackAdded(_track)
}

//export _gotk4_ges1_TimelineClass_track_removed
func _gotk4_ges1_TimelineClass_track_removed(arg0 *C.GESTimeline, arg1 *C.GESTrack) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[TimelineOverrides](instance0)
	if overrides.TrackRemoved == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected TimelineOverrides.TrackRemoved, got none")
	}

	var _track *Track // out

	_track = wrapTrack(coreglib.Take(unsafe.Pointer(arg1)))

	overrides.TrackRemoved(_track)
}

//export _gotk4_ges1_Timeline_ConnectCommited
func _gotk4_ges1_Timeline_ConnectCommited(arg0 C.gpointer, arg1 C.guintptr) {
	var f func()
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg1))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func())
	}

	f()
}

//export _gotk4_ges1_Timeline_ConnectGroupAdded
func _gotk4_ges1_Timeline_ConnectGroupAdded(arg0 C.gpointer, arg1 *C.GESGroup, arg2 C.guintptr) {
	var f func(group *Group)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg2))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(group *Group))
	}

	var _group *Group // out

	_group = wrapGroup(coreglib.Take(unsafe.Pointer(arg1)))

	f(_group)
}

//export _gotk4_ges1_Timeline_ConnectLayerAdded
func _gotk4_ges1_Timeline_ConnectLayerAdded(arg0 C.gpointer, arg1 *C.GESLayer, arg2 C.guintptr) {
	var f func(layer *Layer)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg2))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(layer *Layer))
	}

	var _layer *Layer // out

	_layer = wrapLayer(coreglib.Take(unsafe.Pointer(arg1)))

	f(_layer)
}

//export _gotk4_ges1_Timeline_ConnectLayerRemoved
func _gotk4_ges1_Timeline_ConnectLayerRemoved(arg0 C.gpointer, arg1 *C.GESLayer, arg2 C.guintptr) {
	var f func(layer *Layer)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg2))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(layer *Layer))
	}

	var _layer *Layer // out

	_layer = wrapLayer(coreglib.Take(unsafe.Pointer(arg1)))

	f(_layer)
}

//export _gotk4_ges1_Timeline_ConnectSelectElementTrack
func _gotk4_ges1_Timeline_ConnectSelectElementTrack(arg0 C.gpointer, arg1 *C.GESClip, arg2 *C.GESTrackElement, arg3 C.guintptr) (cret *C.GESTrack) {
	var f func(clip Clipper, trackElement TrackElementer) (track *Track)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg3))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(clip Clipper, trackElement TrackElementer) (track *Track))
	}

	var _clip Clipper                // out
	var _trackElement TrackElementer // out

	{
		objptr := unsafe.Pointer(arg1)
		if objptr == nil {
			panic("object of type ges.Clipper is nil")
		}

		object := coreglib.Take(objptr)
		casted := object.WalkCast(func(obj coreglib.Objector) bool {
			_, ok := obj.(Clipper)
			return ok
		})
		rv, ok := casted.(Clipper)
		if !ok {
			panic("no marshaler for " + object.TypeFromInstance().String() + " matching ges.Clipper")
		}
		_clip = rv
	}
	{
		objptr := unsafe.Pointer(arg2)
		if objptr == nil {
			panic("object of type ges.TrackElementer is nil")
		}

		object := coreglib.Take(objptr)
		casted := object.WalkCast(func(obj coreglib.Objector) bool {
			_, ok := obj.(TrackElementer)
			return ok
		})
		rv, ok := casted.(TrackElementer)
		if !ok {
			panic("no marshaler for " + object.TypeFromInstance().String() + " matching ges.TrackElementer")
		}
		_trackElement = rv
	}

	track := f(_clip, _trackElement)

	var _ *Track

	if track != nil {
		cret = (*C.GESTrack)(unsafe.Pointer(coreglib.InternObject(track).Native()))
		C.g_object_ref(C.gpointer(coreglib.InternObject(track).Native()))
	}

	return cret
}

//export _gotk4_ges1_Timeline_ConnectSnappingEnded
func _gotk4_ges1_Timeline_ConnectSnappingEnded(arg0 C.gpointer, arg1 *C.GESTrackElement, arg2 *C.GESTrackElement, arg3 C.guint64, arg4 C.guintptr) {
	var f func(obj1, obj2 TrackElementer, position uint64)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg4))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(obj1, obj2 TrackElementer, position uint64))
	}

	var _obj1 TrackElementer // out
	var _obj2 TrackElementer // out
	var _position uint64     // out

	{
		objptr := unsafe.Pointer(arg1)
		if objptr == nil {
			panic("object of type ges.TrackElementer is nil")
		}

		object := coreglib.Take(objptr)
		casted := object.WalkCast(func(obj coreglib.Objector) bool {
			_, ok := obj.(TrackElementer)
			return ok
		})
		rv, ok := casted.(TrackElementer)
		if !ok {
			panic("no marshaler for " + object.TypeFromInstance().String() + " matching ges.TrackElementer")
		}
		_obj1 = rv
	}
	{
		objptr := unsafe.Pointer(arg2)
		if objptr == nil {
			panic("object of type ges.TrackElementer is nil")
		}

		object := coreglib.Take(objptr)
		casted := object.WalkCast(func(obj coreglib.Objector) bool {
			_, ok := obj.(TrackElementer)
			return ok
		})
		rv, ok := casted.(TrackElementer)
		if !ok {
			panic("no marshaler for " + object.TypeFromInstance().String() + " matching ges.TrackElementer")
		}
		_obj2 = rv
	}
	_position = uint64(arg3)

	f(_obj1, _obj2, _position)
}

//export _gotk4_ges1_Timeline_ConnectSnappingStarted
func _gotk4_ges1_Timeline_ConnectSnappingStarted(arg0 C.gpointer, arg1 *C.GESTrackElement, arg2 *C.GESTrackElement, arg3 C.guint64, arg4 C.guintptr) {
	var f func(obj1, obj2 TrackElementer, position uint64)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg4))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(obj1, obj2 TrackElementer, position uint64))
	}

	var _obj1 TrackElementer // out
	var _obj2 TrackElementer // out
	var _position uint64     // out

	{
		objptr := unsafe.Pointer(arg1)
		if objptr == nil {
			panic("object of type ges.TrackElementer is nil")
		}

		object := coreglib.Take(objptr)
		casted := object.WalkCast(func(obj coreglib.Objector) bool {
			_, ok := obj.(TrackElementer)
			return ok
		})
		rv, ok := casted.(TrackElementer)
		if !ok {
			panic("no marshaler for " + object.TypeFromInstance().String() + " matching ges.TrackElementer")
		}
		_obj1 = rv
	}
	{
		objptr := unsafe.Pointer(arg2)
		if objptr == nil {
			panic("object of type ges.TrackElementer is nil")
		}

		object := coreglib.Take(objptr)
		casted := object.WalkCast(func(obj coreglib.Objector) bool {
			_, ok := obj.(TrackElementer)
			return ok
		})
		rv, ok := casted.(TrackElementer)
		if !ok {
			panic("no marshaler for " + object.TypeFromInstance().String() + " matching ges.TrackElementer")
		}
		_obj2 = rv
	}
	_position = uint64(arg3)

	f(_obj1, _obj2, _position)
}

//export _gotk4_ges1_Timeline_ConnectTrackAdded
func _gotk4_ges1_Timeline_ConnectTrackAdded(arg0 C.gpointer, arg1 *C.GESTrack, arg2 C.guintptr) {
	var f func(track *Track)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg2))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(track *Track))
	}

	var _track *Track // out

	_track = wrapTrack(coreglib.Take(unsafe.Pointer(arg1)))

	f(_track)
}

//export _gotk4_ges1_Timeline_ConnectTrackRemoved
func _gotk4_ges1_Timeline_ConnectTrackRemoved(arg0 C.gpointer, arg1 *C.GESTrack, arg2 C.guintptr) {
	var f func(track *Track)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg2))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(track *Track))
	}

	var _track *Track // out

	_track = wrapTrack(coreglib.Take(unsafe.Pointer(arg1)))

	f(_track)
}

//export _gotk4_ges1_TimelineElementClass_deep_copy
func _gotk4_ges1_TimelineElementClass_deep_copy(arg0 *C.GESTimelineElement, arg1 *C.GESTimelineElement) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[TimelineElementOverrides](instance0)
	if overrides.DeepCopy == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected TimelineElementOverrides.DeepCopy, got none")
	}

	var _copy TimelineElementer // out

	{
		objptr := unsafe.Pointer(arg1)
		if objptr == nil {
			panic("object of type ges.TimelineElementer is nil")
		}

		object := coreglib.Take(objptr)
		casted := object.WalkCast(func(obj coreglib.Objector) bool {
			_, ok := obj.(TimelineElementer)
			return ok
		})
		rv, ok := casted.(TimelineElementer)
		if !ok {
			panic("no marshaler for " + object.TypeFromInstance().String() + " matching ges.TimelineElementer")
		}
		_copy = rv
	}

	overrides.DeepCopy(_copy)
}

//export _gotk4_ges1_TimelineElementClass_get_layer_priority
func _gotk4_ges1_TimelineElementClass_get_layer_priority(arg0 *C.GESTimelineElement) (cret C.guint32) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[TimelineElementOverrides](instance0)
	if overrides.LayerPriority == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected TimelineElementOverrides.LayerPriority, got none")
	}

	guint32 := overrides.LayerPriority()

	var _ uint32

	cret = C.guint32(guint32)

	return cret
}

//export _gotk4_ges1_TimelineElementClass_get_natural_framerate
func _gotk4_ges1_TimelineElementClass_get_natural_framerate(arg0 *C.GESTimelineElement, arg1 *C.gint, arg2 *C.gint) (cret C.gboolean) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[TimelineElementOverrides](instance0)
	if overrides.NaturalFramerate == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected TimelineElementOverrides.NaturalFramerate, got none")
	}

	framerateN, framerateD, ok := overrides.NaturalFramerate()

	var _ int
	var _ int
	var _ bool

	*arg1 = C.gint(framerateN)
	*arg2 = C.gint(framerateD)
	if ok {
		cret = C.TRUE
	}

	return cret
}

//export _gotk4_ges1_TimelineElementClass_get_track_types
func _gotk4_ges1_TimelineElementClass_get_track_types(arg0 *C.GESTimelineElement) (cret C.GESTrackType) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[TimelineElementOverrides](instance0)
	if overrides.TrackTypes == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected TimelineElementOverrides.TrackTypes, got none")
	}

	trackType := overrides.TrackTypes()

	var _ TrackType

	cret = C.GESTrackType(trackType)

	return cret
}

//export _gotk4_ges1_TimelineElementClass_ripple
func _gotk4_ges1_TimelineElementClass_ripple(arg0 *C.GESTimelineElement, arg1 C.guint64) (cret C.gboolean) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[TimelineElementOverrides](instance0)
	if overrides.Ripple == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected TimelineElementOverrides.Ripple, got none")
	}

	var _start uint64 // out

	_start = uint64(arg1)

	ok := overrides.Ripple(_start)

	var _ bool

	if ok {
		cret = C.TRUE
	}

	return cret
}

//export _gotk4_ges1_TimelineElementClass_ripple_end
func _gotk4_ges1_TimelineElementClass_ripple_end(arg0 *C.GESTimelineElement, arg1 C.guint64) (cret C.gboolean) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[TimelineElementOverrides](instance0)
	if overrides.RippleEnd == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected TimelineElementOverrides.RippleEnd, got none")
	}

	var _end uint64 // out

	_end = uint64(arg1)

	ok := overrides.RippleEnd(_end)

	var _ bool

	if ok {
		cret = C.TRUE
	}

	return cret
}

//export _gotk4_ges1_TimelineElementClass_roll_end
func _gotk4_ges1_TimelineElementClass_roll_end(arg0 *C.GESTimelineElement, arg1 C.guint64) (cret C.gboolean) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[TimelineElementOverrides](instance0)
	if overrides.RollEnd == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected TimelineElementOverrides.RollEnd, got none")
	}

	var _end uint64 // out

	_end = uint64(arg1)

	ok := overrides.RollEnd(_end)

	var _ bool

	if ok {
		cret = C.TRUE
	}

	return cret
}

//export _gotk4_ges1_TimelineElementClass_roll_start
func _gotk4_ges1_TimelineElementClass_roll_start(arg0 *C.GESTimelineElement, arg1 C.guint64) (cret C.gboolean) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[TimelineElementOverrides](instance0)
	if overrides.RollStart == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected TimelineElementOverrides.RollStart, got none")
	}

	var _start uint64 // out

	_start = uint64(arg1)

	ok := overrides.RollStart(_start)

	var _ bool

	if ok {
		cret = C.TRUE
	}

	return cret
}

//export _gotk4_ges1_TimelineElementClass_set_duration
func _gotk4_ges1_TimelineElementClass_set_duration(arg0 *C.GESTimelineElement, arg1 C.GstClockTime) (cret C.gboolean) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[TimelineElementOverrides](instance0)
	if overrides.SetDuration == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected TimelineElementOverrides.SetDuration, got none")
	}

	var _duration gst.ClockTime // out

	_duration = gst.ClockTime(arg1)

	ok := overrides.SetDuration(_duration)

	var _ bool

	if ok {
		cret = C.TRUE
	}

	return cret
}

//export _gotk4_ges1_TimelineElementClass_set_inpoint
func _gotk4_ges1_TimelineElementClass_set_inpoint(arg0 *C.GESTimelineElement, arg1 C.GstClockTime) (cret C.gboolean) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[TimelineElementOverrides](instance0)
	if overrides.SetInpoint == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected TimelineElementOverrides.SetInpoint, got none")
	}

	var _inpoint gst.ClockTime // out

	_inpoint = gst.ClockTime(arg1)

	ok := overrides.SetInpoint(_inpoint)

	var _ bool

	if ok {
		cret = C.TRUE
	}

	return cret
}

//export _gotk4_ges1_TimelineElementClass_set_max_duration
func _gotk4_ges1_TimelineElementClass_set_max_duration(arg0 *C.GESTimelineElement, arg1 C.GstClockTime) (cret C.gboolean) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[TimelineElementOverrides](instance0)
	if overrides.SetMaxDuration == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected TimelineElementOverrides.SetMaxDuration, got none")
	}

	var _maxduration gst.ClockTime // out

	_maxduration = gst.ClockTime(arg1)

	ok := overrides.SetMaxDuration(_maxduration)

	var _ bool

	if ok {
		cret = C.TRUE
	}

	return cret
}

//export _gotk4_ges1_TimelineElementClass_set_parent
func _gotk4_ges1_TimelineElementClass_set_parent(arg0 *C.GESTimelineElement, arg1 *C.GESTimelineElement) (cret C.gboolean) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[TimelineElementOverrides](instance0)
	if overrides.SetParent == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected TimelineElementOverrides.SetParent, got none")
	}

	var _parent TimelineElementer // out

	{
		objptr := unsafe.Pointer(arg1)
		if objptr == nil {
			panic("object of type ges.TimelineElementer is nil")
		}

		object := coreglib.Take(objptr)
		casted := object.WalkCast(func(obj coreglib.Objector) bool {
			_, ok := obj.(TimelineElementer)
			return ok
		})
		rv, ok := casted.(TimelineElementer)
		if !ok {
			panic("no marshaler for " + object.TypeFromInstance().String() + " matching ges.TimelineElementer")
		}
		_parent = rv
	}

	ok := overrides.SetParent(_parent)

	var _ bool

	if ok {
		cret = C.TRUE
	}

	return cret
}

//export _gotk4_ges1_TimelineElementClass_set_priority
func _gotk4_ges1_TimelineElementClass_set_priority(arg0 *C.GESTimelineElement, arg1 C.guint32) (cret C.gboolean) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[TimelineElementOverrides](instance0)
	if overrides.SetPriority == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected TimelineElementOverrides.SetPriority, got none")
	}

	var _priority uint32 // out

	_priority = uint32(arg1)

	ok := overrides.SetPriority(_priority)

	var _ bool

	if ok {
		cret = C.TRUE
	}

	return cret
}

//export _gotk4_ges1_TimelineElementClass_set_start
func _gotk4_ges1_TimelineElementClass_set_start(arg0 *C.GESTimelineElement, arg1 C.GstClockTime) (cret C.gboolean) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[TimelineElementOverrides](instance0)
	if overrides.SetStart == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected TimelineElementOverrides.SetStart, got none")
	}

	var _start gst.ClockTime // out

	_start = gst.ClockTime(arg1)

	ok := overrides.SetStart(_start)

	var _ bool

	if ok {
		cret = C.TRUE
	}

	return cret
}

//export _gotk4_ges1_TimelineElementClass_trim
func _gotk4_ges1_TimelineElementClass_trim(arg0 *C.GESTimelineElement, arg1 C.guint64) (cret C.gboolean) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[TimelineElementOverrides](instance0)
	if overrides.Trim == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected TimelineElementOverrides.Trim, got none")
	}

	var _start uint64 // out

	_start = uint64(arg1)

	ok := overrides.Trim(_start)

	var _ bool

	if ok {
		cret = C.TRUE
	}

	return cret
}

//export _gotk4_ges1_Track_ConnectCommited
func _gotk4_ges1_Track_ConnectCommited(arg0 C.gpointer, arg1 C.guintptr) {
	var f func()
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg1))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func())
	}

	f()
}

//export _gotk4_ges1_Track_ConnectTrackElementAdded
func _gotk4_ges1_Track_ConnectTrackElementAdded(arg0 C.gpointer, arg1 *C.GESTrackElement, arg2 C.guintptr) {
	var f func(effect TrackElementer)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg2))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(effect TrackElementer))
	}

	var _effect TrackElementer // out

	{
		objptr := unsafe.Pointer(arg1)
		if objptr == nil {
			panic("object of type ges.TrackElementer is nil")
		}

		object := coreglib.Take(objptr)
		casted := object.WalkCast(func(obj coreglib.Objector) bool {
			_, ok := obj.(TrackElementer)
			return ok
		})
		rv, ok := casted.(TrackElementer)
		if !ok {
			panic("no marshaler for " + object.TypeFromInstance().String() + " matching ges.TrackElementer")
		}
		_effect = rv
	}

	f(_effect)
}

//export _gotk4_ges1_Track_ConnectTrackElementRemoved
func _gotk4_ges1_Track_ConnectTrackElementRemoved(arg0 C.gpointer, arg1 *C.GESTrackElement, arg2 C.guintptr) {
	var f func(effect TrackElementer)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg2))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(effect TrackElementer))
	}

	var _effect TrackElementer // out

	{
		objptr := unsafe.Pointer(arg1)
		if objptr == nil {
			panic("object of type ges.TrackElementer is nil")
		}

		object := coreglib.Take(objptr)
		casted := object.WalkCast(func(obj coreglib.Objector) bool {
			_, ok := obj.(TrackElementer)
			return ok
		})
		rv, ok := casted.(TrackElementer)
		if !ok {
			panic("no marshaler for " + object.TypeFromInstance().String() + " matching ges.TrackElementer")
		}
		_effect = rv
	}

	f(_effect)
}

//export _gotk4_ges1_TrackElementClass_active_changed
func _gotk4_ges1_TrackElementClass_active_changed(arg0 *C.GESTrackElement, arg1 C.gboolean) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[TrackElementOverrides](instance0)
	if overrides.ActiveChanged == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected TrackElementOverrides.ActiveChanged, got none")
	}

	var _active bool // out

	if arg1 != 0 {
		_active = true
	}

	overrides.ActiveChanged(_active)
}

//export _gotk4_ges1_TrackElementClass_changed
func _gotk4_ges1_TrackElementClass_changed(arg0 *C.GESTrackElement) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[TrackElementOverrides](instance0)
	if overrides.Changed == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected TrackElementOverrides.Changed, got none")
	}

	overrides.Changed()
}

//export _gotk4_ges1_TrackElementClass_create_element
func _gotk4_ges1_TrackElementClass_create_element(arg0 *C.GESTrackElement) (cret *C.GstElement) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[TrackElementOverrides](instance0)
	if overrides.CreateElement == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected TrackElementOverrides.CreateElement, got none")
	}

	element := overrides.CreateElement()

	var _ gst.Elementer

	cret = (*C.GstElement)(unsafe.Pointer(coreglib.InternObject(element).Native()))

	return cret
}

//export _gotk4_ges1_TrackElementClass_create_gnl_object
func _gotk4_ges1_TrackElementClass_create_gnl_object(arg0 *C.GESTrackElement) (cret *C.GstElement) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[TrackElementOverrides](instance0)
	if overrides.CreateGnlObject == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected TrackElementOverrides.CreateGnlObject, got none")
	}

	element := overrides.CreateGnlObject()

	var _ gst.Elementer

	cret = (*C.GstElement)(unsafe.Pointer(coreglib.InternObject(element).Native()))

	return cret
}

//export _gotk4_ges1_TrackElement_ConnectControlBindingAdded
func _gotk4_ges1_TrackElement_ConnectControlBindingAdded(arg0 C.gpointer, arg1 *C.GstControlBinding, arg2 C.guintptr) {
	var f func(controlBinding gst.ControlBindinger)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg2))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(controlBinding gst.ControlBindinger))
	}

	var _controlBinding gst.ControlBindinger // out

	{
		objptr := unsafe.Pointer(arg1)
		if objptr == nil {
			panic("object of type gst.ControlBindinger is nil")
		}

		object := coreglib.Take(objptr)
		casted := object.WalkCast(func(obj coreglib.Objector) bool {
			_, ok := obj.(gst.ControlBindinger)
			return ok
		})
		rv, ok := casted.(gst.ControlBindinger)
		if !ok {
			panic("no marshaler for " + object.TypeFromInstance().String() + " matching gst.ControlBindinger")
		}
		_controlBinding = rv
	}

	f(_controlBinding)
}

//export _gotk4_ges1_TrackElement_ConnectControlBindingRemoved
func _gotk4_ges1_TrackElement_ConnectControlBindingRemoved(arg0 C.gpointer, arg1 *C.GstControlBinding, arg2 C.guintptr) {
	var f func(controlBinding gst.ControlBindinger)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg2))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(controlBinding gst.ControlBindinger))
	}

	var _controlBinding gst.ControlBindinger // out

	{
		objptr := unsafe.Pointer(arg1)
		if objptr == nil {
			panic("object of type gst.ControlBindinger is nil")
		}

		object := coreglib.Take(objptr)
		casted := object.WalkCast(func(obj coreglib.Objector) bool {
			_, ok := obj.(gst.ControlBindinger)
			return ok
		})
		rv, ok := casted.(gst.ControlBindinger)
		if !ok {
			panic("no marshaler for " + object.TypeFromInstance().String() + " matching gst.ControlBindinger")
		}
		_controlBinding = rv
	}

	f(_controlBinding)
}

//export _gotk4_ges1_TrackElementAssetClass_get_natural_framerate
func _gotk4_ges1_TrackElementAssetClass_get_natural_framerate(arg0 *C.GESTrackElementAsset, arg1 *C.gint, arg2 *C.gint) (cret C.gboolean) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[TrackElementAssetOverrides](instance0)
	if overrides.NaturalFramerate == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected TrackElementAssetOverrides.NaturalFramerate, got none")
	}

	framerateN, framerateD, ok := overrides.NaturalFramerate()

	var _ int
	var _ int
	var _ bool

	*arg1 = C.gint(framerateN)
	*arg2 = C.gint(framerateD)
	if ok {
		cret = C.TRUE
	}

	return cret
}
